### ISSUE TITLE
have been getting this issue for a few weeks, probably a easy fix ( see log below )

### ISSUE THREAD

**Issue by walkingspaceman** [HashLips/hashlips_art_engine#1]
Lords-iMac:hashlips_art_engine-main blackjosh$ node index.js
(node:11835) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/blackjosh/Desktop/hashlips_art_engine-main/node_modules/canvas/build/Release/libpixman-1.0.40.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/blackjosh/Desktop/hashlips_art_engine-main/node_modules/canvas/build/Release/libpixman-1.0.40.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6

**Comment by HashLips** [comment]
Thank you that is just a dependency warning the program should still work right? Will update that in the next version. Also use Yarn to install.

**Comment by jpaezsa** [comment]
> warning t

Hello @HashLips Daniel!…
I have the same issue when i tray to create bigger images, any image mayor to 512px give me this error, eg. 513px or 2500px 

I run a mac os 10.13 - impossible to upgrade no 10.15 :(  

Any idea how fix it?

I really appreciate your work, tks 4 sharing!
