### ISSUE TITLE
Getting this error message with "eyeball" but I deleted it from the code and don't have any folders named eyeball?

### ISSUE THREAD

**Issue by kfrains** [HashLips/hashlips_art_engine#1000]
HELP! Anyone else getting this message and know how to fix it?
 
errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\kathe\\create-10k-nft-collection-2.0.0/layers/Eyeball/'

**Comment by bolshoytoster** [comment]
@kfrains save your `src/config.js` file.

**Comment by kfrains** [comment]
That worked, thank you!!
