### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by ZyryZ06** [HashLips/hashlips_art_engine#1004]
> hashlips_art_engine@1.1.1 generate
> node index.js

(node:10332) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead   
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\ZyryZ\Desktop\Mad Rabbit Nft\hashlips_art_engine/layers/Background/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (C:\Users\ZyryZ\Desktop\Mad Rabbit Nft\hashlips_art_engine\src\main.js:73:6)
    at C:\Users\ZyryZ\Desktop\Mad Rabbit Nft\hashlips_art_engine\src\main.js:92:15     
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\ZyryZ\Desktop\Mad Rabbit Nft\hashlips_art_engine\src\main.js:90:30)
    at startCreating (C:\Users\ZyryZ\Desktop\Mad Rabbit Nft\hashlips_art_engine\src\main.js:356:20)
    at C:\Users\ZyryZ\Desktop\Mad Rabbit Nft\hashlips_art_engine\index.js:6:3
    at Object.<anonymous> (C:\Users\ZyryZ\Desktop\Mad Rabbit Nft\hashlips_art_engine\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) {      
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\ZyryZ\\Desktop\\Mad Rabbit Nft\\hashlips_art_engine/layers/Background/'
}

I have been all over the forums, I have tried numerous fixes, and it seems everytime I fix something, I run into a new problem, please help. I want to get this to work rather than making nfts on an easier platform, at this point ive come to far

**Comment by bolshoytoster** [comment]
@ZyryZ06 save your `src/config.js`.

**Comment by ZyryZ06** [comment]
> @ZyryZ06 save your `src/config.js`.

I have done that

**Comment by bolshoytoster** [comment]
@ZyryZ06 can you paste your `layersConfiguration` please.

**Comment by ZyryZ06** [comment]
> @ZyryZ06 can you paste your `layersConfiguration` please.
Im not positive what you mean. are you referring to my folders?

**Comment by bolshoytoster** [comment]
@ZyryZ06 the bit in your `src/config.js` you should've changed.

**Comment by ZyryZ06** [comment]
lol, I may have found my problem. im going to fix this and see what happens next

**Comment by ZyryZ06** [comment]
> @ZyryZ06 the bit in your `src/config.js` you should've changed.

const layerConfigurations = [
  {
    growEditionSizeTo: 5,
    layersOrder: [
      { name: "1-Background" },
      { name: "2-Skin" },
      { name: "3-Clothes" },
      { name: "4-Eyes" },
      { name: "5-Hats" },
      { name: "6-Mouth" },
      { name: "7-Eye Accessories" },
      { name: "8-Earings" },
      { name: "9-Necklace" },

**Comment by bolshoytoster** [comment]
@ZyryZ06 can you paste the error you're getting please.

**Comment by ZyryZ06** [comment]
> @ZyryZ06 can you paste the error you're getting please.

I do believe I found the problem, I had a couple typos.
Thanks for directing me in the right direction, Ive tried everything
