### ISSUE TITLE
I can't deploy the site

### ISSUE THREAD

**Issue by HelloWorld44** [HashLips/hashlips_art_engine#1019]
1:42:48 PM: Build ready to start
1:42:53 PM: build-image version: 2d975aac035b49faec3566497e1a23664999ac04 (focal)
1:42:53 PM: build-image tag: v4.7.0
1:42:53 PM: buildbot version: 51f079eb2b8422b2dd4a536784559216feb9524d
1:42:53 PM: Fetching cached dependencies
1:42:53 PM: Failed to fetch cache, continuing with build
1:42:53 PM: Starting to prepare the repo for build
1:42:53 PM: No cached dependencies found. Cloning fresh repo
1:42:53 PM: git clone https://github.com/HelloWorld44/test2
1:42:54 PM: Preparing Git Reference refs/heads/main
1:42:54 PM: Parsing package.json dependencies
1:42:54 PM: Different build dir detected, going to use the one specified in the Netlify configuration file: '' versus '/' in the Netlify UI
1:42:55 PM: Starting build script
1:42:55 PM: Installing dependencies
1:42:55 PM: Python version set to 2.7
1:42:55 PM: v16.14.2 is already installed.
1:42:56 PM: Now using node v16.14.2 (npm v8.5.0)
1:42:56 PM: Started restoring cached build plugins
1:42:56 PM: Finished restoring cached build plugins
1:42:56 PM: Attempting ruby version 2.7.2, read from environment
1:42:57 PM: Using ruby version 2.7.2
1:42:57 PM: Using PHP version 8.0
1:42:57 PM: Started restoring cached go cache
1:42:57 PM: Finished restoring cached go cache
1:42:57 PM: go version go1.16.5 linux/amd64
1:42:57 PM: go version go1.16.5 linux/amd64
1:42:57 PM: Installing missing commands
1:42:57 PM: Verify run directory
1:42:58 PM: ​
1:42:58 PM: ────────────────────────────────────────────────────────────────
1:42:58 PM: Netlify Build
1:42:58 PM: ────────────────────────────────────────────────────────────────
1:42:58 PM: ​
1:42:58 PM: ❯ Version
1:42:58 PM: @netlify/build 26.5.1
1:42:58 PM: ​
1:42:58 PM: ❯ Flags
1:42:58 PM: baseRelDir: true
1:42:58 PM: buildId: 624585a877c6aa3b6e3d0729
1:42:58 PM: deployId: 624585a877c6aa3b6e3d072b
1:42:58 PM: ​
1:42:58 PM: ❯
1:42:58 PM: /opt/build/repo
1:42:58 PM: ​
1:42:58 PM: ❯ Config file
1:42:58 PM: No config file was defined: using default values.
1:42:58 PM: ​
1:42:58 PM: ❯ Context
1:42:58 PM: production
1:42:58 PM: ​
1:42:58 PM: ────────────────────────────────────────────────────────────────
1:42:58 PM: 1. Build command from Netlify app
1:42:58 PM: ────────────────────────────────────────────────────────────────
1:42:58 PM: ​
1:42:58 PM: $ npm run build
1:42:59 PM: npm ERR! code ENOENT
1:42:59 PM: npm ERR! syscall open
1:42:59 PM: npm ERR! path /opt/build/repo/package.json
1:42:59 PM: npm ERR! errno -2
1:42:59 PM: npm ERR! enoent ENOENT: no such file or directory, open '/opt/build/repo/package.json'
1:42:59 PM: npm ERR! enoent This is related to npm not being able to find a file.
1:42:59 PM: npm ERR! enoent
1:42:59 PM: npm ERR! A complete log of this run can be found in:
1:42:59 PM: npm ERR! /opt/buildhome/.npm/_logs/2022-03-31T10_42_58_992Z-debug-0.log
1:42:59 PM: ​
1:42:59 PM: ────────────────────────────────────────────────────────────────
1:42:59 PM: "build.command" failed
1:42:59 PM: ────────────────────────────────────────────────────────────────
1:42:59 PM: ​
1:42:59 PM: Error message
1:42:59 PM: Command failed with exit code 254: npm run build (https://ntl.fyi/exit-code-254)
1:42:59 PM: ​
1:42:59 PM: Error location
1:42:59 PM: In Build command from Netlify app:
1:42:59 PM: npm run build
1:42:59 PM: ​
1:42:59 PM: Resolved config
1:42:59 PM: build:
1:42:59 PM: base: /opt/build/repo
1:42:59 PM: command: npm run build
1:42:59 PM: commandOrigin: ui
1:42:59 PM: publish: /opt/build/repo/build
1:42:59 PM: publishOrigin: ui
1:42:59 PM: Caching artifacts
1:42:59 PM: Started saving build plugins
1:42:59 PM: Finished saving build plugins
1:42:59 PM: Started saving pip cache
1:42:59 PM: Finished saving pip cache
1:43:01 PM: Creating deploy upload records
1:42:59 PM: Started saving emacs cask dependencies
1:42:59 PM: Finished saving emacs cask dependencies
1:42:59 PM: Started saving maven dependencies
1:42:59 PM: Finished saving maven dependencies
1:42:59 PM: Started saving boot dependencies
1:42:59 PM: Finished saving boot dependencies
1:43:01 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
1:42:59 PM: Started saving rust rustup cache
1:42:59 PM: Finished saving rust rustup cache
1:42:59 PM: Started saving go dependencies
1:42:59 PM: Finished saving go dependencies
1:43:01 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
1:43:01 PM: Failing build: Failed to build site
1:43:01 PM: Finished processing build request in 8.092288256s

**Comment by bolshoytoster** [comment]
@HelloWorld44 you’re running `npm run build` from the wrong directory. Run it in the one with `package.json`.
