### ISSUE TITLE
I am stuck here please help!!!

### ISSUE THREAD

**Issue by elda1981** [HashLips/hashlips_art_engine#1027]
Dimi-MBP:hashlips_art_engine-1.1.2_patch_v6 dimi$ npm run build

> hashlips_art_engine@1.1.1 build /Users/dimi/Downloads/hashlips_art_engine-1.1.2_patch_v6
> node index.js

(node:5347) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at removeQueryStrings (/Users/dimi/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js:274:15)
    at cleanDna (/Users/dimi/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js:60:26)
    at /Users/dimi/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js:225:22
    at Array.find (<anonymous>)
    at /Users/dimi/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js:224:42
    at Array.map (<anonymous>)
    at constructLayerToDna (/Users/dimi/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js:223:35)
    at startCreating (/Users/dimi/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js:364:23)
    at /Users/dimi/Downloads/hashlips_art_engine-1.1.2_patch_v6/index.js:6:3
    at Object.<anonymous> (/Users/dimi/Downloads/hashlips_art_engine-1.1.2_patch_v6/index.js:7:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5347) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5347) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Dimi-MBP:hashlips_art_engine-1.1.2_patch_v6 dimi$

**Comment by bolshoytoster** [comment]
@elda1981 can you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine) please.

**Comment by elda1981** [comment]
@bolshoytoster you are a gem!!! Not sure what it was but it worked!!!!I've been pulling my hair for hours now..
I've tried increasing the number from 5 to 100 but it won't work. Are there any dependencies that won't allow me to do it?

**Comment by bolshoytoster** [comment]
@elda1981 make sure you save the `src/config.js` file.

**Comment by elda1981** [comment]
Fantastic!! @bolshoytoster it worked!! Apparently, I just need to increase my layers in order to increase the number of the output. Thank you once again for your prompt response!! Have a great day :)
