### ISSUE TITLE
Is it possible to have multiple source folders for a single trait?

### ISSUE THREAD

**Issue by rojcyk** [HashLips/hashlips_art_engine#1028]
I'm trying to generate images with different `skin` color. But the accompanying images like `hair` or `facial_hair` need to be different in order to construct the final image. 

So what I would want to achieve is to have two different `layer configurations` which would map to the same metadata but would source different folders like this:

```
const layerConfigurations = [
  {
    growEditionSizeTo: 320,
    layersOrder: [
      { name: "background" },
      { name: "base/black" },
      { name: "neck/black" },
      { name: "top" },
      { name: "jaw-tech" },
      { name: "eyes-tech" },
      { name: "hair/black },
      { name: "ears/black" },
      { name: "jaw/black" },
      { name: "eyes" }
    ],
  }
```

**Result:** 

The trait_type in the generated metadata.json would be shown as just `base` or `neck` and not `base/black`

**Comment by bolshoytoster** [comment]
@rojcyk in `src/main.js` ~line 178:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L177-L179
You should be able to change `value: selectedElement.name,` to `value: selectedElement.name.split('/')[0],`

**Comment by rojcyk** [comment]
@bolshoytoster thank you, works like a charm!
