### ISSUE TITLE
Removing custom_fields and external_url from metadata?

### ISSUE THREAD

**Issue by plasmaHD** [HashLips/hashlips_art_engine#1030]
Is it possible to update either the generation script itself or the update_info script to completely remove custom_fields and external_url from metadata? I only want the name, image, and trait information. Thanks in advance

**Comment by bolshoytoster** [comment]
@plasmaHD in `utils/update_info.js` ~line 26:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/utils/update_info.js#L26-L27

You can insert something like:
```js
delete item.custom_fields
```

**Comment by plasmaHD** [comment]
@bolshoytoster works like a charm. Thanks for quick response.
