### ISSUE TITLE
Generate New Collection - Without Duplicates from Collection 1

### ISSUE THREAD

**Issue by sadun619** [HashLips/hashlips_art_engine#1036]
i need generate 10k collection with 4 drops (2500x4)

how can i shuffle nft's just in one drop without mixing each drops.

**Comment by alpharhoking** [comment]
Did you manage to solve this issue?

**Comment by sadun619** [comment]
> Did you manage to solve this issue?

yes. generated to 4 times. with keeping previous DNS
