### ISSUE TITLE
Can Get rarity from existing metadeta file

### ISSUE THREAD

**Issue by sadun619** [HashLips/hashlips_art_engine#1047]
Can get rarity from already generated, existing _metadeta file.

**Comment by bolshoytoster** [comment]
@sadun619 `node utils/rarity.js`?

**Comment by sadun619** [comment]
is it work for if i get metadata file from another device?

**Comment by sadun619** [comment]
> @sadun619 `node utils/rarity.js`?


is it work for if i get metadata file from another device?

**Comment by bolshoytoster** [comment]
@sadun619 yes, just put it in the `build/json` folder.

**Comment by sadun619** [comment]
ok thank you

> @sadun619 yes, just put it in the `build/json` folder.

It's not working  

Node.js v17.4.0
PS E:\ori\hashlips_art_engine-main> node utils/rarity.js
E:\ori\hashlips_art_engine-main\utils\rarity.js:53
    rarityDataTraits.forEach((rarityDataTrait) => {
                     ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at E:\ori\hashlips_art_engine-main\utils\rarity.js:53:22
    at Array.forEach (<anonymous>)
    at E:\ori\hashlips_art_engine-main\utils\rarity.js:48:14
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\ori\hashlips_art_engine-main\utils\rarity.js:46:6)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

**Comment by bolshoytoster** [comment]
@sadun619 you'll need to copy the `src/config.js` file over as well sorry.

**Comment by sadun619** [comment]
thank you dear.
it's working. copied config and layer.
Thank you so much

**Comment by Pwnkmrdroch** [comment]
How can I get Rarity of complete collection incase I created multiple cases (10+).
Right now I am using node utils/rarity.js but it is showing a rarity of first case only.
Can anyone help asap?

Thank you

**Comment by bolshoytoster** [comment]
@Pwnkmrdroch what do you mean by 'cases'?
