### ISSUE TITLE
trying to change output Filename

### ISSUE THREAD

**Issue by chicky25** [HashLips/hashlips_art_engine#1055]
hi im trying to change the filename of the output file.
so normaly the file is named after the editioncount 

const saveImage = (_editionCount) => {
  fs.writeFileSync(
    `${buildDir}/images/${_editionCount}.png`,
    canvas.toBuffer(`image/png`)

can i somehow change it so that the filename will be the name of the selected layers 
for example if background is called yellow.png the output file will also contain yellow in ints filename + the other names of the layers?

edit : btw im using Version 1.0.6

**Comment by bolshoytoster** [comment]
@chicky25 at ~line 404 in `src/main.js`:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L403-L405

You could change
```js
abstractedIndexes[0]
```
To something like
```js
renderObjectArray.map(i => i.layer.selectedElement.name).join(', ')
```

**Comment by chicky25** [comment]
> 

Thank you Dude. You are legendary.
worked like a charm!

**Comment by chicky25** [comment]
> @chicky25 at ~line 404 in `src/main.js`:
> 
> https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L403-L405
> 
> You could change
> 
> ```js
> abstractedIndexes[0]
> ```
> 
> To something like
> 
> ```js
> renderObjectArray.map(i => i.layer.selectedElement.name).join(', ')
> ```


Thank you Dude. You are legendary.
worked like a charm!
