### ISSUE TITLE
'layerItemsMaxRepeatedTraits' doubt

### ISSUE THREAD

**Issue by bettyboomy** [HashLips/hashlips_art_engine#1066]
Hello guys!

Thanks a lot for your amazing code!

Im trying to use 'layerItemsMaxRepeatedTraits' because I want each item from "hat" layer to repeat only once.

This is my code:

![doubt](https://user-images.githubusercontent.com/101867301/162693070-97391cd6-c8a7-424f-b004-624811814059.png)

It doesn't work for me, the "hat" layer items keep repeating more than once.

Does anyone know why?

Thanks in advance.

BR

Betty

**Comment by bolshoytoster** [comment]
@bettyboomy that's because it's not supported in this repo, I think you meant to use [thePeanutGalleryAndCo's repo](https://github.com/thepeanutgalleryandco/create-and-mint-nft-collection).

**Comment by bettyboomy** [comment]
Oh yes sorry! This is for [thePeanutGalleryAndCo's repo](https://github.com/thepeanutgalleryandco/create-and-mint-nft-collection). Thanks!
