### ISSUE TITLE
adding specific metadata to specific edition

### ISSUE THREAD

**Issue by mosfetti** [HashLips/hashlips_art_engine#1072]
Do you guys know if there's an easy way to implement custom metadata for specific edition?

Let's suppose i have a total of 15 items and the editions are created with 
    `growEditionSizeTo: 5,`
then
    `growEditionSizeTo: 10,`
then
    `growEditionSizeTo: 15,`
    
 I would need a way to tell the code to add an extra metadata for the first 5 items, then another extra metadata for items from 6 to 10, and then extra metadata for items from 11 to 15.
 Of course this is just an example.. with only 15 items I would be able to do it manually, but for collection with 10k items it would be quite impossible to do so..
 
 Thanks for any help

**Comment by bolshoytoster** [comment]
@mosfetti in `src/main.js` ~line 405:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L404-L406

You could change `addMetadata(newDna, abstractedIndexes[0]);` to `addMetadata(newDna, abstractedIndexes[0], layerConfigurations[layerConfigIndex].extraMetadata);`

Then ~line 131
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L130-L132

You can change `(_dna, _edition)` to `(_dna, _edition, _extraMetadata)`.

Then ~line 140:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L140-L141

You can add `..._extraMetadata,`.

---

In `src/config.js` you can now set `extraMetadata` like you set `growEditionSizeTo`.

**Comment by mosfetti** [comment]
thank you very much! I'll try to tinker a little bit now! I'll close the issue if this is working, otherwhise I might ask further help!

**Comment by bolshoytoster** [comment]
@mosfetti if it works for you I'll add it to [my fork](https://github.com/bolshoytoster/hashlips_art_engine/).

**Comment by mosfetti** [comment]
Yes, it's working! Thanks a lot!
