### ISSUE TITLE
Update metadata JSON file error

### ISSUE THREAD

**Issue by tomkjose** [HashLips/hashlips_art_engine#1093]
I was trying to update my baseUri in all JSON files. But keep getting some errors.
 
![image](https://user-images.githubusercontent.com/44130152/163811197-998d85af-2c4a-4b23-9118-c077b82485d5.png)

**Comment by bolshoytoster** [comment]
@IceAge95 this issue does not occur on this repo, could you open this issue on [codeSTACKr's repo](https://github.com/codeSTACKr/create-10k-nft-collection) and/or use the [main `utils/update_info.js`](https://github.com/HashLips/hashlips_art_engine/blob/main/utils/update_info.js).

**Comment by tomkjose** [comment]
I used the [main utils/update_info.js](https://github.com/HashLips/hashlips_art_engine/blob/main/utils/update_info.js) , but it create a copy of the first and last JSON file as undefined.json with  data updated on it, left unchanged remaining files.
![image](https://user-images.githubusercontent.com/44130152/163822597-28ec5454-d0dd-4b83-aeea-09c47ce95310.png)

**Comment by bolshoytoster** [comment]
@IceAge95 does [mine](https://github.com/bolshoytoster/hashlips_art_engine/blob/main/utils/update_info.js) work?

**Comment by tomkjose** [comment]
Worked, but it create a copy of the first and last JSON file as undefined.json with data updated on it, leaving unchanged the remaining files.

**Comment by bolshoytoster** [comment]
@IceAge95 I just had a look at your metadata, and it's missing the `edition` attribute so it looks like you'll either have to open an issue on [codeSTACKr's repo](https://github.com/codeSTACKr/create-10k-nft-collection) (about the original error), or regenerate your collection using either this repo or mine.

**Comment by tomkjose** [comment]
thank You
