### ISSUE TITLE
Sequential image generation

### ISSUE THREAD

**Issue by peazley** [HashLips/hashlips_art_engine#1096]
Is there a way to generate NFT's in order?  0001, 0002, 0003 etc. 

I thought make "const shuffleLayerConfigurations = false;" would keep things in order, but it seems to be generating at random still. 

This is how I've got my layer folders setup

FIRST DIGIT
0.png
1.png
2.png
3.png
4.png
5.png
6.png
7.png
8.png
9.png

SECOND DIGIT
0.png
1.png
2.png
3.png
4.png
5.png
6.png
7.png
8.png
9.png

THIRD DIGIT

FOURTH DIGIT

-- 

no matter what the images are still generated at random, but also says "You need more layers or elements to grow your edition to 10000 artworks!" even though 4 layers of 10 should produce 10k images. 

Is there anyway to accomplish this?

**Comment by bolshoytoster** [comment]
@peazley not currently, since not many people want this, but you could probably implement this yourself.

---

Replace `src/main.js` ~line 362:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L362

with
```js
      let newDna = [];
      for (let i = 4; i >= 0; i--) {
        const digit = Math.floor(editionCount / 10**i);
        newDna.push(`${digit}:${digit}.png`);
      }
      newDna = newDna.join(DNA_DELIMITER)
```

**Comment by peazley** [comment]
Sort of working, but seems to be going through the first layers images (0-9), but then only uses the first image of the other layer (0)

I appreciate your feedback. I'll poke around an see if I can make it function properly. Thanks for pointing me in the right direction.

**Comment by bolshoytoster** [comment]
@peazley what if you change the lines
```js
      for (let i = 4; i >= 0; i--) {
        const digit = Math.floor(editionCount / 10**i);
```
to
```js
      for (let i = 0; i < 5; i++) {
        const digit = Math.floor((editionCount / 10**(4 - i)) % 10);
```

**Comment by peazley** [comment]
@bolshoytoster sorry for my slow response. That still doesn't seem to make it work, I'm getting multiples of the same image it seems. Might be a bit over my head. Maybe just try to manually create them instead.
