### ISSUE TITLE
Custom naming instead of #1, #2, etc.

### ISSUE THREAD

**Issue by designworkplan** [HashLips/hashlips_art_engine#11]
Not an issue but trying to get insights on how to add items to the Metadata. 

I am using "npm i random-character-name" for random names for my NFT artwork.

Added the var to the top 

![Schermafbeelding 2021-09-15 om 22 48 54](https://user-images.githubusercontent.com/17745966/133507334-4f13de05-1528-415a-bcbe-1bf5710b0415.jpg)

Then added a const for adding the names;

![Schermafbeelding 2021-09-15 om 22 45 28](https://user-images.githubusercontent.com/17745966/133506911-ee9041ae-e189-4e00-b215-e1b728be05fa.jpg)

When I change "name: `#${_edition}`," to "name: `#${_randomName}`," as in the constant the program fails.

![Schermafbeelding 2021-09-15 om 22 45 52](https://user-images.githubusercontent.com/17745966/133506952-55bc6982-0a6c-4b44-95ef-47ae2329ade6.jpg)

The image works out great, but cannot seem to get it working into the Metadata.

![1](https://user-images.githubusercontent.com/17745966/133507433-b8121dfa-58ed-4bd8-86a0-eaa31b94e822.png)

Can anyone assist in this. Please connect if you have a solution. Thanks.

**Comment by AlfieDarko** [comment]
what is the error message you get?

from a glance, shouldnt you pass the randomName variable into the function? doesnt look so from here but if you could add a screenshot of your latest changes, I'd be able to better tell you whats happening too.

**Comment by HashLips** [comment]
The best way is to generate the name in the main loop and pass it along to the functions that way you will be able to render it and also add it to the metadata.

**Comment by designworkplan** [comment]
Thank you Alfie for taking a look.

When I try to call the variable randomName into the function, the name is not defined.
![Schermafbeelding 2021-09-16 om 08 33 55](https://user-images.githubusercontent.com/17745966/133561806-a263020b-86ee-4da9-87c5-de4388cbf231.jpg)

This is the output of the metadata
![Schermafbeelding 2021-09-16 om 08 34 50](https://user-images.githubusercontent.com/17745966/133561909-aca8b012-379d-4036-8826-4d8748922de0.jpg)

Any assistance woulde be fanatastic. Thank you in advance.
