### ISSUE TITLE
504 gateway timeout nginx/1.14.0 (Ubuntu)

### ISSUE THREAD

**Issue by zabeast** [HashLips/hashlips_art_engine#1101]
I uploaded my metadata to piñata and it was successful, however when I go to view the metadata it takes ages to load and then it comes to page where it says '504 gateway timeout nginx/1.14.0 (Ubuntu)
<img width="1615" alt="Screen Shot 2022-04-20 at 11 01 24 am" src="https://user-images.githubusercontent.com/104042774/164126105-95b8d35d-705b-49c9-9fe3-8ac1e28619a2.png">
'

**Comment by bolshoytoster** [comment]
@zabeast does [this](https://knowledge.pinata.cloud/en/articles/5537996-why-am-i-getting-a-504-error-when-trying-to-view-a-folder) help?

**Comment by zabeast** [comment]
Yeah it does. so just confirming its the browser that is causing this issue, not anything I've done in regards to coding and etc.

**Comment by bolshoytoster** [comment]
@zabeast It's not the browser, any http status codes starting with 5 are server errors. But it's also not your fault.

**Comment by zabeast** [comment]
> @zabeast It's not the browser, any http status codes starting with 5 are server errors. But it's also not your fault.

alright, is this something I need to resolve in order for everything to work properly or can I move ahead without worrying about it?

**Comment by bolshoytoster** [comment]
@zabeast you don't need to worry about it.
