### ISSUE TITLE
IPFS Resolve error in finding hidden.png in Pinata

### ISSUE THREAD

**Issue by vipdiv** [HashLips/hashlips_art_engine#1105]
I am following along with the Youtube tutorial around 50:00 time mark and he's explaining how to create the metadate for the hidden file. I created that file and uploaded it to pinata. Both the metadate file and image file It shows up fine when I click on it,. His tutorial wanted us to add in hidden.json to the end. However I didn't need to do that, it just showed up as the following:

https://gateway.pinata.cloud/ipfs/QmScfm8QyprYsH3HTjaAVABqnx754vx5rBA3bLDCjTwKJy

{
  "name": "My hidden image",
  "description": "Hidden image",
  "image": "ipfs://QmcGidzhciMTCXei4xgvDENrEzNJZs71s1XsYw9ux9sS73/hidden.png"
]

His tutorial then asks us to copy and paste the hidden png CID so the URL looks like: https://gateway.pinata.cloud/ipfs/QmcGidzhciMTCXei4xgvDENrEzNJZs71s1XsYw9ux9sS73/hidden.png but when I do that I get the following error:

**ipfs resolve -r /ipfs/QmcGidzhciMTCXei4xgvDENrEzNJZs71s1XsYw9ux9sS73/hidden.png: no link named "hidden.png" under QmcGidzhciMTCXei4xgvDENrEzNJZs71s1XsYw9ux9sS73**

this is driving me crazy ;(

**Comment by bolshoytoster** [comment]
@vipdiv you'll be more likely to find a solution if you opened an issue [where you actually got the code](https://github.com/codeSTACKr/create-10k-nft-collection).

**Comment by vipdiv** [comment]
> @vipdiv you'll be more likely to find a solution if you opened an issue [where you actually got the code](https://github.com/codeSTACKr/create-10k-nft-collection).

I got the code from the Hashlips Masterclass on Youtube, https://youtube.com/clip/UgkxjmKUkhXZ2fXDxYctYFnLXh2EhuoUZxAX

**Comment by bolshoytoster** [comment]
@vipdiv oh sorry, I didn't know about that video.

**Comment by vipdiv** [comment]
> @vipdiv oh sorry, I didn't know about that video.

I could have sworn you were listed as a contributor to the hashlips_art_engine. In any event, would you know why one might get that IPFS error?

**Comment by bolshoytoster** [comment]
@vipdiv I am a contributor, but I have no clue about ipfs.

**Comment by vipdiv** [comment]
Figured it out thanks to the Art Engine Discord. It's the folder. Both the Image and Metadata folders must be uploaded to Pinata as folders, not individual files. This was a huge monkey on my back and I can finally move on with the rest of the tutorial phew!
