### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by 1109piyush** [HashLips/hashlips_art_engine#1114]
npm install
![Screenshot 2022-04-23 153005](https://user-images.githubusercontent.com/103021442/164890203-0f4d7b27-19fc-451f-894f-7337f4146f56.png)

**Comment by bolshoytoster** [comment]
@1109piyush you're in the wrong folder. Run `Get-ChildItem -Directory` to get the name, then run `cd ` + the name to change into it.

**Comment by 1109piyush** [comment]
Ok how can i create gif from this

**Comment by bolshoytoster** [comment]
@1109piyush https://github.com/HashLips/hashlips_art_engine/issues/1008#issuecomment-1086636163

**Comment by 1109piyush** [comment]
I tried this the above screenshot is of that repositery

**Comment by bolshoytoster** [comment]
@1109piyush then RTFM or open an issue on that repotitory.

**Comment by Draqee4** [comment]
am also getting same issue

**Comment by bolshoytoster** [comment]
@Draqee4 what issue?

**Comment by Draqee4** [comment]
whenever I tried to run the command npm install I can't install it properly

**Comment by bolshoytoster** [comment]
@Draqee4 can you paste the error here please.

**Comment by Draqee4** [comment]
npm WARN hashlips_art_engine-1.1.2_patch_v6 No repository field.
npm WARN hashlips_art_engine-1.1.2_patch_v6 No README data
npm WARN hashlips_art_engine-1.1.2_patch_v6 No license field.

up to date in 0.686s
found 0 vulnerabilities
PS C:\Users\draqe\Desktop\hashlips_art_engine-1.1.2_patch_v6>

**Comment by Draqee4** [comment]
after typing node index.js 
getting this error 
PS C:\Users\draqe\Desktop\hashlips_art_engine-1.1.2_patch_v6> node index.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\draqe\Desktop\hashlips_art_engine-1.1.2_patch_v6\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
PS C:\Users\draqe\Desktop\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@Draqee4 those are warnings and can be ignored.

**Comment by Draqee4** [comment]
alright but an other thing eating my brain can you pls chk out

**Comment by bolshoytoster** [comment]
@Draqee4
> Error: Cannot find module 'index.js'

You're in the wrong folder. Run `Get-ChildItem -Directory` to get the name, then run `cd ` + the name to change into it.

**Comment by Draqee4** [comment]
alright i will try it thanks

**Comment by Draqee4** [comment]
d-----          3/3/2022   4:47 PM                hashlips_art_engine-1.1.2_patch_v6 its showing this

**Comment by bolshoytoster** [comment]
@Draqee4 then run `cd hashlips_art_engine-1.1.2_patch_v6`.

**Comment by Draqee4** [comment]
done

**Comment by bolshoytoster** [comment]
@Draqee4 you can run `npm install` and `node index.js` now.

**Comment by Draqee4** [comment]
ok
let me try again

**Comment by Draqee4** [comment]
love u bro you save me it takes me 8 to12 hours thanks.................

**Comment by 1109piyush** [comment]
![Screenshot 2022-04-24 124159](https://user-images.githubusercontent.com/103021442/164965774-db7d7611-b637-45a6-8f34-1c0cecf36e59.png)

**Comment by bolshoytoster** [comment]
@1109piyush run `node utils/update_info.js` instead.

**Comment by ChemicalEmotions** [comment]
i cannot get past the initial npm install  and cannot get my nfts to show up in preview at all. i keep receiving errors whether i try yarn, node, or truffle. i need help

**Comment by ChemicalEmotions** [comment]
i'm not sure if i'm using wrong node because all the videos i watch tell me to type commands and none of them work

**Comment by bolshoytoster** [comment]
@ChemicalEmotions can you **please** paste the error here.

**Comment by williamdex60** [comment]
> @1109piyush run `node utils/update_info.js` instead.

Hi! I pasted that but it didn't work either, what other solution do you have?

**Comment by bolshoytoster** [comment]
@williamdex60 does it give an error? If so can you please paste it here.

**Comment by williamdex60** [comment]
> @williamdex60 does it give an error? If so can you please paste it here.

The same error of the picture, when I run, npm run generate

**Comment by bolshoytoster** [comment]
@williamdex60 there are several pictures here, can you please paste the error here.

**Comment by williamdex60** [comment]
> @williamdex60 there are several pictures here, can you please paste the error here.
Error: The module '/home/runner/zghsx9ruruf/node_modules/scrypt/build/Release/scrypt.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by bolshoytoster** [comment]
@williamdex60 run `npm rebuild`
