### ISSUE TITLE
Configure equal rarity

### ISSUE THREAD

**Issue by afaquekhan17** [HashLips/hashlips_art_engine#1116]
![Screenshot (12)](https://user-images.githubusercontent.com/91663130/164968258-ce416470-5a09-41d6-9704-30180e30adc4.png)

Hey, I want to assign equal rarity % to my each trait. But I don't have any coding language, please help.

**Comment by afaquekhan17** [comment]
@bolshoytoster Any help would be appreciated.

**Comment by bolshoytoster** [comment]
@afaquekhan17 they have the same rarity, you'll see it more clearly if you generate a bigger collection.

**Comment by afaquekhan17** [comment]
No, I have generated even 1000 with this and it takes only some traits and skip the others

**Comment by afaquekhan17** [comment]
I have 14 background images, all I want is that it takes every image in equal %
