### ISSUE TITLE
How to set correct Rarity % Chance?

### ISSUE THREAD

**Issue by kingchenc** [HashLips/hashlips_art_engine#1117]
Hey, how to set Rarity % Chance correct in the haslips generator?

Lets say i have this layers and i want the % rarity

Legendary: 5%
Epic: 10%
Rare: 25%
Common: 60%

how to do this? maybe you know @bolshoytoster ?

**Comment by bolshoytoster** [comment]
@kingchenc you could set the weights (the bit after the `#` in the filename) to the rarity percentage you want, i.e. 5, 10, 25, 60

**Comment by kingchenc** [comment]
@bolshoytoster do you have an small example for this? :X

**Comment by bolshoytoster** [comment]
@kingchenc something like this?
```js
layers/
| layer 1/
  | Legendary#5.png
  | Epic#10.png
  | AlsoEpic#10.png
  | Rare#25.png
  | Common#60.png
```

**Comment by kingchenc** [comment]
@bolshoytoster 
Hmm got it, but how can i add this to the layer config? im newbie 🍡 and thanks for help

```
const layerConfigurations = [
  {
    growEditionSizeTo: 250,
    startEditionFrom: 0,
    layersOrder: [
      { name: "Rarity" },
    ],
  },
];

```

or must i need to add this to another section?

**Comment by bolshoytoster** [comment]
@kingchenc you don't beed to do anything to `src/config.js` for this.

**Comment by kingchenc** [comment]
@bolshoytoster 
Ah now i think i understand now :D I must renam the layers with the correct % Chance right? :D

**Comment by bolshoytoster** [comment]
@kingchenc yes.

**Comment by kingchenc** [comment]
@bolshoytoster Nice thank you :)
