### ISSUE TITLE
Need a bit of clarity on how the rarity influences the build image

### ISSUE THREAD

**Issue by rojcyk** [HashLips/hashlips_art_engine#1122]
There is not much about it in the documentation itself but I need to achieve the following.

- I have a layer which I need to be present all the time. (A jacket in our instance)
- I need this layer to be picked from various variants (Coat, riders jacket, armor etc)
- I got the assumption from reading some of the issues that I need to make sure the sum of all the rarities needs to equal to 100. Like in the following picture

![Screenshot 2022-04-27 at 10 15 22](https://user-images.githubusercontent.com/1080609/165473307-6ef34c08-9a0d-45f8-8384-7ecb5cef62ba.png)

- But once I run the build. It turns out it 

![Screenshot 2022-04-27 at 10 19 06](https://user-images.githubusercontent.com/1080609/165474170-cf7169d2-e421-408e-adae-c460b79ef724.png)
is not the case. I have the jacket layer only in about 1/3 of the resulted images.

So my question is: **What do I need to do to generate the images with this top layer? 100% of the time?**

**Comment by bolshoytoster** [comment]
@rojcyk could you paste your `layersConfigurations` here please.

**Comment by JayGalvan90** [comment]
Hey your hash tag on the .png pics are high, if I'm correct the " weight " for rarity should be around #2 in your pic a lot of the png have a weight #10 or #16. So try maybe lowering it to 2 or 3 maybe. I hope that helps, I'm tinkering with my project and did same thing to different food items.

**Comment by bolshoytoster** [comment]
@JayGalvan90 that doesn't matter.

**Comment by JayGalvan90** [comment]
> @JayGalvan90 that doesn't matter.

Really ? Because it works for me, my bad though I hope you find your answer. 🤙🏼

**Comment by rojcyk** [comment]
@bolshoytoster thank you for the direction 🙇‍♂️ I found an error in the layersConfiguration => not a problem with the engine, but my config mistake.
