### ISSUE TITLE
Dont mix specific layer traits with other layer traits

### ISSUE THREAD

**Issue by kingchenc** [HashLips/hashlips_art_engine#1123]
Hi, 

is there a way, how i can configure that some layer traits not get mixxed with other layer traits?

Short Example:

> Eyes: Red, Blue, Yellow
> Glasses: Black, White, Purple

I dont want Blue Eyes mixxed with Black Glasses, but i want mix the other two colours with Black.

> Red Eyes + Yellow Eyes with all Glasses
> Blue Eyes only with White and Purple Glasses

Is that possible in the config?

@bolshoytoster you know that?

**Comment by bolshoytoster** [comment]
@kingchenc you could do it if you had multiple `layersCnfigurations`, but it would be comlicated.

You could have a `layersConfiguration` with just blue eyes and another with the other eye ecolours  in.

**Comment by kingchenc** [comment]
> @kingchenc you could do it if you had multiple `layersCnfigurations`, but it would be comlicated.
> 
> You could have a `layersConfiguration` with just blue eyes and another with the other eye ecolours in.

@bolshoytoster any example for this sir? Thanks

**Comment by bolshoytoster** [comment]
@kingchenc
```js
const layersConfigurations = [
  {
    // This one has only Blue Eyes and no black glasses
  },
  {
    // This one has the other eye colours and all glasses
  },
]
```

**Comment by kingchenc** [comment]
> @kingchenc
> 
> ```js
> const layersConfigurations = [
>   {
>     // This one has only Blue Eyes and no black glasses
>   },
>   {
>     // This one has the other eye colours and all glasses
>   },
> ]
> ```

Love Ya, nice :)

**Comment by s-d-sd** [comment]
Is it possible to mix those different traits?
Intead of having one trait first, and the other second.

like

 not [1 | AA.....AA | 10 | BB....BB | 20]
 ↓
 but [1 | ABAAB........ABBBAA | 20]

```
const layersConfigurations = [
  {
    growEditionSizeTo: 10,
    // (A) This one has only Blue Eyes and no black glasses
  },
  {
    growEditionSizeTo: 20,
    // (B) This one has the other eye colours and all glasses
  },
]
```

**Comment by bolshoytoster** [comment]
@SDM-Shroom you can set `shuffleLayerConfigurations = true`, although due to bugs with that in this repo you should probably use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by s-d-sd** [comment]
@bolshoytoster

Thank you for the advice, the fork works great

One thing I'd like to ask is, is it possible to create collection which has mixing different traits with sequential number

not [1 | BDACCD........ABDCDA | 40]
↓
but [1 | ABAA.....BABA | 20 | DDCD....CDCD | 40] 

somehow by modifying the code below?

```
const layersConfigurations = [
  {
    growEditionSizeTo: 10,
   startEditionFrom: 1,
    // (A) 
  },
  {
    growEditionSizeTo: 10,
    // (B) 
  },
  {
    growEditionSizeTo: 10,
    // (C)
  {
    growEditionSizeTo: 10,
    // (D) 
  },
]
```

**Comment by bolshoytoster** [comment]
@SDM-Shroom no, but you could try generating the first bit with just A and B then generate with just C and D, my repo lets you continue a henerated collection.
