### ISSUE TITLE
npm install not working 

### ISSUE THREAD

**Issue by vvwvvvvvwvvvvvvw** [HashLips/hashlips_art_engine#1130]

**Comment by waxanator** [comment]
im using macbook pro m1

**Comment by bolshoytoster** [comment]
@waxanator this is because one of our dependencies doesn't support m1, please look  at [some existing issues](https://github.com/HashLips/hashlips_art_engine/issues?q=is%3Aissue+M1) for help.

**Comment by waxanator** [comment]
> @waxanator this is because one of our dependencies doesn't support m1, please look at [some existing issues](https://github.com/HashLips/hashlips_art_engine/issues?q=is%3Aissue+M1) for help.

brat ya smotrel, nichego ne nashel
