### ISSUE TITLE
Not able to update my metadata

### ISSUE THREAD

**Issue by SwagCord13** [HashLips/hashlips_art_engine#1187]
Hi not able to update my metadata i used "node utils/update_info.js" 
PS C:\Users\Sauld\Downloads\hashlips_art_engine-1.1.2_patch_v6> node utils/update_info.js
node:internal/fs/utils:345
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    **at Object.<anonymous> (C:\Users\Sauld\Downloads\hashlips_art_engine-1.1.2_patch_v6\utils\update_info.js:14:17)**
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}
PS C:\Users\Sauld\Downloads\hashlips_art_engine-1.1.2_patch_v6> 

I also tried "generate_metadata" which changed all my metadata attributes and trtait types to "NOT A HOT DOG". I than ran "npm run update_info" which properly updated the baseUri and the name and description but i had to regenerate my metadata to get rid of the hotdog problem. And now "npm run update_info" comes up with this---
PS C:\Users\Sauld\Downloads\hashlips_art_engine-1.1.2_patch_v6> npm run update_info

> hashlips_art_engine@1.1.1 update_info
> node utils/update_info.js

node:internal/fs/utils:345
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at Object.<anonymous> (C:\Users\Sauld\Downloads\hashlips_art_engine-1.1.2_patch_v6\utils\update_info.js:14:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}
PS C:\Users\Sauld\Downloads\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@SwagCord13 Have you messed with the `build/json` folder? If your code is unmodified then it's saying `build/json/_metadata.json` is a folder (should be a file).

Make sure your `utils/update_info.js` line 14 matches this exactly:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/utils/update_info.js#L14

**Comment by SwagCord13** [comment]
![gitbub issue](https://user-images.githubusercontent.com/105584009/169508475-ee45ab74-3f98-4d2d-921c-3a049a9cedcd.PNG)
![github issue 2](https://user-images.githubusercontent.com/105584009/169508477-fc0ef73f-083a-4726-9d20-ec47ebfc4adb.PNG)
![gitbub issue 3](https://user-images.githubusercontent.com/105584009/169508483-ff7dbaa5-f972-441c-8a7e-5f61a2546e94.PNG)


That is what my build folder looks like. I dont think i have the _metadata.json file. What is it?
My build folder goes 'build/json/metadata'
@bolshoytoster

**Comment by bolshoytoster** [comment]
@SwagCord13 if you regenerate does it get rid of that folder?

**Comment by SwagCord13** [comment]
> @SwagCord13 if you regenerate does it get rid of that folder?

when you say regenerate do you mean using the 'npm run generate_metadata" or do you just mean 'npm run generate'

**Comment by SwagCord13** [comment]
@bolshoytoster should my build folder be "build/json" and then all my metadata. Because atm my build folder is "build/json/metadata"and then the all the metadata. does that need to change?

**Comment by SwagCord13** [comment]
@bolshoytoster my "update_info" line 14 looks like this.
let rawdata = fs.readFileSync(`${basePath}/build/json/_metadata.json`);
Should i change the last bit to "build/json/metadata" because i dont have that _metadata.json thing.

**Comment by SwagCord13** [comment]
> @bolshoytoster my "update_info" line 14 looks like this. let rawdata = fs.readFileSync(`${basePath}/build/json/_metadata.json`); Should i change the last bit to "build/json/metadata" because i dont have that _metadata.json thing.
![IMG_5453](https://user-images.githubusercontent.com/105584009/169518198-f18142c0-ba83-45df-a136-0bc23e61e87d.jpg)

Tried that says its an illegal operation.

**Comment by SwagCord13** [comment]
@bolshoytoster FIXED problem all goodf
