### ISSUE TITLE
error ENOENT: no such file or directory -4058 scandir ENOENT

### ISSUE THREAD

**Issue by Tdawg007** [HashLips/hashlips_art_engine#1195]
when i try to generate nfts it gives me this error

errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\bsks2\\minter-dapp\\backend/layers/girl base/'

**Comment by Tdawg007** [comment]
some help would greatly appreciated

**Comment by bolshoytoster** [comment]
@Tdawg007 as I told you in [this comment](https://github.com/HashLips/hashlips_art_engine/issues/370#issuecomment-1132572718https://github.com/HashLips/hashlips_art_engine/issues/370#issuecomment-1132572718),:
> it can't find `backend/layers/girl base/`, make sure your folder names in `backend/layers` match the names in your `layersOrder`s.
>
> If that doesn't work, could you try opening an issue in the place you actually got the code from.

**Comment by Tdawg007** [comment]
all of the layer names match the layers order

**Comment by bolshoytoster** [comment]
@Tdawg007 can you paste your `layersOrder`(s) and the output of `ls {,backend/}layers` here please.

The `layersOrder` is case sensitive as well.

**Comment by Tdawg007** [comment]
{ name: "girl base" },
      { name: "girl Eyes" },
      { name: "girl eyebrows" },
      { name: "girl nose" },
      { name: "girl mouth" },
      { name: "girl clothes" },
      { name: "girl hair" },
      { name: "girl accessories" },


At line:1 char:5
+ 1s{,backend/}layers
+     ~
Missing expression after unary operator ','.
At line:1 char:5
+ 1s{,backend/}layers
+     ~~~~~~~~
Unexpected token 'backend/' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\bsks2\minter-dapp\backend> {,backend/}layers
At line:1 char:3
+ {,backend/}layers
+   ~
Missing expression after unary operator ','.

**Comment by bolshoytoster** [comment]
@Tdawg007 sorry, I thought you were on mac, could you paste the output of `Get-ChildItem layers` here please.

**Comment by Tdawg007** [comment]
Directory: C:\Users\bsks2\minter-dapp\backend\layers


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         5/20/2022   7:50 AM                PNG FILES

**Comment by bolshoytoster** [comment]
@Tdawg007 you need to move your layers out of the `PNG FILES/` folder and just into `layers/`

**Comment by Tdawg007** [comment]
it fixed it. thank a lot.

**Comment by ac6113** [comment]
I am getting same error. How move the layers out of png files? (p.s. I am not a coder, sorry if it is a very basic question)

**Comment by bolshoytoster** [comment]
@ac6113 can you paste your error(s) here please. Make sure your layer names match your `layersOrder`s exactly.
