### ISSUE TITLE
Please Help me :(

### ISSUE THREAD

**Issue by Th3HotDog** [HashLips/hashlips_art_engine#12]
This is the same issue I had before. I know why the error shows up (names are wrong) but I've double checked that. Installed everything, the code works fine until I put my layers in. Please, is there something i'm missing? I've included the path directory  folder so you can see. Ignore the "growEditionSizeTo" I was just messing around there. Please I've been stuck here for weeks with different versions. Edited to say I have added the weights to each file as well. IE Boots#45.png
![image](https://user-images.githubusercontent.com/90287413/133511470-fceeca10-5c0d-4a4d-9915-3bc4649bf5bc.png)

**Comment by Th3HotDog** [comment]
Fixed! All I had to do was save it!! Wow...

**Comment by AlfieDarko** [comment]
Happens to the best of us 😂. Feel free to close the issue!
