### ISSUE TITLE
Not generating specific number images

### ISSUE THREAD

**Issue by ChickGum** [HashLips/hashlips_art_engine#1205]
Hey guys, I am using hashlips for the first time to create NFT Collection.
I have created a shades layer folder, in that folder I have only 1 file and have set it’s number to for example: “Shades#10”. But, when I generated the 20 NFT’s for testing it created all 20 images with shades. And the same goes for all layers.

**Comment by bolshoytoster** [comment]
@ChickGum that's because you have one file, meaning it has 100% chance of showing up.

You could either add an empty image there with `#90` or you could have two objects in your `layersConfigurations`, one with shades and one without.

**Comment by ChickGum** [comment]
> @ChickGum that's because you have one file, meaning it has 100% chance of showing up.
> 
> You could either add an empty image there with `#90` or you could have two objects in your `layersConfigurations`, one with shades and one without.

**Comment by ChickGum** [comment]
Thank you @bolshoytoster for helping. It means a lot.
