### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by ShojoPixels** [HashLips/hashlips_art_engine#122]
https://www.youtube.com/watch?v=3jizwk6_m1s
I am following this tutorial, but on minute 18:45 when I try to update the baseuri by running node utils/updateBaseUri.js I get this error message:

PS C:\Users\17864\Desktop\hashlips_art_engine-1.0.7_update> node utils/updateBase        aseUri.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\17864\Desktop\hashlips_art_engine-1.0.7_update\utils\updateBaseUri.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
PS C:\Users\17864\Desktop\hashlips_art_engine-1.0.7_update>

![Screenshot 2021-10-17 010119](https://user-images.githubusercontent.com/92660805/137612364-16c21abd-3d6d-4237-b838-4cd8209d6c75.png)

**Comment by WesleyAcker** [comment]
I'm getting this same error message.

**Comment by ShojoPixels** [comment]
Hi! I figured it out. For some reason this version was missing some folders. Download V 1.0.4 and go to the utils folder, there you will see rarityData and updateBaseUri. Copy those onto the utils folder of V.1.0.7 and it should work. <3

**Comment by ShojoPixels** [comment]
Let me know if this woked for anyone
