### ISSUE TITLE
Nfts pics issue  URGENT

### ISSUE THREAD

**Issue by tahaimran** [HashLips/hashlips_art_engine#1245]
![8201](https://user-images.githubusercontent.com/59136478/173181000-a7b1562e-6f7e-443e-ad4b-67e1e7fd24a5.png)
Hi please let me know as soon as possible how to fix it

**Comment by memolguin** [comment]
I have the same problem, any solution yet?

**Comment by memolguin** [comment]
I solved it, I have a file in Photoshop where I open all the images before generating the random images to see if there is a problem with the overlapping or something like that so I upload all the images to Photoshop and then exported all the layer to file and those images were the ones I put on the folders of the visual studio file. and Voila!

**Comment by tahaimran** [comment]
Yup, you have  to convert 64 bit files to smaller
