### ISSUE TITLE
Create an option to add Custom Attributes

### ISSUE THREAD

**Issue by sd-dbs** [HashLips/hashlips_art_engine#125]
Hi, is there any way to edit your code to add some custom attributes, like...

- Numeric Traits
- Date Traits

For example, here are the attributes of one of the [OpenSea creatures](https://testnets.opensea.io/assets/0x7dca125b1e805dc88814aed7ccc810f677d3e1db/25). Also, see below for more...

### Numeric Traits (Rankings, Stats, Boosts)

> **CODE**

...
{
"attributes": [
    {
      "trait_type": "Base", 
      "value": "Starfish"
    }, 
    {
      "trait_type": "Eyes", 
      "value": "Big"
    }, 
    {
      "trait_type": "Mouth", 
      "value": "Surprised"
    }, 
    {
      "trait_type": "Level", 
      "value": 5
    }, 
    {
      "trait_type": "Stamina", 
      "value": 1.4
    }, 
    {
      "trait_type": "Personality", 
      "value": "Sad"
    }, 
    {
      "display_type": "boost_number", 
      "trait_type": "Aqua Power", 
      "value": 40
    }, 
    {
      "display_type": "boost_percentage", 
      "trait_type": "Stamina Increase", 
      "value": 10
    }, 
    {
      "display_type": "number", 
      "trait_type": "Generation", 
      "value": 2
    }
  ]
}

> **PREVIEW**

![3df0848-attributes](https://user-images.githubusercontent.com/91214333/137676146-cabe915a-6110-4254-90ac-57827eea5f44.png)

### Date Traits

> **CODE**

{
      "display_type": "date", 
      "trait_type": "birthday", 
      "value": 1546360800
}

> **PREVIEW**

<img width="391" alt="89bee0f-Screen_Shot_2019-10-18_at_7 51 58_PM" src="https://user-images.githubusercontent.com/91214333/137681620-f865c388-58e8-466e-9738-6a10e4a74a1d.png">

I really appreciate any support with this!

**Comment by designworkplan** [comment]
Check https://github.com/HashLips/hashlips_art_engine/pull/123/commits/b6c12a51a911027a1fd9ebebb9c1c7d7433bc9ea
