### ISSUE TITLE
node index.js

### ISSUE THREAD

**Issue by SebbeDuck** [HashLips/hashlips_art_engine#1261]
SyntaxError: Unexpected token ']'
←[90m    at wrapSafe (internal/modules/cjs/loader.js:988:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1036:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:937:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:778:12)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:961:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (C:\Users\sebbe\hashlips\src\main.js:24:5)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1072:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m

**Comment by bolshoytoster** [comment]
@SebbeDuck can you paste the *full* error please, it's probably an issue with your `src/config.js`.

**Comment by SebbeDuck** [comment]
> 
This is the full error.

C:\Users\sebbe\hashlips>node index.js
C:\Users\sebbe\hashlips\src\config.js:765
];
^

SyntaxError: Unexpected token ']'
←[90m    at wrapSafe (internal/modules/cjs/loader.js:988:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1036:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:937:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:778:12)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:961:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (C:\Users\sebbe\hashlips\src\main.js:24:5)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1072:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m

C:\Users\sebbe\hashlips>

**Comment by bolshoytoster** [comment]
@SebbeDuck can you paste lines 763-767 of your `src\config.js` here please.

**Comment by SebbeDuck** [comment]
> @SebbeDuck can you paste lines 763-767 of your `src\config.js` here please.

    },
    {
];

const shuffleLayerConfigurations = false;

**Comment by bolshoytoster** [comment]
@SebbeDuck could you try removing the `{` ~line 764

**Comment by SebbeDuck** [comment]
> @SebbeDuck could you try removing the `{` ~line 764

That was the issue, it works perfectly now, thanks! :)
