### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ghost** [HashLips/hashlips_art_engine#1264]
I'm using Windows 10 with below installation. But hit error when execute npm install. Appreciate if I would be able to get solution to fixt it so that I can continue to move on as this is just the beginning  😥

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> node -v
v14.18.2
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> npm -v
6.14.15
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> npm install

> canvas@2.8.0 install C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas 
> node-pre-gyp install --fallback-to-build

The system cannot find the path specified.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\@mapbox\node-pre-gyp\bin\node-pre-gyp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN hashlips_art_engine@1.1.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pauline&Rueben\AppData\Roaming\npm-cache\_logs\2022-06-19T11_03_27_282Z-debug.log

**Comment by bolshoytoster** [comment]
@wylim6783 
> I don't know how run as an admin powershell

https://www.howtogeek.com/742916/how-to-open-windows-powershell-as-an-admin-in-windows-10/

**Comment by ghost** [comment]
I try to attach printscreen after I hit run as administrator in PowerShell but seems I can't find the attach file icon. But result shown as below:

PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> New-Item -Path C:\Users@mapbox -ItemType SymbolicLink -Value C:\Users\Pauline&Rueben\AppData\Roaming\npm\node_modules
At line:1 char:78
+ ... \Users@mapbox -ItemType SymbolicLink -Value C:\Users\Pauline&Rueben\A ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double 
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
 
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@wylim6783 try running `New-Item -Path C:\Users@mapbox -ItemType SymbolicLink -Value "C:\Users\Pauline&Rueben\AppData\Roaming\npm\node_modules"` then.

**Comment by ghost** [comment]
Before I run as you adviced, I head over to PowerShell run as administrator again...it's still the same

PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> New-Item -Path C:\Users@mapbox -ItemType SymbolicLink -Value "C:\Users\Pauline&Rueben\AppData\Roaming\npm\node_modules"
New-Item : Administrator privilege required for this operation.
At line:1 char:1
+ New-Item -Path C:\Users@mapbox -ItemType SymbolicLink -Value "C:\User ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\Paulin...pm\node_modules:String) [New-Item], UnauthorizedAcces  
   sException
    + FullyQualifiedErrorId : NewItemSymbolicLinkElevationRequired,Microsoft.PowerShell.Commands.NewItemCommand
 
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@wylim6783 that's not an admin powershell.

**Comment by ghost** [comment]
I thought I followed the link you shared just now should activate as administrator.

**Comment by ghost** [comment]
Is it correct that I should change VS code compatibility to "run as administrator" at the properties? I tried to change it & result shown as below: 

PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> New-Item -Path C:\Users@mapbox -ItemType SymbolicLink -Value "C:\Users\Pauline&Rueben\AppData\Roaming\npm\node_modules"
New-Item : NewItemIOError
At line:1 char:1
+ New-Item -Path C:\Users@mapbox -ItemType SymbolicLink -Value "C:\User ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\Users@mapbox:String) [New-Item], IOException
    + FullyQualifiedErrorId : NewItemIOError,Microsoft.PowerShell.Commands.NewItemCommand     
 
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@wylim6783 can you try running `npm install` again now.

**Comment by ghost** [comment]
Error still there...

 Session contents restored from 6/19/2022 at 9:21:03 PM 

Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> npm install

> canvas@2.8.0 install C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas 
> node-pre-gyp install --fallback-to-build

The system cannot find the path specified.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\@mapbox\node-pre-gyp\bin\node-pre-gyp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN hashlips_art_engine@1.1.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pauline&Rueben\AppData\Roaming\npm-cache\_logs\2022-06-19T13_33_16_139Z-debug.log
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6>

**Comment by ghost** [comment]
Could you please advise if any solution? Appreciate that

**Comment by bolshoytoster** [comment]
@wylim6783 I don't know, it looks more like an issue either node, npm or node-pre-gyp; you should try openning an issue in [node-pre-gyp](https://github.com/mapbox/node-pre-gyp/issues/new)'s repo.

**Comment by ghost** [comment]
I think below yarn install triggered me that I have to enable PowerShell execution policy. After changed it, seem everything realized... 😀. Hopefully by changing the policy won't risk my pc. Anyway for sharing the outcome.

PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> yarn install
this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ yarn install
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> yarn install
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warn[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 53.18s.
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> npm run generate

> hashlips_art_engine@1.1.1 generate C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6       
> node index.js

Created edition: 1, with DNA: 59ed9aa1f8dba18e866485aeda070367f75a8c6f
Created edition: 2, with DNA: 286d53c27fa6498baf7003aa85a5aab0f72e0264
Created edition: 3, with DNA: f6decd3758fec287ebba5cda110e0f50afacd3d1
Created edition: 4, with DNA: 33f9c0add9a15304d43d16af3804204b34422565
Created edition: 5, with DNA: 588587f4e8bb6138ec2e1533c9748902583d24b8
