### ISSUE TITLE
Output SVG file

### ISSUE THREAD

**Issue by Azmuch** [HashLips/hashlips_art_engine#127]
How can I modify this code to work with Illustrator or to output SVG Files

**Comment by austincondiff** [comment]
Any movement here? I am also interested in generating SVG-based NFTs? Are there any pros/cons to an SVG-based NFT as opposed to a PNG (other than the obvious vector vs raster)? I am noticing SVG's aren't renderering properly in the OpenSea app and in the Coinbase Wallet app so I question whether or not I should even consider this.

**Comment by moranil** [comment]
Created pull request
https://github.com/HashLips/hashlips_art_engine/pull/186

**Comment by moranil** [comment]
Here is the link to the svg branch from ny fork

https://github.com/moranil/hashlips_art_engine/tree/svg_art_feature

**Comment by illushane** [comment]
> Here is the link to the svg branch from ny fork
> 
> https://github.com/moranil/hashlips_art_engine/tree/svg_art_feature

This is amazing! Thanks for your awesome code. However, I have a question. Can I generate both format at the same time?

**Comment by moranil** [comment]
That is not possible with the current code.

However, should not be hard to implement. I can make those changes easily to this code. 

The input layer format should be svg (svg can be rendered in canvas, but png files can't be converted to svg format).

**Comment by illushane** [comment]
> That is not possible with the current code.
> 
> However, should not be hard to implement. I can make those changes easily to this code.
> 
> The input layer format should be svg (svg can be rendered in canvas, but png files can't be converted to svg format).

Thanks. SVG export is saving lots of time

**Comment by slavakurilyak** [comment]
@moranil are you able to sync your code with the latest changes on HashLips:main?
