### ISSUE TITLE
Any way to allow hashlips art engine to generate without DNA check?

### ISSUE THREAD

**Issue by GangstaDev** [HashLips/hashlips_art_engine#1275]
Can I generate 1000 of the exact same image, 1 layer?? I did DNABypass true and it still spams DNA exists

**Comment by IceMasterT** [comment]
Im in the same boat, i second this question..

**Comment by bolshoytoster** [comment]
@IceMasterT you could try changing line 363 of `src/main.js`:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L362-L364

To:
```js
      if (true) {
```

**Comment by IceMasterT** [comment]
> ```js
>       if (true) {
> ```

you are the man! thanks brother!

**Comment by IceMasterT** [comment]
by chance do you know what to change to make the gifs files work? i just end up with blank files that are 0mb
