### ISSUE TITLE
Can't install npm help :c

### ISSUE THREAD

**Issue by Cetrolio** [HashLips/hashlips_art_engine#1277]
PS C:\Users\alleg\Downloads\hashlips_art_engine-1.0.6_update> npm install
npm WARN alleg No description
npm WARN alleg No repository field.
npm WARN alleg No license field.

audited 1 package in 0.438s
found 0 vulnerabilities

**Comment by bolshoytoster** [comment]
@Cetrolio that's not an error.

You may however be in the wrong folder, run `Get-ChildItem -Directory` to get the name, then run `cd ` + the name to change into it.

**Comment by Cetrolio** [comment]
@bolshoytoster i don't understand what name i should get

**Comment by bolshoytoster** [comment]
@Cetrolio it should be something like `hashlips_art_engine-1.0.6_update`.

**Comment by Cetrolio** [comment]
@bolshoytoster omg thank u a lot
