### ISSUE TITLE
node index.js, what's the problem?

### ISSUE THREAD

**Issue by Cetrolio** [HashLips/hashlips_art_engine#1278]
PS C:\Users\alleg\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update> node index.js
C:\Users\alleg\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\config.js
(node:14388) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at cleanDna (C:\Users\alleg\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\main.js:54:25)
    at C:\Users\alleg\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\main.js:151:22
    at Array.find (<anonymous>)
    at C:\Users\alleg\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\main.js:150:42
    at Array.map (<anonymous>)
    at constructLayerToDna (C:\Users\alleg\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\main.js:149:35)
    at startCreating (C:\Users\alleg\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\main.js:248:23)
    at C:\Users\alleg\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\index.js:13:3
    at Object.<anonymous> (C:\Users\alleg\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\index.js:14:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14388) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS C:\Users\alleg\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update>

**Comment by bolshoytoster** [comment]
@Cetrolio could you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine) instead.

**Comment by Cetrolio** [comment]
@bolshoytoster im sorry, i dont' understand what do you mean, also it's my first time using vs code so im very ignorant about this subject

**Comment by bolshoytoster** [comment]
@Cetrolio my fork is a more updated version of hashlips, could you follow the link and use that instead of hashlips.

**Comment by Cetrolio** [comment]
@bolshoytoster 
 layers/Eyeball doesn't exist, make sure your layers/ folder matches your src/config.js
idk why there's this error, my folders match with the ones in config.js

**Comment by bolshoytoster** [comment]
@Cetrolio make sure you save `src/config.js`.

**Comment by Cetrolio** [comment]
@bolshoytoster mate i love you it worked
