### ISSUE TITLE
How to write name and edition on image? 

### ISSUE THREAD

**Issue by c-drazen** [HashLips/hashlips_art_engine#1282]
Anybody know how to write text (  name: `${namePrefix} #${_edition}`, ) to picture? I want to write on nft image a name and edition, etc (name #1).

    
╭――――――╮
│                  
│                  
│      name #01 
╰――――――╯

This is a function for draw only text to background without image. And doesn't have option for nft  name: `${namePrefix} #${_edition}`, (name #1).

👇

const text = {
  only: false,
  color: "#ffffff",
  size: 20,
  xGap: 40,
  yGap: 40,
  align: "left",
  baseline: "top",
  weight: "regular",
  family: "Courier",
  spacer: " => ",
};

**Comment by 3filo** [comment]
were you able to solve the problem? 
I have the same problem.
Please Help

**Comment by bolshoytoster** [comment]
@GianlucaTrifilo in `src/main.js`, ~line 397:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L397-L398

You could add
```js
          addText(
            `${namePrefix} #${abstractedIndexes[0]}`,
            text.xGap,
            text.yGap,
            text.size
          )
```

**Comment by 3filo** [comment]
Amazing! You saved me! Thanks a lot!

**Comment by 3filo** [comment]
Last question:
But if i need the other Metadata on it? 
Like:
const text = {
  only: true,

Like this the Picture
![1](https://user-images.githubusercontent.com/11597732/204144827-5dbdd8b0-8464-4cae-9231-719f82722206.png)

**Comment by bolshoytoster** [comment]
@GianlucaTrifilo in `src/main.js`, you could change ~lines 204-217:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L204-L217

to
```js
  ctx.drawImage(
    _renderObject.loadedImage,
    0,
    0,
    format.width,
    format.height
  );

  addText(
    `${_renderObject.layer.name}${text.spacer}${_renderObject.layer.selectedElement.name}`, 
    text.xGap, 
    text.yGap * (_index + 1), 
    text.size 
  ) 
```

Although you may get layers blocking the text this way.

**Comment by 3filo** [comment]
Thank you. Works fine!
But is it not possible to set the text layer above all other layers?
![1](https://user-images.githubusercontent.com/11597732/204145912-39356eb4-e2de-4f29-bd2e-8454ff0a2fa8.png)

**Comment by bolshoytoster** [comment]
@GianlucaTrifilo you'll have to revert the changes at ~line 204-217, then add
```js
          renderObjectArray.forEach((renderObject, index) => {
            addText(
              `${renderObject.layer.name}${text.spacer}${renderObject.layer.selectedElement.name}`,
              text.xGap,
              text.yGap * (index + 1),
              text.size
            )
          });
```
to ~line 397 (just before or after the first edit).

**Comment by 3filo** [comment]
Thank you [bolshoytoster](https://github.com/bolshoytoster)! :)
