### ISSUE TITLE
A problem with "collection" when generating bulk

### ISSUE THREAD

**Issue by 0xLauge** [HashLips/hashlips_art_engine#1299]
I have a problem when generating my art, it doesn't add the collection data in each JSON file.

Is there an updated version or a way around this, thanks in advance!

**Comment by bolshoytoster** [comment]
@LaugeBirchLorup what do you mean by 'collection data'?

**Comment by 0xLauge** [comment]
@bolshoytoster There's a URI specifically for the collection to show the overall collection image and name

**Comment by bolshoytoster** [comment]
@LaugeBirchLorup you could try running `node utils/update_info.js`
