### ISSUE TITLE
Output file with total counts on traits

### ISSUE THREAD

**Issue by bkhoward2001** [HashLips/hashlips_art_engine#13]
Really could use some sort of single output file which gives counts as to each attribute based on the total generated. Example for a 10000 count collection:

450 have the red hat
3498 have the yellow hat
4643 have the green eyes
etc.
This should be a single file which can be brought into excel or other type of program for manipulation. This summary of counts would be easier to deal with for most rather than trying to parse all the json data. I was going to try to do this with the previous dna by parsing through individual digits; but with the latest changes to the dna that is not possible. There should an easier summary of trait totals available for output. Just an easy summary would prove beneficial.

**Comment by HashLips** [comment]
Yea I this is a cool idea, however, opensea and marketplaces automatically do this. If you simply want a counter then we can create a helper function that allows us to count afterward.
