### ISSUE TITLE
Problems with npm i

### ISSUE THREAD

**Issue by 948485100** [HashLips/hashlips_art_engine#1308]
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code 6
npm ERR! path F:\NFT\minter-dapp\backend\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
win32-unknown-x64.tar.gz
win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp info install unpacking Release/
npm ERR! node-pre-gyp info install unpacking Release/canvas.exp
npm ERR! node-pre-gyp info install unpacking Release/canvas.ilk
npm ERR! node-pre-gyp info install unpacking Release/canvas.lib
npm ERR! node-pre-gyp info install unpacking Release/canvas.node
npm ERR! node-pre-gyp info install unpacking Release/canvas.pdb
npm ERR! node-pre-gyp ERR! Completion callback never invoked!
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22000npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\NFT\\minter-dapp\\backend\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
npm ERR! node-pre-gyp ERR! cwd F:\NFT\minter-dapp\backend\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v16.15.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2022-07-07T17_49_44_836Z-debug-0.log
PS F:\NFT\minter-dapp\backend> -

**Comment by 948485100** [comment]
I deleted node_modules and reinstalled several times and this is the case。thanks for help

**Comment by bolshoytoster** [comment]
@948485100 according to [this comment](https://github.com/mapbox/node-pre-gyp/issues/367#issuecomment-392770854) this can be caused by antivirus.

**Comment by 948485100** [comment]
Thank you so much, hope you are all well
