### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by CristiCh** [HashLips/hashlips_art_engine#131]
After running the project v1.0.7 I get:

 code: 'MODULE_NOT_FOUND',
 requireStack: [
**'...hashlips_art_engine-1.0.7_update/src/main.js'
'...hashlips_art_engine-1.0.7_update/index.js'**
]

Can you please help?

**Comment by jcm302** [comment]
I also have this issue and need some help brain is melting from this as a noob. 

PS D:\NFT_MuscleBabies\Hashlips Engine> node index.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'D:\NFT_MuscleBabies\Hashlips Engine\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
