### ISSUE TITLE
Yarn install error

### ISSUE THREAD

**Issue by PamZ33** [HashLips/hashlips_art_engine#1314]
I'm getting this error with yarn install ( see below ). Can anyone help, please?
c:Users\AppData\Roaming\npm\yarn.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ yarn install
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by bolshoytoster** [comment]
@PamZ33 run `Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted`

**Comment by PamZ33** [comment]
@bolshoytoster Firstly, thanks. Tried but still got these error. Any help? Anyone?
C:\Users\Downloads\hashlips_art_engine-1.1.2_patch_v6> yarn install run Set-ExecutionPolicy
 -Scope CurrentUser -ExecutionPolicy Unrestricted
yarn : File C:\Users\Pamela Shea\AppData\Roaming\npm\yarn.ps1 cannot be loaded because running scripts
is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ yarn install run Set-ExecutionPolicy -Scope CurrentUser -ExecutionPol ...
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by PamZ33** [comment]
I tried "npm install -g yarn" and it worked, in case anyone is facing similar issues. Thanks again, @bolshoytoster.
