### ISSUE TITLE
Using the same layer multiple times

### ISSUE THREAD

**Issue by 0x471** [HashLips/hashlips_art_engine#1317]
Hi,

It is possible to use same layer multiple times while generating NFTs? For instance:

```
  growEditionSizeTo: 100,
    layersOrder: [
      { name: "Universe" },
      { name: "Pixel"},
      { name: "Pixel"},
    ],
```

Thanks in advance.

**Comment by bolshoytoster** [comment]
@0x471 yes.

**Comment by 0x471** [comment]
> @0x471 yes.

I tried but it doesn't generate as I said? It only uses one image from Pixel folder.

**Comment by bolshoytoster** [comment]
@0x471 have you saved `src/config.js`?
