### ISSUE TITLE
MODULE NOT FOUND when running node index.js

### ISSUE THREAD

**Issue by jcm302** [HashLips/hashlips_art_engine#132]
Hello noob here,

Installed yarn and reinstalled nodes, turned on script ability in powershell, installed desktop studio C++,  with no avail. Still getting this error with no output of NFT's. Any help much appreciated!

PS D:\NFT_MuscleBabies\Hashlips Engine> node index.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'D:\NFT_MuscleBabies\Hashlips Engine\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by fonzi69** [comment]
Did you figure it out? Im having the same problem
