### ISSUE TITLE
How to generate unique images with only 2 visible traits

### ISSUE THREAD

**Issue by danvisx** [HashLips/hashlips_art_engine#1320]
My current set-up:
- background: 20
- shape: 300
- 20 metadata layers as transparent pngs
- another 20 metadata layers as transparent pngs

so each shape can be generated 15 times, thus 15*300 are 4500 visual only combinations. But that is only if each background is set to trait weight: 5. 

my edition size is ~3000 and a lot of the backgrounds are repeating, visually due to the discrepancy in the layers numbers between background and shape.

is there a number of backgrounds I should add, a bigger edition I should attempt to generate and select out of that or something that can be added in the code?

**Comment by bolshoytoster** [comment]
@dvisan do you want the background/shape combinations to all be unique? If so you could add [`bypassDNA`](https://github.com/HashLips/hashlips_art_engine#usage-%E2%84%B9%EF%B8%8F) to the metadata layers.

**Comment by danvisx** [comment]
> @dvisan do you want the background/shape combinations to all be unique? If so you could add [`bypassDNA`](https://github.com/HashLips/hashlips_art_engine#usage-%E2%84%B9%EF%B8%8F) to the metadata layers.

Yes, unique. 

By my train of thought: if a shape has been already mixed with a background in a previous image, then the program should skip that combination. The issue here as stated above is that there are way less backgrounds than shapes. I still think there would be a need for more backgrounds in every scenario.

By my understanding, the DNA verification prevented duplicates, thus I didn't understood from the Readme how bypassing it would actually work for my use case. But adding it to the metadata layers makes a bit of sense, although I do not completely get it how that works.

**Comment by bolshoytoster** [comment]
@dvisan using `bypassDNA` like I said would make it so it only checks background/shape for uniqueness, so there wouldn't be any duplicates of them.

**Comment by danvisx** [comment]
ok, it makes 100% sense now. Thanks!!
