### ISSUE TITLE
some rarity not showing

### ISSUE THREAD

**Issue by sadun619** [HashLips/hashlips_art_engine#1333]
if use multiple layer configurations, some layers and values not showing in rarity. ( have 113 layer configuration, 65 layers, 876 traits in project.  only showing 6 layers and 105 traits in rarity. all layers and traits have deferent names.

**Comment by bolshoytoster** [comment]
@sadun619 it only shows the traits that get used in the collection, the unused ones won't be shown.

I also think won't work if you use `displayName`.

**Comment by sadun619** [comment]
> @sadun619 it only shows the traits that get used in the collection, the unused ones won't be shown.
> 
> I also think won't work if you use `displayName`.

got it. thank you. most layers have displayName.
