### ISSUE TITLE
_metadata.json missing from JSON folder

### ISSUE THREAD

**Issue by Versilli0n** [HashLips/hashlips_art_engine#1340]
_metadata.json file is not there in the json folder. I have all the json files for all the nfts but not the _metadata.json

**Comment by bolshoytoster** [comment]
@Versilli0n the generation was probably interrupted or ran into too many duplicates. You can run [my `utils/update_info.js` ](https://raw.githubusercontent.com/bolshoytoster/hashlips_art_engine/main/utils/update_info.js) to generate it.

**Comment by Versilli0n** [comment]
Thanks my g.
