### ISSUE TITLE
Error: EEXIST: file already exists

### ISSUE THREAD

**Issue by Sviche** [HashLips/hashlips_art_engine#1346]
![image](https://user-images.githubusercontent.com/83732455/180774895-59202948-7f4e-4fb9-a3a6-10318124eed8.png)
right it tells me that the file already exists, but the problem is that if you delete this file or two folders in it (images and json), the program stops working

**Comment by bolshoytoster** [comment]
@Sviche do you have permissions for `C:/Users/hashlips_art_engine-main/`? you probably made it as admin.

You can either give yourself permissions for it, run powershell as admin or just move the project into your own user's forder.

**Comment by Sviche** [comment]
> @Sviche do you have permissions for `C:/Users/hashlips_art_engine-main/`? you probably made it as admin.
> 
> You can either give yourself permissions for it, run powershell as admin or just move the project into your own user's forder.

Thank you very much!
