### ISSUE TITLE
I've done `npm install` and  after running `node index.js` I am getting this error

### ISSUE THREAD

**Issue by 1NGODMOD** [HashLips/hashlips_art_engine#1349]
![image](https://user-images.githubusercontent.com/92852568/181716639-e1ca28cc-09f8-4b2b-bc2e-7e9d3401bee2.png)

**Comment by bolshoytoster** [comment]
@1NGODMOD try moving the project to somewhere like `C:/Users/Public/`.

**Comment by jeffoodchain** [comment]
@bolshoytoster Is it able to change the code to make the directory is to my D:\?

**Comment by bolshoytoster** [comment]
@FoodChain1028 yes, as long as there are no non-ASCII characters in your path.

**Comment by jeffoodchain** [comment]
@bolshoytoster you mean the path to all file? Well I'll try it.

**Comment by 1NGODMOD** [comment]
> @1NGODMOD try moving the project to somewhere like `C:/Users/Public/`.

Thank you.That helped.
