### ISSUE TITLE
npm install issue 

### ISSUE THREAD

**Issue by Joglezbee1** [HashLips/hashlips_art_engine#1350]
i have been racking my brain trying to figure out why npm install is throwing these errors at me.. if someone could please help i would greatly appreciate it!!!

 npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code 1
npm ERR! path /home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas
npm ERR! command failed
npm ERR! command sh /tmp/install-20479bf7.sh
npm ERR! Failed to execute '/home/jacoboglesbee1/.config/nvm/versions/node/v18.7.0/bin/node /home/jacoboglesbee1/.config/nvm/versions/node/v18.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@18.7.0 | linux | x64
npm ERR! node-pre-gyp info check checked for "/home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@18.7.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.7.0 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.7.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/jacoboglesbee1/.config/nvm/versions/node/v18.7.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jacoboglesbee1/.config/nvm/versions/node/v18.7.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/jacoboglesbee1/.cache/node-gyp/18.7.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/jacoboglesbee1/.cache/node-gyp/18.7.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/jacoboglesbee1/.config/nvm/versions/node/v18.7.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/jacoboglesbee1/.cache/node-gyp/18.7.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: pkg-config: not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/jacoboglesbee1/.config/nvm/versions/node/v18.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.10.120-16442-g774fa9d77ddb
npm ERR! gyp ERR! command "/home/jacoboglesbee1/.config/nvm/versions/node/v18.7.0/bin/node" "/home/jacoboglesbee1/.config/nvm/versions/node/v18.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd /home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas
npm ERR! gyp ERR! node -v v18.7.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/home/jacoboglesbee1/.config/nvm/versions/node/v18.7.0/bin/node /home/jacoboglesbee1/.config/nvm/versions/node/v18.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/jacoboglesbee1/hashlips_art_engine/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Linux 5.10.120-16442-g774fa9d77ddb
npm ERR! node-pre-gyp ERR! command "/home/jacoboglesbee1/.config/nvm/versions/node/v18.7.0/bin/node" "/home/jacoboglesbee1/hashlips_art_engine/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/jacoboglesbee1/hashlips_art_engine/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v18.7.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jacoboglesbee1/.npm/_logs/2022-07-30T01_04_35_999Z-debug-0.log

**Comment by Joglezbee1** [comment]
this is what i get when i rune node index.js 


 Require stack:
- /home/jacoboglesbee1/hashlips_art_engine/src/main.js
- /home/jacoboglesbee1/hashlips_art_engine/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/jacoboglesbee1/hashlips_art_engine/src/main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jacoboglesbee1/hashlips_art_engine/src/main.js',
    '/home/jacoboglesbee1/hashlips_art_engine/index.js'
  ]
}
**

**Comment by Joglezbee1** [comment]
do i need to install npm globally instead??
-g?

**Comment by Joglezbee1** [comment]
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

**Comment by simonlee9449** [comment]
I guess you are having same issue with me. 
this command fixed issue for me. hope this works.
```
brew install pkg-config cairo pango libpng jpeg giflib librsvg 
```

ref: https://flaviocopes.com/fix-node-canvas-error-pre-gyp-macos/

**Comment by rainbowhat** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> ref: [https://flaviocopes.com/fix-node-canvas-error-pre-gyp-m](https://flaviocopes.com/fix-node-canvas-error-pre-gyp-macos/)

Error: Cannot find module '../build/Release/canvas.node' - Still getting this

**Comment by JohnDotOwl** [comment]
> I guess you are having same issue with me. this command fixed issue for me. hope this works.
> 
> ```
> brew install pkg-config cairo pango libpng jpeg giflib librsvg 
> ```
> 
> ref: https://flaviocopes.com/fix-node-canvas-error-pre-gyp-macos/

rror: Cannot find module '../build/Release/canvas.node' - Still getting this

**Comment by JohnDotOwl** [comment]
> > I guess you are having same issue with me. this command fixed issue for me. hope this works.
> > ```
> > brew install pkg-config cairo pango libpng jpeg giflib librsvg 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ref: https://flaviocopes.com/fix-node-canvas-error-pre-gyp-macos/
> 
> error: Cannot find module '../build/Release/canvas.node' - Still getting this

Solution : delete the node_modules/ folder then run npm install again.

**Comment by bolshoytoster** [comment]
@Joglezbee1 this is because one of our dependencies doesn't support m1, please look  at [some existing issues](https://github.com/HashLips/hashlips_art_engine/issues?q=is%3Aissue+M1) for help.

**Comment by Joglezbee1** [comment]
i tried what was mentioned above but still not working im using chrome os, and i have used this setup before but now it is not working...

**Comment by Joglezbee1** [comment]
is there a moderator of this software that can help me please??

**Comment by Joglezbee1** [comment]
> > > I guess you are having same issue with me. this command fixed issue for me. hope this works.
> > > ```
> > > brew install pkg-config cairo pango libpng jpeg giflib librsvg 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ref: https://flaviocopes.com/fix-node-canvas-error-pre-gyp-macos/
> > 
> > 
> > error: Cannot find module '../build/Release/canvas.node' - Still getting this
> 
> Solution : delete the node_modules/ folder then run npm install again.

install: target 'librsvg' is not a directory

**Comment by bolshoytoster** [comment]
@Joglezbee1 can you paste the full error here please.

**Comment by Joglezbee1** [comment]
> @Joglezbee1 can you paste the full error here please.

i just finshed trying to reinstall everything compleltey and im still getting an error a diffreent one now, im using the update versions of node js and npm.. i hope this helps 
jacoboglesbee1@penguin:~/hashlips_art_engine$ node index.js
/home/jacoboglesbee1/hashlips_art_engine/src/main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/jacoboglesbee1/hashlips_art_engine/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
jacoboglesbee1@penguin:~/hashlips_art_engine$ npm run build

> hashlips_art_engine@1.1.1 build
> node index.js

/home/jacoboglesbee1/hashlips_art_engine/src/main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/jacoboglesbee1/hashlips_art_engine/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /home/jacoboglesbee1/hashlips_art_engine
npm ERR! command failed
npm ERR! command sh -c node index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jacoboglesbee1/.npm/_logs/2022-08-02T04_23_48_096Z-debug.log

**Comment by bolshoytoster** [comment]
@Joglezbee1 either update node.js or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by Joglezbee1** [comment]
node js says it is updated and use what in your fork the repository? im just at a loss why this is not working for me anymore does nobody know???

**Comment by bolshoytoster** [comment]
@Joglezbee1 you need to download a more recent version of node.

**Comment by Joglezbee1** [comment]
> @Joglezbee1 you need to download a more recent version of node.

jacoboglesbee1@penguin:~/hashlips_art_engine$ node -v
v16.16.0
jacoboglesbee1@penguin:~/hashlips_art_engine$ npm -v
8.11.0
jacoboglesbee1@penguin:~/hashlips_art_engine$ node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/home/jacoboglesbee1/hashlips_art_engine/node_modules/sha1'
Require stack:
- /home/jacoboglesbee1/hashlips_art_engine/src/main.js
- /home/jacoboglesbee1/hashlips_art_engine/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/jacoboglesbee1/hashlips_art_engine/src/main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jacoboglesbee1/hashlips_art_engine/src/main.js',
    '/home/jacoboglesbee1/hashlips_art_engine/index.js'
  ]
}
jacoboglesbee1@penguin:~/hashlips_art_engine$

**Comment by Joglezbee1** [comment]
@bolshoytoster node and npm are update now as you see above and this is the error i recieve now..., module not found any ideas?

**Comment by bolshoytoster** [comment]
@Joglezbee1 you need to run `npm install`.

**Comment by Joglezbee1** [comment]
awesome thank you so much for all the help @bolshoytoster truly!!!
