### ISSUE TITLE
Number of minted nft

### ISSUE THREAD

**Issue by Sviche** [HashLips/hashlips_art_engine#1351]
Hello, why did I change the parameter of the number of NFT that will be minted, but I still get 5 NFT as a result
![Сн89имо9789к](https://user-images.githubusercontent.com/83732455/181920387-83ce856c-175c-4383-8f65-f860a7e80c0d.JPG)

**Comment by bolshoytoster** [comment]
@Sviche save `src/config.js`.

**Comment by Sviche** [comment]
> @Sviche save `src/config.js`.

Thank you, You are the best!!
