### ISSUE TITLE
variable `solanaMetadata`

### ISSUE THREAD

**Issue by 0xinit** [HashLips/hashlips_art_engine#1358]
So, I have been playing around the generator for a while and i got a question about `solanaMetadata`. Do we need to change the variable to ethMetadata if we use eth chain? I dont necessarily see the difference, but still need in puts on it.

Thanks!

**Comment by bolshoytoster** [comment]
@0xinit that's just metadata that's only needed/included in solana collections. If you want to add extra metadata in an eth collection you can instead use `extraMetadata`.

**Comment by 0xinit** [comment]
No, my question is that can I define it like ethMetadata for my collection instead of `soloanaMetadata` or `extraMetadata`?

**Comment by bolshoytoster** [comment]
@0xinit no.

**Comment by 0xinit** [comment]
ohh okay! Thanks!
