### ISSUE TITLE
layerObj.options?.["displayName"] != undefined

### ISSUE THREAD

**Issue by aycanozarpaci** [HashLips/hashlips_art_engine#137]
layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
←[90m    at Module._compile (internal/modules/cjs/loader.js:720:23)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:643:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:683:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:16:16)←[39m
    at Object.<anonymous> (C:\laragon\www\hashlips_art_engine\index.js:6:39)
←[90m    at Module._compile (internal/modules/cjs/loader.js:776:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:643:32)←[39m

giving this error after "node index.js"

**Comment by screwgoth** [comment]
I got the same error too.

**Comment by eyecoins** [comment]
Hi every body i am on windows 7 so i can't update node so i fixed by make edit to main.js code 
the function layersSetup() use a new syntax feature( ?. ) and that not able on  early version at node so i edit like that

``const layersSetup = (layersOrder) => {
 
  const layers = layersOrder.map((layerObj, index) => ({
    id: index,
    elements: getElements(`${layersDir}/${layerObj.name}/`),
    name:
      layerObj.options && layerObj.options["displayName"] != undefined
        ? layerObj.options["displayName"]
        : layerObj.name,
    blend:
    layerObj.options && layerObj.options["blend"] != undefined
        ? layerObj.options["blend"]
        : "source-over",
    opacity:
    layerObj.options && layerObj.options["opacity"] != undefined
        ? layerObj.options["opacity"]
        : 1,
    bypassDNA:
    layerObj.options && layerObj.options["bypassDNA"] !== undefined
        ? layerObj.options["bypassDNA"]
        : false,
  }));
  return layers;
};
