### ISSUE TITLE
How to set rarity of layers

### ISSUE THREAD

**Issue by stackcraft55** [HashLips/hashlips_art_engine#1375]
I am going to set the rarity of layers
I have several layers. but I want to some variations don't have specific layers

0	Background	100%
1	Skin Tone	100%
2	Eyes	100%
3	Hair Style	100%
4	Shoes	100%
5	T-Shirt	100%
6	Gloves	50%
7	Trousers	100%
8	Belt	80%
9	Top	70%
10	Weapon	80%
11	Briefcase	80%
12	Glasses	40%
13	Smoke	30%
14	Hat	60%

It is my plan
How should I make the config.js file?
Please help me
Thank you

**Comment by bolshoytoster** [comment]
@cryptoguy55 you could have blank pictures in the layer folders with the rarity of not showing, e.g. 20% for belt.

**Comment by stackcraft55** [comment]
Hi. @bolshoytoster 
Thank you for answer
if I name the blank picture as "None#30", it will be displayed on metadata
How can I remove none attribute on metadata?

**Comment by bolshoytoster** [comment]
@cryptoguy55 change `src/main.js` ~line 174-180 from:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L174-L180

to
```js
const addAttributes = (_element) => {
  if (selectedElement.name != "None") {
    let selectedElement = _element.layer.selectedElement;
    attributesList.push({
      trait_type: _element.layer.name,
      value: selectedElement.name,
    });
  }
 };
```

**Comment by stackcraft55** [comment]
Thank you.
Could you let me know your telegram id?

**Comment by bolshoytoster** [comment]
@cryptoguy55 I don't use telegram.

**Comment by stackcraft55** [comment]
discord or skype?

**Comment by bolshoytoster** [comment]
@cryptoguy55 bolshoy#0648 on discord

**Comment by berkantsoytas** [comment]
I wish you would continue the communication from here. Can someone help me with this matter?

**Comment by bolshoytoster** [comment]
@berkantsoytas I don't think there was much communication after this, have you tried using empty images?

**Comment by berkantsoytas** [comment]
> @berkantsoytas I don't think there was much communication after this, have you tried using empty images?

No, I haven't tried it. Should I try it?

**Comment by bolshoytoster** [comment]
@berkantsoytas you should probably try it.
