### ISSUE TITLE
Output Images Low Quality

### ISSUE THREAD

**Issue by Brandon1419** [HashLips/hashlips_art_engine#138]
Hey everyone. My output images quality is rather low. You can really notice it... The assets I uploaded are all original high-quality png files. Why is this happening? Am I missing a setting?

**Comment by berkenatascii** [comment]
yes, i have the same problem. Files with the .png extension are processed with ants. I can't find where I went wrong.

**Comment by DipoAreoye** [comment]
any solution for this?

**Comment by jmclain24** [comment]
Having the same issue. Is there any solution for this?
