### ISSUE TITLE
Pause ?

### ISSUE THREAD

**Issue by urospeed** [HashLips/hashlips_art_engine#14]
First of all, thank you for your awesome work (Codes + Vidéos). Internet needs more person like you!

I would like to know if there is an option to pause and restart later this generator? (Keep the log in memory and if you don't delete the image , the code continue by itself)

Thank you!

**Comment by HashLips** [comment]
The code will not be able to do that because we want to create the art with almost the same timestamp, You can always adjust the code yourself and then add a pause function.
