### ISSUE TITLE
node index.js problem 

### ISSUE THREAD

**Issue by hyperionkear** [HashLips/hashlips_art_engine#140]
![config js - hashlips_art_engine-main - Visual Studio Code 21 10 2021 00_27_15](https://user-images.githubusercontent.com/92893115/138176155-6d2e3d4f-0b2f-45f6-86dd-38a09476700c.png)

**Comment by djcatcannon** [comment]
Try saving, then run it again
it worked after for me

**Comment by hyperionkear** [comment]
I've tried but it didnt work for me
