### ISSUE TITLE
How to stop auto reset of the editionCount?

### ISSUE THREAD

**Issue by Thebks** [HashLips/hashlips_art_engine#1402]
I have 10 different designs and of each, I want to make 1000 NFTS but when I try to create another 1000 its just deletes the previous collection and makes a new one. I  change the code a little bit just so it doesn't delete the 'build' folder and add files to it but then the editionCount always starts from 1. I can't print all 10,000 at once I have to print 1000/design. 

The editionCount should start from (1-1000) for the 1st design and then for the 2nd design it should be (1001-2000) and so on. How can I do that?

**Comment by Thebks** [comment]
I hope I'm being clear

**Comment by bolshoytoster** [comment]
@Thebks [my fork](https://github.com/bolshoytoster/hashlips_art_engine) does this, you set `growEditionSize` to the next size (i.e. `2000` for the second one).

> I can't print all 10,000 at once I have to print 1000/design.

Couldn't you have each design as a seperate `layersConfiguration`, then you could also shuffle the designs.

**Comment by Thebks** [comment]
@bolshoytoster  I could do that but that would still mix up the layers since they have the same folder names. I will check your fork out and will let you know if it works for me. Thank You

**Comment by Thebks** [comment]
@bolshoytoster Wow You just solved my problem just like that and saved me some time. You Program clearly solves the `editionCount` problem that I had. I just have to have to move the 1st batch to a different folder to make another batch otherwise it says `Edition exists!`. That is not a problem I can do that.
Thank You so much.

**Comment by bolshoytoster** [comment]
@Thebks the `Edition exists!` is just info, you could instead set `startEditionFrom` (the same way you set `growEditionSize`) to the starting number of the next batch to avoid the messages.

**Comment by Thebks** [comment]
Alright, I'll try that.
