### ISSUE TITLE
NFT Minting Catch Error

### ISSUE THREAD

**Issue by DavidPFMedia** [HashLips/hashlips_art_engine#1417]
If everyone has the same problem as I am (not exact, but similar), please let me know how to resolve this.  This is my first time coding this to try to mint my NFTs that I have created, and so far it's been rather difficult. Half the time I don't know what I'm doing without tutorials that were as far as March of this year when rinkby's was a thing. This is the error I came across trying to mint my NFTs.

```
PS C:\Users\aarons\Desktop\create-10k-nft-collection-2.0.1> npm run mint

> 10k-collection-video@2.0.1 mint
> node utils/nftport/mint %npm_config_start% %npm_config_end%

OK to mint ALL? (y/n): n
Exiting...
PS C:\Users\aarons\Desktop\create-10k-nft-collection-2.0.1> npm run mint --start=1 --end=100

> 10k-collection-video@2.0.1 mint
> node utils/nftport/mint %npm_config_start% %npm_config_end%

OK to mint 1-100? (y/n): y
CATCH ERROR: ERROR STATUS: 422
Retrying
CATCH ERROR: ERROR STATUS: 429
Retrying
CATCH ERROR: ERROR STATUS: 429
Retrying
CATCH ERROR: ERROR STATUS: 429
Retrying
CATCH ERROR: ERROR STATUS: 422
Retrying
CATCH ERROR: ERROR STATUS: 429
Retrying
CATCH ERROR: ERROR STATUS: 429
Retrying
CATCH ERROR: ERROR STATUS: 429
Retrying
CATCH ERROR: ERROR STATUS: 422
Retrying
CATCH ERROR: ERROR STATUS: 429
Retrying
CATCH ERROR: ERROR STATUS: 429
Retrying
CATCH ERROR: ERROR STATUS: 429
Retrying
CATCH ERROR: ERROR STATUS: 422
Retrying
CATCH ERROR: ERROR STATUS: 429
```

**Comment by bolshoytoster** [comment]
@DavidPFMedia http error 422 means 'Unprocessable Entity'. http error 429 means 'Too Many Requests'.

You should open an issue on [codeSTACKr's repo](https://github.com/codeSTACKr/create-10k-nft-collection/issues) because that's where you got the code from.

**Comment by DavidPFMedia** [comment]
> 

Thanks a lot! I have opened the issue there just now. Hopefully, I could get some answers and helpful suggestions there!

**Comment by DavidPFMedia** [comment]
Thanks for the help, but I'll have to start over.

**Comment by DavidPFMedia** [comment]
Thanks for the help, but I'll have to start over.
