### ISSUE TITLE
Art Engine stops at 3500 want to do a 10K NFT series

### ISSUE THREAD

**Issue by MDMWINS** [HashLips/hashlips_art_engine#1425]
This has happened 2 times now, have a fast PC - what is the issue. please help!

**Comment by bolshoytoster** [comment]
@MDMWINS can you paste the last few lines of the output here please, and make sure you save `src/config.js`.

**Comment by MDMWINS** [comment]
Hiya
PC Specs are these
pc Processor: Intel® Core™ i7-6700 CPU @ 3.40GHz 3.40 GHz Installeret RAM: 32,0 GB Systemtype: 64-bit operativsystem, x64-baseret processor Windows 10 Home
Cant seem to find the config.js file?
[Öppna fotot]

Från: bolshoytoster ***@***.***>
Skickat: den 26 oktober 2022 18:13
Till: HashLips/hashlips_art_engine ***@***.***>
Kopia: MDMWINS ***@***.***>; Mention ***@***.***>
Ämne: Re: [HashLips/hashlips_art_engine] Art Engine stops at 3500 want to do a 10K NFT series (Issue #1425)


@MDMWINS<https://github.com/MDMWINS> can you paste the last few lines of the output here please, and make sure you save src/config.js.

**Comment by bolshoytoster** [comment]
@MDMWINS
> Cant seem to find the config.js file?

It's the one with your `layersConfigurations` in.

Can you please paste the last few lines of output from generating here.

**Comment by MDMWINS** [comment]
ah see artist has used this one https://github.com/HashLips/hashlips_art_engine_ps_script/issues will raise issue there instead

**Comment by MDMWINS** [comment]
moved to https://github.com/HashLips/hashlips_art_engine_ps_script/issues/5
