### ISSUE TITLE
Can I exclude Background Layer when counting on rarity?

### ISSUE THREAD

**Issue by Zundra1** [HashLips/hashlips_art_engine#1431]
Once I started generating I noticed that I have same picture but only different backgrounds..
Is there a way to Exclude background or make code ignore background layer so I could make unique images without repeating same elements on different backgrounds?

**Comment by bolshoytoster** [comment]
@Zundra1 you can use `options.bypassDNA` [as shown in the README](https://github.com/HashLips/hashlips_art_engine#usage-%E2%84%B9%EF%B8%8F).

**Comment by Zundra1** [comment]
@bolshoytoster what should I change inside that, sorry if its stupid question but im new to this coding thing i dont know very well how to do it xD

 bypassDNA:
      layerObj.options?.["bypassDNA"] !== undefined
        ? layerObj.options?.["bypassDNA"]
        : true,

**Comment by bolshoytoster** [comment]
@Zundra1 have a look at the example:
```js
const layerConfigurations = [
  {
    growEditionSizeTo: 5,
    layersOrder: [
      { name: "Background" , {
        options: {
          bypassDNA: true;
        }
      }},
      { name: "Eyeball" },
      { name: "Eye color" },
      { name: "Iris" },
      { name: "Shine" },
      { name: "Bottom lid" },
      { name: "Top lid" },
    ],
  },
];
```

**Comment by Zundra1** [comment]
@bolshoytoster 
![Screenshot (2)](https://user-images.githubusercontent.com/117024997/198892963-c81e96ba-db7c-4fff-8ce5-83d292d07af2.png)
I'm doing something wrong probably.. I don't know what I did wrong

**Comment by bolshoytoster** [comment]
@Zundra1 sorry, my fault, change the `false` to `true` and remove the `;`.

**Comment by Zundra1** [comment]
@bolshoytoster I did i still have 8 problems, sorry for being boring about this

**Comment by Zundra1** [comment]
@bolshoytoster Is it maybe because I'm using older version 1.1.1 ?

**Comment by bolshoytoster** [comment]
@Zundra1 it won't be to do with version, remove the `{` at the endo of line 29 and remove one of the `}`s on line 33.

**Comment by Zundra1** [comment]
@bolshoytoster  It worked!! thank you so much bro <3
