### ISSUE TITLE
npm run generate issue 

### ISSUE THREAD

**Issue by Don-Chich** [HashLips/hashlips_art_engine#1435]
Hi guys, Just having an issue whenever i run npm run generate. Was working fine last week. Any help would be much appreciated. Thanks 

> hashlips_art_engine@1.1.1 generate D:\Generated assets\Generated assests\Furs Gen\hashlips_art_engine-1.1.2_patch_v6
> node index.js

(node:25048) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at removeQueryStrings (D:\Generated assets\Generated assests\Furs Gen\hashlips_art_engine-1.1.2_patch_v6\src\main.js:274:15)
    at cleanDna (D:\Generated assets\Generated assests\Furs Gen\hashlips_art_engine-1.1.2_patch_v6\src\main.js:60:26)
    at D:\Generated assets\Generated assests\Furs Gen\hashlips_art_engine-1.1.2_patch_v6\src\main.js:225:22
    at Array.find (<anonymous>)
    at D:\Generated assets\Generated assests\Furs Gen\hashlips_art_engine-1.1.2_patch_v6\src\main.js:224:42
    at Array.map (<anonymous>)
    at constructLayerToDna (D:\Generated assets\Generated assests\Furs Gen\hashlips_art_engine-1.1.2_patch_v6\src\main.js:223:35)
    at startCreating (D:\Generated assets\Generated assests\Furs Gen\hashlips_art_engine-1.1.2_patch_v6\src\main.js:364:23)
    at D:\Generated assets\Generated assests\Furs Gen\hashlips_art_engine-1.1.2_patch_v6\index.js:6:3
    at Object.<anonymous> (D:\Generated assets\Generated assests\Furs Gen\hashlips_art_engine-1.1.2_patch_v6\index.js:7:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

npm install

npm WARN hashlips_art_engine@1.1.1 No repository field.

audited 65 packages in 0.63s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Using Node ver 14.18.2

**Comment by Don-Chich** [comment]
Using node ver 14.18.2

**Comment by bolshoytoster** [comment]
@Don-Chich you could try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine) instead.

**Comment by Don-Chich** [comment]
@bolshoytoster Tried your fork, no error message anymore but doesn't generate either 

PS C:\Users\trov9\Downloads\hashlips_art_engine-main(1)\hashlips_art_engine-main> npm run generate

> hashlips_art_engine@1.1.1 generate C:\Users\trov9\Downloads\hashlips_art_engine-main(1)\hashlips_art_engine-main
> node index.js

Just stays like that after entering command

**Comment by bolshoytoster** [comment]
@Don-Chich it might be loading images? You could try adding `console.log('Loading edition ' + i)`at the end of [`src/main.js` line ~454](https://github.com/bolshoytoster/hashlips_art_engine/blob/132f9861fe68ad2a229f9aa863dca0f41ed86e67/src/main.js#L453-L455).

**Comment by Don-Chich** [comment]
@bolshoytoster added console.log('Loading edition ' + i) to line 454. It shows it loading edition x, supply is set to 90 and images loading is at 400+. Just keeps loading.

**Comment by bolshoytoster** [comment]
@Don-Chich could you paste your `layersConfigurations` here please?

**Comment by Don-Chich** [comment]
![Screenshot (114)](https://user-images.githubusercontent.com/104963440/200032130-0dbdb5d6-900d-4d17-a3db-5f8595a6cd9e.png)

**Comment by bolshoytoster** [comment]
@Don-Chich could you paste the bit from `src/config.js` that you changed please.

The long time could be due to the number of layers you have.

**Comment by Don-Chich** [comment]
{
    growEditionSizeTo: 10,
    layersOrder: [
     { name: "Background" },
     { name: "Arms F" },
     { name: "Body F" },
     { name: "Neck F" },
     { name: "Neck Shadow" },
     { name: "Face F", },
     { name: "Eye F", },
     { name: "Nose F", },
     { name: "Mouth F", },
     { name: "Head F", },
    ],
   },
   {
    growEditionSizeTo: 20,
    layersOrder: [
     { name: "Background" },
     { name: "Arms B" },
     { name: "Body B" },
     { name: "Neck B" },
     { name: "Neck Shadow" },
     { name: "Face B", },
     { name: "Eye B", },
     { name: "Nose B", },
     { name: "Mouth B", },
     { name: "Head B", },
    ],
   },
   {
      growEditionSizeTo: 30,
    layersOrder: [
    { name: "Background" },
    { name: "Arms D" },
    { name: "Body D" },
    { name: "Neck D" },
    { name: "Neck Shadow" },
    { name: "Face D", },
    { name: "Eye D", },
    { name: "Nose D", },
    { name: "Mouth D", },
    { name: "Head D", },
   ],
  },
  {
       growEditionSizeTo: 40,
    layersOrder: [
     { name: "Background" },
     { name: "Arms C" },
     { name: "Body C" },
     { name: "Neck C" },
     { name: "Neck Shadow" },
     { name: "Face C", },
     { name: "Eye C", },
     { name: "Nose C", },
     { name: "Mouth C", },
     { name: "Head C", },
    ],
   },
   {
    growEditionSizeTo: 50,
    layersOrder: [
      { name: "Background" },
      { name: "Arms A" },
      { name: "Body A" },
      { name: "Neck A" },
      { name: "Neck Shadow" },
      { name: "Face A", },
      { name: "Eye A", },
      { name: "Nose A", },
      { name: "Mouth A", },
      { name: "Head A", },
    ],
   },
   {
    growEditionSizeTo: 60,
    layersOrder: [
      { name: "Background" },
      { name: "Arms E" },
      { name: "Body E" },
      { name: "Neck E" },
      { name: "Neck Shadow" },
      { name: "Face E", },
      { name: "Eye E", },
      { name: "Nose E", },
      { name: "Mouth E", },
      { name: "Head E", },
    ],
   },
   {
    growEditionSizeTo: 70,
    layersOrder: [
      { name: "Background" },
      { name: "Arms G" },
      { name: "Body G" },
      { name: "Neck G" },
      { name: "Neck Shadow" },
      { name: "Face G", },
      { name: "Eye G", },
      { name: "Nose G", },
      { name: "Mouth G", },
      { name: "Head G", },
    ],
   },
   {
    growEditionSizeTo: 80,
    layersOrder: [
      { name: "Background" },
      { name: "Arms H" },
      { name: "Body H" },
      { name: "Neck H" },
      { name: "Neck Shadow" },
      { name: "Face H", },
      { name: "Eye H", },
      { name: "Nose H", },
      { name: "Mouth H", },
      { name: "Head H", },
    ],
   },
   {
    growEditionSizeTo: 90,
    layersOrder: [
      { name: "Background" },
      { name: "Arms I" },
      { name: "Body I" },
      { name: "Neck I" },
      { name: "Neck Shadow" },
      { name: "Face I", },
      { name: "Eye I", },
      { name: "Nose I", },
      { name: "Mouth I", },
      { name: "Head I", },
    ],
   },
   ];

**Comment by Don-Chich** [comment]
Will it have to load edition every time?

**Comment by bolshoytoster** [comment]
@Don-Chich you may have misunderstood `growEditionSizeTo`, it's meant to be the size of that edition (so if you wanted 90 images you'd need to set each of them to `10`). Your current configuration is trying to generate 450 images.

**Comment by Don-Chich** [comment]
@bolshoytoster ah i see, Thought layer growtheditionsize was staggered like v 1.1.2. It's generating now, Absolute legend. Any reason as to what the go was with original issue?

**Comment by bolshoytoster** [comment]
@Don-Chich I think the original issue was due to a layer's weigts all being 0, but I might be wrong, my fork fixes that.

**Comment by Don-Chich** [comment]
@bolshoytoster lol you were right. i forgot to add layers within the some of the folders. The original generator is working now as well. Time to get some sleep. Thanks again.
