### ISSUE TITLE
The script only generating the first layer group.

### ISSUE THREAD

**Issue by x0n0x** [HashLips/hashlips_art_engine#145]
I've prepared more than 100 traits/attributes spread across 8 folders. 
In configuration settings (config.js), I also made 8 layer groups. but when running the script `node index.js` it's only generating the first layer group. 

How to fix this problem so I can generating all layer groups and have 10K NFTs?

**Comment by Sosik1** [comment]
Hello,

I have fixed this issue and created a pull request. You will be able to download the fixed files as soon as the maintainer merges this pull request: #177 

Good Luck

**Comment by x0n0x** [comment]
> Hello,
> 
> I have fixed this issue and created a pull request. You will be able to download the fixed files as soon as the maintainer merges this pull request: #177
> 
> Good Luck

Thanks!
