### ISSUE TITLE
 rarity

### ISSUE THREAD

**Issue by faustoandreabellucci** [HashLips/hashlips_art_engine#1467]
Hi, sorry for the disorder. I generated 10k NFTS but when I went to check them on the clothes on which I had put a percentage of #0,3 out of 10,000 NFT there were not 30 but many more.
They had to be 30 NFTS total with that object out of a total of 10.000 but it is not so.
Can you tell me why?
The acronym of the accessory was this -> Space Suite#0,3

**Comment by bolshoytoster** [comment]
@faustoandreabellucci
> #0,3

The function hashlips uses to parse numbers (`Number`) doesn't support commas anywhere in a number, you should instead use `#0.3`.

> There had to be 30 NFTS total with that object

The weights in hashlips are only probabilities, not exact numbers. So even after following the above advice, you'll only end up with approximately the number you want.

Also, the weights aren't percentages, they're probabilities out of the total for the layer, i.e. if you have a layer:
```js
Background
| image1#30.png
| image2#40.png
```
The layer weight add up to 70, so the probability for `image1` is 30 / 70 (or 3/7 or ~43%).

**Comment by faustoandreabellucci** [comment]
thank you for the explanation @bolshoytoster
