### ISSUE TITLE
hashlip generate only 5615 images instead of 6075 images

### ISSUE THREAD

**Issue by d3fcom** [HashLips/hashlips_art_engine#1469]
Hi guys I'm using Hashlips [version: "1.1.1".] 
I'm using it with Node JS, to generate a collection of NFT's I have inserted in the Layers folder 2 folders (Backgrounds, 45 items), and (Shoes, 135 items) and its suppose to give me 6075 images because 45 x 135 = 6075, but after generating 5615 images it stops and tells me on the terminal that if I want to be able to generate more unique images I need to add more layers ) but its false I'm supposed to be able to produce 6075 images I don't know where did I go wrong.

this is my Config.js file :
---------------------------------------------------------------------------------------------------------------------------------

const basePath = process.cwd();
const { MODE } = require(`${basePath}/constants/blend_mode.js`);
const { NETWORK } = require(`${basePath}/constants/network.js`);

const network = NETWORK.eth;

// General metadata for Ethereum
const namePrefix = "Nft collection article Name example";
const description = "example NFT description ";
const baseUri = "ipfs://NewUriToReplace";

const solanaMetadata = {
  symbol: "EX",
  seller_fee_basis_points: 500, // Define how much % you want from secondary market sales 1000 = 10%
  external_url: "https://www.example.com",
  creators: [
    {
      address: "jdk3R0000EXAMPLEADRESSD0000oUKeB433SSh",
      share: 10000,
    },
  ],
};

// If you have selected Solana then the collection starts from 0 automatically
const layerConfigurations = [
  {
    growEditionSizeTo: 6075,
    layersOrder: [
      { name: "Background" },
      { name: "Shoes" },
    ],
  },
];

const shuffleLayerConfigurations = false;

const debugLogs = true;

const format = {
  width: 2048,
  height: 2048,
  smoothing: false,
};

const gif = {
  export: false,
  repeat: 0,
  quality: 100,
  delay: 500,
};

const text = {
  only: false,
  color: "#ffffff",
  size: 20,
  xGap: 40,
  yGap: 40,
  align: "left",
  baseline: "top",
  weight: "regular",
  family: "Courier",
  spacer: " => ",
};

const pixelFormat = {
  ratio: 2 / 128,
};

const background = {
  generate: false,
  brightness: "80%",
  static: false,
  default: "#000000",
};

const extraMetadata = {
  creator: "d3fco man",
};

const rarityDelimiter = "#";

const uniqueDnaTorrance = 10000;

const preview = {
  thumbPerRow: 5,
  thumbWidth: 50,
  imageRatio: format.height / format.width,
  imageName: "preview.png",
};

const preview_gif = {
  numberOfImages: 5,
  order: "ASC", // ASC, DESC, MIXED
  repeat: 0,
  quality: 100,
  delay: 500,
  imageName: "preview.gif",
};

module.exports = {
  format,
  baseUri,
  description,
  background,
  uniqueDnaTorrance,
  layerConfigurations,
  rarityDelimiter,
  preview,
  shuffleLayerConfigurations,
  debugLogs,
  extraMetadata,
  pixelFormat,
  text,
  namePrefix,
  network,
  solanaMetadata,
  gif,
  preview_gif,
};

---------------------------------------------------------------------------------------------------------------------------------
For the first 5000 somthing images everything goes well but I don't know why at 5615 it stops, I have tried again, and sometimes it produces a little bit more or a little bit fewer images.

but there are really 45 images, in the "background" folder. (different drawings same size png's)

and there is really 135 images in the "Shoes" folder (different drawing but same size png's)

can you guy's Help me please ? I have windows 10, A lot of free space, (200 G's) and the latest Node Js version (v16.13.2) my Hashlips is also the latest version: "1.1.1"

**Comment by bolshoytoster** [comment]
@d3fcom that error message is given when you run into too many duplicates. You can get it to work how you want by setting `uniqueDnaTorrance` in `src/config.js` to `Infinity`.

**Comment by d3fcom** [comment]
oh wow thank you so much @bolshoytoster you saved my life
