### ISSUE TITLE
metadata problems

### ISSUE THREAD

**Issue by faustoandreabellucci** [HashLips/hashlips_art_engine#1471]
hello, I had to change the attributes of some images and I also wanted to delete some.
when I do "node utils/update_info.js" to insert the CID the program resets all 10,000 Json files. Change the attributes of the ones I've edited and put back the ones I've deleted. is there a solution or do i have to put the CID on all 10,000 images by hand? 
I just need to change the CID nothing more

**Comment by bolshoytoster** [comment]
@faustoandreabellucci you'd have to edit the main`_metadata.json`.
