### ISSUE TITLE
npm generate is not working

### ISSUE THREAD

**Issue by unithpaul** [HashLips/hashlips_art_engine#1481]
pranitha@Pranithas-MacBook-Air hashlips_art_engine-1.1.2_patch_v5 % npm install

up to date, audited 71 packages in 1s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
pranitha@Pranithas-MacBook-Air hashlips_art_engine-1.1.2_patch_v5 % npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

node:internal/modules/cjs/loader:1056
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /Users/pranitha/Documents/hashlips_art_engine-1.1.2_patch_v5/node_modules/canvas/lib/bindings.js
- /Users/pranitha/Documents/hashlips_art_engine-1.1.2_patch_v5/node_modules/canvas/lib/canvas.js
- /Users/pranitha/Documents/hashlips_art_engine-1.1.2_patch_v5/node_modules/canvas/index.js
- /Users/pranitha/Documents/hashlips_art_engine-1.1.2_patch_v5/src/main.js
- /Users/pranitha/Documents/hashlips_art_engine-1.1.2_patch_v5/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1053:15)
    at Module._load (node:internal/modules/cjs/loader:898:27)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/pranitha/Documents/hashlips_art_engine-1.1.2_patch_v5/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/pranitha/Documents/hashlips_art_engine-1.1.2_patch_v5/node_modules/canvas/lib/bindings.js',
    '/Users/pranitha/Documents/hashlips_art_engine-1.1.2_patch_v5/node_modules/canvas/lib/canvas.js',
    '/Users/pranitha/Documents/hashlips_art_engine-1.1.2_patch_v5/node_modules/canvas/index.js',
    '/Users/pranitha/Documents/hashlips_art_engine-1.1.2_patch_v5/src/main.js',
    '/Users/pranitha/Documents/hashlips_art_engine-1.1.2_patch_v5/index.js'
  ]
}

Node.js v19.4.0
pranitha@Pranithas-MacBook-Air hashlips_art_engine-1.1.2_patch_v5 %

**Comment by bolshoytoster** [comment]
@unithpaul try deleting `node_modules/` then running `npm install` again.

**Comment by unithpaul** [comment]
it still shows this,

pranitha@Pranithas-MacBook-Air hashlips_art_engine-1.1.2_patch_v6 % npm install
npm ERR! code 1
npm ERR! path /Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/node/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@19.4.0 | darwin | x64
npm ERR! node-pre-gyp info check checked for "/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-darwin-unknown-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-darwin-unknown-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@19.4.0 (node-v111 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-darwin-unknown-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.4.0 | darwin | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.4.0 | darwin | x64
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:483:16)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/node/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v111"
npm ERR! gyp ERR! cwd /Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas
npm ERR! gyp ERR! node -v v19.4.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/node/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! node-pre-gyp ERR! command "/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/node/bin/node" "/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v19.4.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pranitha/.npm/_logs/2023-01-13T23_55_51_050Z-debug-0.log
pranitha@Pranithas-MacBook-Air hashlips_art_engine-1.1.2_patch_v6 %

**Comment by bolshoytoster** [comment]
either downgrade your node.js or change the line:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/package.json#L27

to
```json
  "canvas": "^2.11.0", 
```
in `package.json`.

**Comment by unithpaul** [comment]
i have changed this in package. json but it still shows same

**Comment by unithpaul** [comment]
i have tried for node v18.13.0

pranitha@Pranithas-MacBook-Air hashlips_art_engine-1.1.2_patch_v6 % node -v
v18.13.0
pranitha@Pranithas-MacBook-Air hashlips_art_engine-1.1.2_patch_v6 % npm install
npm ERR! code 1
npm ERR! path /Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/node/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@19.4.0 | darwin | x64
npm ERR! node-pre-gyp info check checked for "/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-darwin-unknown-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-darwin-unknown-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@19.4.0 (node-v111 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-darwin-unknown-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@19.4.0 | darwin | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@19.4.0 | darwin | x64
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:483:16)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/node/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v111"
npm ERR! gyp ERR! cwd /Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas
npm ERR! gyp ERR! node -v v19.4.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/node/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! node-pre-gyp ERR! command "/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/node/bin/node" "/Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/pranitha/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v19.4.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pranitha/.npm/_logs/2023-01-14T00_00_45_208Z-debug-0.log
pranitha@Pranithas-MacBook-Air hashlips_art_engine-1.1.2_patch_v6 %

**Comment by bolshoytoster** [comment]
@unithpaul make sure you save the file when you edit it.

**Comment by unithpaul** [comment]
thank you brother
