### ISSUE TITLE
How to Get Rarity if use DisplayName

### ISSUE THREAD

**Issue by sadun619** [HashLips/hashlips_art_engine#1490]
there is a way to get rarity if use display name option?

**Comment by bolshoytoster** [comment]
@sadun619 [I made a version of `utils/rarity.js` that works with `displayName`](https://github.com/HashLips/hashlips_art_engine/issues/1025#issuecomment-1122721584)

**Comment by sadun619** [comment]
> @sadun619 [I made a version of `utils/rarity.js` that works with `displayName`](https://github.com/HashLips/hashlips_art_engine/issues/1025#issuecomment-1122721584)

thank you, i'll try.

**Comment by sadun619** [comment]
> 

it's working. thank you again.

**Comment by sadun619** [comment]
have another issue. some traits value not showing.  can you fix it please.

![Screenshot (208)](https://user-images.githubusercontent.com/6003462/217956673-4abf7257-a199-4650-840d-07291f323c70.png)
