### ISSUE TITLE
Webp format support?

### ISSUE THREAD

**Issue by bilinkis** [HashLips/hashlips_art_engine#1498]

**Comment by bolshoytoster** [comment]
@bilinkis [node-canvas doesn't currently natively support webp](https://github.com/Automattic/node-canvas/issues/1258), so it's probably easiest to just convert to png/jpeg/pdf.

**Comment by bilinkis** [comment]
> @bilinkis [node-canvas doesn't currently natively support webp](https://github.com/Automattic/node-canvas/issues/1258), so it's probably easiest to just convert to png/jpeg/pdf.

Alright, I guess I'll stick to PNG. Thanks for your fast response!
