### ISSUE TITLE
NPM INSTALL ISSUES

### ISSUE THREAD

**Issue by dibrandon** [HashLips/hashlips_art_engine#1507]
Trying to install Hashlips I got the following error after uninstalling and reinstalling both NODE(18.x) and PYTHON(3.x), the problem persisted, I went through the node documentation for NODE-GYP problems ( https://github.com/nodejs/node-gyp#on-windows ), install the Visual Studio IDE (no visual studio code) from VS INSTALLER, install NODE and PY, try again with npm install a hashlips and NOTHING! I changed my directories to English (just in case) and NOTHING! Looking through the issues of other users here, I found that someone suggested changing the version of Canvas to version 2.11.0. Believe it or not, but it worked!

I repeat for those who have problems with NPM INSTALL, 

try first   `npm install canvas@2.11.0` then `npm install`.
Of course it requires that you have python and node installed first.

quotes;
         
              @gwilldan you could try changing the line:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/package.json#L27

to
```json
  "canvas": "^2.11.0", 
```
in `package.json`.

_Originally posted by @bolshoytoster in https://github.com/HashLips/hashlips_art_engine/issues/1489#issuecomment-1399470005_

another quote:
              @gwilldan you could try just running `npm install canvas@2.11.0` then `npm install`.

_Originally posted by @bolshoytoster in https://github.com/HashLips/hashlips_art_engine/issues/1489#issuecomment-1399471588_
            

My orignal(replicated) error log :

$ npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.       
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\node-fetch',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\node-fetch'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\node-fetch'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\node-fetch'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\node-fetch'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\nopt',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\nopt'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\nopt'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Warning: Missing input files:
npm ERR! C:\GTK\bin\libpangocairo-1.0-0.dll
npm ERR! C:\GTK\bin\libglib-2.0-0.dll
npm ERR! C:\GTK\bin\libintl-8.dll
npm ERR! C:\GTK\bin\libgmodule-2.0-0.dll
npm ERR! C:\GTK\bin\libgthread-2.0-0.dll
npm ERR! C:\GTK\bin\libfreetype-6.dll
npm ERR! C:\GTK\bin\zlib1.dll
npm ERR! C:\GTK\bin\libgobject-2.0-0.dll
npm ERR! C:\GTK\bin\libpng14-14.dll
npm ERR! C:\GTK\bin\libpangowin32-1.0-0.dll
npm ERR! C:\GTK\bin\libcairo-2.dll
npm ERR! C:\GTK\bin\libfontconfig-1.dll
npm ERR! C:\GTK\bin\libpangoft2-1.0-0.dll
npm ERR! C:\GTK\bin\libexpat-1.dll
npm ERR! C:\GTK\bin\libpango-1.0-0.dll
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!
npm ERR!   Backend.cc
npm ERR! D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\src\backend\Backend.h(3,10): fatal  error C1083: No se puede abrir el archivo incluir: 'cairo.h': No such file or directory [D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\build\canvas.vcxproj]
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\kuro\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js 
build --fallback-to-build --module=D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@18.15.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-win32-unknown-x64.tar.gz    
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@18.15.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-win32-unknown-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.15.0 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.15.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.10 found at "C:\Users\kuro\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp info find VS using VS2022 (17.5.33502.453) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\kuro\AppData\Local\Programs\Python\Python310\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\kuro\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\canvas\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\kuro\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\kuro\\AppData\\Local\\node-gyp\\Cache\\18.15.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\kuro\\AppData\\Local\\node-gyp\\Cache\\18.15.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\kuro\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\kuro\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.15.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\canvas\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.15.0 | win32 | x64
npm ERR! gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1     
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\kuro\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:203:23)     
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kuro\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas
npm ERR! gyp ERR! node -v v18.15.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\kuro\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19044
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\DESCARGAS\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd D:\DESCARGAS\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v18.15.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kuro\AppData\Local\npm-cache\_logs\2023-03-16T12_05_50_129Z-debug-0.log

**Comment by dibrandon** [comment]
I repeat for those who have problems with NPM INSTALL,

try first npm install canvas@2.11.0 then npm install.


Of course it requires that you have python and node installed first.

**Comment by dibrandon** [comment]
I repeat for those who have problems with NPM INSTALL,

try first  `npm install canvas@2.11.0` then `npm install`.


Of course, it requires that you have python and node installed first.

**Comment by bolshoytoster** [comment]
@dibrandon I have a PR open which will update the canvas dependency, but I don't think @HashLips has been on this repo for over a year.
