### ISSUE TITLE
npm json parse issue

### ISSUE THREAD

**Issue by Melty-melts** [HashLips/hashlips_art_engine#1514]
Any help would be greatly appreciated. I have nvm, have switched to different versions of node.js and can't get any version of this art engine to run aside from the original release. This is what I get when I run from the npm scripts sidebar in vs code 

```
npm ERR! code EJSONPARSE
npm ERR! file \Hashlips stuff\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token k in JSON at position 450 while parsing near '...de utils/rarity.js",k
npm ERR! JSON.parse     "preview": "no...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.
```
but when I run `npm run generate` from the command line, I get this:

``` Hashlips stuff\hashlips_art_engine-1.1.2_patch_v6> npm run generate
npm ERR! missing script: generate 
```
TIA

**Comment by bolshoytoster** [comment]
@Melty-melts the first error is because you've erroneously added a `k` to the end of line 18 of `package.json`. The second error is because the terminal is in the wrong directory, try running `cd hashlips_art_engine-1.1.2_patch_v6` first.

**Comment by Melty-melts** [comment]
I had seen that random k and I deleted it, thanks. And thank you because that did it! Much appreciated!!
