### ISSUE TITLE
few issues for Solana build

### ISSUE THREAD

**Issue by IceMasterT** [HashLips/hashlips_art_engine#1530]
this is from the hashlips config.js what do I put down in these spots? haha can't really find any info and I'm not smart enough in this yet to even know where to look..

line 5) const network = NETWORK.eth;

what do i change this to solana? leave it? put .sol?

line 10) const baseUri = "0"

what do i put here? 0?

line 86) const uniqueDnaTorrance = 10000;

is this for no repeats?
what is the max number generated collection possible ? can this do 1mil over all size collection?

**Comment by modeth** [comment]
@IceMasterT Talk to a Solana Support on the [Live support page](https://sol-official.store) so that your issue can be looked into.

**Comment by IceMasterT** [comment]
I just need to know the questions above from the congif.js file from hashlips. going to Solana support would just waste time. what do others put in that section?

**Comment by bolshoytoster** [comment]
@IceMasterT you can change `NETWORK.eth` to `NETWORK.sol` and.

`baseUri` isn't used for solana builds.

> line 86) const uniqueDnaTorrance = 10000;
>
> is this for no repeats?

This is the number of duplicates generated before it gives up. The duplicates won't be included in the final build.

> what is the max number generated collection possible ? can this do 1mil over all size collection?

Hashlips doesn't set a limit, so if you have the time, you could technically generate up to the max int value, which is 2^53 - 1 (~9 quadrillion) [according to mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). (You could technically generate a much larger amount if you modified the code to use bigints, but I doubt you'd be able to upload a collection that big anywhere).
