### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by FishDudes** [HashLips/hashlips_art_engine#1535]
[Bot-Hosting Daemon]: Checking server disk space usage, this could take a few seconds...
[Bot-Hosting Daemon]: Updating process configuration files...
[Bot-Hosting Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Bot-Hosting Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Bot-Hosting Daemon]: Finished pulling Docker container image
Python 3.11.3
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${PY_PACKAGES} ]]; then pip install -U --prefix .local ${PY_PACKAGES}; fi; if [[ -f /home/container/${REQUIREMENTS_FILE} ]]; then pip install -U --prefix .local -r ${REQUIREMENTS_FILE}; fi; /usr/local/bin/python /home/container/${BOT_PY_FILE}
container@pterodactyl~ Server marked as offline...
[Bot-Hosting Daemon]: ---------- Detected server process in a crashed state! ----------
[Bot-Hosting Daemon]: Exit code: 0
[Bot-Hosting Daemon]: Out of memory: false
[Bot-Hosting Daemon]: Checking server disk space usage, this could take a few seconds...
[Bot-Hosting Daemon]: Updating process configuration files...
[Bot-Hosting Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Bot-Hosting Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Bot-Hosting Daemon]: Finished pulling Docker container image
Python 3.11.3
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${PY_PACKAGES} ]]; then pip install -U --prefix .local ${PY_PACKAGES}; fi; if [[ -f /home/container/${REQUIREMENTS_FILE} ]]; then pip install -U --prefix .local -r ${REQUIREMENTS_FILE}; fi; /usr/local/bin/python /home/container/${BOT_PY_FILE}
container@pterodactyl~ Server marked as offline...
[Bot-Hosting Daemon]: ---------- Detected server process in a crashed state! ----------
[Bot-Hosting Daemon]: Exit code: 0
[Bot-Hosting Daemon]: Out of memory: false
[Bot-Hosting Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by bolshoytoster** [comment]
@FishDudeYT [again](https://github.com/HashLips/hashlips_art_engine/issues/1534), you've opened an issue in the wrong place. I don't know what software that is, so I can't refer you to an appropriate place (my best guess is [this](https://github.com/pterodactyl/panel)). You should report issues on the softwares' pages.
