### ISSUE TITLE
Can't mint beyoned 437

### ISSUE THREAD

**Issue by ShaDyDeVIL888** [HashLips/hashlips_art_engine#1545]
Hello, I have succesfully minted 437 nfts on polygon, opensea, but when I want to continue it tells me it minted but there is no process invilved as I see the 'completed' text immediately and there are no files on opensea. 

PS D:\Photoshop\Project\Project\create-10k-nft-collection> npm run mint --start=438

> mint
> node utils/nftport/mint %npm_config_start% %npm_config_end%

OK to mint 438-Remaining? (y/n): y
Minting complete. To check for errors run command: npm run check_txns --dir=minted
PS D:\Photoshop\Project\Project\create-10k-nft-collection>

**Comment by bolshoytoster** [comment]
@ShaDyDeVIL888 you've opened this issue in the wrong place, you probably wanted to open it on [codeSTACKr's repo](https://github.com/codeSTACKr/create-10k-nft-collection).

**Comment by ShaDyDeVIL888** [comment]
Hello, I have opened it there as well, I thought it might be similar, sorry, I will close it now
