### ISSUE TITLE
Extreme rarities not showing up!

### ISSUE THREAD

**Issue by javinbhalla** [HashLips/hashlips_art_engine#1552]
I am using the art engine app on mac and had set the rarities like you mentioned. Example : Car1$71.50.png  Car2$27.75.png  Car3$0.74.png Car4$0.01.png

All the layer files in each folders add up to exactly 100. But the extremely rare items (Example : Car4$0.01.png) are not showing up.

I have a 11,111 items collection which would meaning I should have at-least 111 Car4.png [0.01 X 11,111 = 111.11(Approx)]

Can anyone tell me why this is happening?

**Comment by bolshoytoster** [comment]
@javinbhalla this is due to how chance works, you will likely not generate the exact amounts of images that you want. You could try either generating multiple times or manually adding certain rare images afterwards.

**Comment by javinbhalla** [comment]
> @javinbhalla this is due to how chance works, you will likely not generate the exact amounts of images that you want. You could try either generating multiple times or manually adding certain rare images afterwards.

I actually switched from the app to hashlips engine and replaced the $ with # and voila that solved the issue! Thanks for the response though!
