### ISSUE TITLE
Possible to Change Output Folder?

### ISSUE THREAD

**Issue by IceMasterT** [HashLips/hashlips_art_engine#1553]
How do i change the output folder? i have a nice empty external hard drive.. what would be the best way to go about using it? just move the directory over?

**Comment by bolshoytoster** [comment]
@IceMasterT you can change `buildDir` ~line 6 of `src/main.js`:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L5-L7

This will make it put the images/metadata wherever you specify.

This will only chamge behaviour for `src/main.js`, you may want to change [other occurances in the code](https://github.com/HashLips/hashlips_art_engine/search?q=build).

**Comment by amritabithi** [comment]
> How do i change the output folder? i have a nice empty external hard drive.. what would be the best way to go about using it? just move the directory over?

You can also just copy your entirei hashlips folder that you are working from over to the external drive, and then change your current working directory on the command line to that folder, so for me it looks like like:
`cd /media/amrita/331c2fe3-8a14-425a-9275-fa85c865d94b`
Then re-build the project at the new location:
Run this command if you have yarn installed.
`yarn install`
Alternatively you can run this command if you have node installed.
`npm install`

From there you should be able to run everything as you normally would, and you can check to confirm your current working directory with the command:
`pwd`
