### ISSUE TITLE
i'm facing this error: 'MODULE_NOT_FOUND',   requireStack: [], please guide me.

### ISSUE THREAD

**Issue by umer007khan** [HashLips/hashlips_art_engine#1565]
Error: Cannot find module 'X:\PP\art-engine-template-main\main.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by umer007khan** [comment]
i tried to solve it, but didn't find a way

**Comment by bolshoytoster** [comment]
@umer007khan it looks like you're using [this repository](https://github.com/hashlips-lab/art-engine-template), which doesn't contain a `main.js`. I'm not sure what you're trying to do, but you could try running `node index.js` or `npm run start` instead.

**Comment by umer007khan** [comment]
i'm using a correct directory but i think think error is causing by Node JS module, do you have any idea how to solve it?

example
PS X:\PP\hashlips art engine stable> node main.js
**node:internal/modules/cjs/loader:1080**
  throw err;
  ^

Error: Cannot find module 'X:\PP\hashlips art engine stable\main.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by bolshoytoster** [comment]
@umer007khan
> i think think error is causing by Node JS module

No it is not, the error is `Error: Cannot find module 'X:\PP\hashlips art engine stable\main.js'`. This is, as I said, because there is no `main.js`. You can try running `node index.js` or `npm run build` instead.

**Comment by umer007khan** [comment]
Sir, main.js is present in project file.

PS X:\PP\hashlips art engine stable> dir


    Directory: X:\PP\hashlips art engine stable


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2/18/2023   2:02 PM                .github
d-----         2/18/2023   2:02 PM                .vscode
d-----          5/6/2023   3:35 PM                build
d-----         2/18/2023   2:02 PM                constants
d-----          7/8/2023   4:16 PM                layers
d-----         2/18/2023   2:02 PM                modules
d-----          7/8/2023   4:35 PM                node_modules
d-----          7/8/2023   9:22 PM                src
d-----         2/18/2023   2:04 PM                utils
-a----        10/30/2022  10:28 PM           1678 .gitignore
-a----        10/30/2022  10:28 PM              9 .nvmrc
-a----        10/30/2022  10:28 PM         441599 banner.png
-a----        10/30/2022  10:28 PM            157 index.js
-a----        10/30/2022  10:28 PM           1065 LICENSE
-a----        10/30/2022  10:28 PM          37711 logo.png
-a----          7/8/2023   4:33 PM          41575 package-lock.json
-a----        10/30/2022  10:28 PM            861 package.json
-a----        10/30/2022  10:28 PM           9930 README.md
-a----          7/8/2023   4:33 PM          16305 yarn.lock


PS X:\PP\hashlips art engine stable> cd src
PS X:\PP\hashlips art engine stable\src> dir


    Directory: X:\PP\hashlips art engine stable\src


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          7/8/2023   3:33 PM           2982 config.js
-a----        10/30/2022  10:28 PM          12297 **_main.js_**


PS X:\PP\hashlips art engine stable\src>

**Comment by bolshoytoster** [comment]
@umer007khan yes, `main.js` exists, but under `src/`. You would have to run `node src/main.js` to run it. However, this is not how hashlips is run, you need to run `index.js`.

**Comment by umer007khan** [comment]
did i have to downgrade node js version?


PS X:\PP\hashlips art engine stable> node index.js      
node:internal/modules/cjs/loader:1340
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\X:\PP\hashlips art engine stable\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
**NODE_MODULE_VERSION 93. This version of Node.js requires**
_NODE_MODULE_VERSION 108. Please try re-compiling or re-installing_
    at Object.<anonymous> (X:\PP\hashlips art engine stable\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by bolshoytoster** [comment]
@umer007khan you can either downgrade node to v16 or rebbuild dependencies by deleting `node_modules/` and running `npm install` again.

**Comment by umer007khan** [comment]
thanks for guidance issue is solved, i had to downgrade node version.

**Comment by jonny-dungeons** [comment]
No need to downgrade node at all. 

I just came into this issue while using node v21.7.3 / yarn v4.3.1 and I simply went [here](https://www.npmjs.com/package/canvas) and followed the explicit instruction to download several packages with homebrew. 

Problem solved for me.

See the screenshot:
![image](https://github.com/user-attachments/assets/fede09e6-b967-4a50-9b6e-f3e3e0c179a0)
