### ISSUE TITLE
HashLips using only last folder on /src/config to generate images

### ISSUE THREAD

**Issue by FerTia8** [HashLips/hashlips_art_engine#1566]
Hey there,
My /layers folder looks something like this:

├── Background
│   └── Black#1.png
├── First Number
│   ├── FirstOne#45.png
│   ├── FirstPi#10.png
│   └── FirstZero#45.png
├── Second Number
│   ├── SecondE#6.png
│   ├── SecondGolden#1.png
│   ├── SecondI#3.png
│   ├── SecondOne#45.png
│   └── SecondZero#45.png
└── Sign
    ├── Minus#50.png
    └── Plus#50.png

in /src/config: 
```
const layerConfigurations = [
  {
    growEditionSizeTo: 7,
    layersOrder: [
      { name: "Background" },
      { name: "Sign" },
      { name: "First Number" },
      { name: "Second Number" },
    ],
  },
];
```

Despite generating 7 images each containing right metadata for each layer, the resulting png contains only the 'Second Number' layer, which I find odd since my example isn't very distinct from the default one. Any help would be appreciated!

**Comment by bolshoytoster** [comment]
@FerTia8 you could make sure the images under `layers/Second Number/` have transparent backgrounds.

**Comment by FerTia8** [comment]
yeah the .pngs weren't really pngs lol, thanks!
