### ISSUE TITLE
Image generate error

### ISSUE THREAD

**Issue by nicholasm12** [HashLips/hashlips_art_engine#1567]
So, when I run "npm run generate" instead of generating the image it shows like this:
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! Missing script: "generate"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

**Comment by nicholasm12** [comment]
I try to solved it but failed, I had already downgrade my node.js, btw.
Everything had installed properly.
I would really appreciate your help, thank you.

**Comment by bolshoytoster** [comment]
@nicholasm12 your terminal is in the wrong folder, try running `cd hashlips_art_engine-main/` or whatever it's called first.

**Comment by nicholasm12** [comment]
@bolshoytoster , it still doesn't work , After I run the cd and try to run 'npm run build' it shows:
> hashlips_art_engine@1.1.1 build
> node index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\STLABS\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6/node_modules/sha1'
Require stack:
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous>
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [

**Comment by bolshoytoster** [comment]
@nicholasm12 you still need to run `npm install` before `npm run build`.

**Comment by nicholasm12** [comment]
I always run npm i first

**Comment by nicholasm12** [comment]
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

up to date, audited 65 packages in 3s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
This shows when I run 'npm i'

**Comment by nicholasm12** [comment]
Bro, thank you ,it works when I uninstall the npm thanks a lot

**Comment by nicholasm12** [comment]
thanks bro @bolshoytoster
