### ISSUE TITLE
error while reading from input stream...

### ISSUE THREAD

**Issue by Niemandy** [HashLips/hashlips_art_engine#1568]
Please help me solve the problem.
I tried to solve it in different ways, but it doesn't work.
![image](https://github.com/HashLips/hashlips_art_engine/assets/140972582/e62443c0-4c5e-442e-bc21-b4a127abbc44)

**Comment by bolshoytoster** [comment]
@Niemandy could you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine), it should tell you which image(s) cause the issue.

**Comment by Niemandy** [comment]
> @Niemandy could you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine), it should tell you which image(s) cause the issue.

Thank you very much, it skipped the error in the beginning and then started working. It skipped all the GIF files.
