### ISSUE TITLE
I cant install reactjs on my machine

### ISSUE THREAD

**Issue by AndreOmniBarry** [HashLips/hashlips_art_engine#1571]
Last login: Fri Aug 11 23:10:37 on ttys006
OmniBarrys-MacBook:~ khourageandreomnibarry$ npm install -g create react app
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'create@0.0.2',
npm WARN EBADENGINE   required: { node: '>= 0.4.0 && < 0.7.0' },
npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.5.1' }
npm WARN EBADENGINE }
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/app
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/app'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/app'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/app'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khourageandreomnibarry/.npm/_logs/2023-08-11T22_13_22_433Z-debug-0.log
OmniBarrys-MacBook:~ khourageandreomnibarry$

**Comment by AndreOmniBarry** [comment]
I get same errors using npx, currently I'm running on node: 'v18.16.0', and npm: '9.5.1'
I tried downloading a lesser version of node but the earliest available version is Node.js 0.12.18.

**Comment by bolshoytoster** [comment]
@AndreOmniBarry have you read the error:
```
The operation was rejected by your operating system.
It is likely you do not have the permissions to access this file as the current user

If you believe this might be a permissions issue, please double-check the
permissions of the file and its containing directories, or try running
the command again as root/Administrator.
```

**Comment by AndreOmniBarry** [comment]
Yes I saw this and do not how what that means nor do I know how to get past it

**Comment by AndreOmniBarry** [comment]
i just did this

OmniBarrys-MacBook:~ khourageandreomnibarry$ npm  cache clear --force
npm WARN using --force Recommended protections disabled.
npm ERR! code EACCES
npm ERR! syscall unlink
npm ERR! path /Users/khourageandreomnibarry/.npm/_cacache/index-v5/00/9d/6d0e43e3004178c2fd077379422ad42e5aca94d21615275b0dc091d02b82
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 502:20 "/Users/khourageandreomnibarry/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khourageandreomnibarry/.npm/_logs/2023-08-12T00_37_03_268Z-debug-0.log

**Comment by AndreOmniBarry** [comment]
OmniBarrys-MacBook:~ khourageandreomnibarry$ sudo chown -R 502:20 "/Users/khourageandreomnibarry/.npm"
Password:
OmniBarrys-MacBook:~ khourageandreomnibarry$ sudo npm install -g react

added 3 packages in 9s
OmniBarrys-MacBook:~ khourageandreomnibarry$ ls
Applications		Movies			my
Desktop			Music			node_modules
Documents		Pictures		package-lock.json
Downloads		Public			package.json
Google Digital Camp	index.html		react
Library			movie			websites
OmniBarrys-MacBook:~ khourageandreomnibarry$ cd react
OmniBarrys-MacBook:react khourageandreomnibarry$ ls
README.md	package.json	src
index.html	public		vite.config.js
OmniBarrys-MacBook:react khourageandreomnibarry$ npm install react
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /Users/khourageandreomnibarry/.npm/_cacache/tmp/b70d7db8
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 502:20 "/Users/khourageandreomnibarry/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khourageandreomnibarry/.npm/_logs/2023-08-12T00_44_38_392Z-debug-0.log
OmniBarrys-MacBook:react khourageandreomnibarry$ sudo chown -R 502:20 "/Users/khourageandreomnibarry/.npm"
Password:
OmniBarrys-MacBook:react khourageandreomnibarry$ ls
README.md	package.json	src
index.html	public		vite.config.js
OmniBarrys-MacBook:react khourageandreomnibarry$ npm install -g create-vite

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/create-vite
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/create-vite'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/create-vite'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/create-vite'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khourageandreomnibarry/.npm/_logs/2023-08-12T00_50_12_104Z-debug-0.log
OmniBarrys-MacBook:react khourageandreomnibarry$ 
OmniBarrys-MacBook:react khourageandreomnibarry$ npm install -g create-vite
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/create-vite
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/create-vite'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/create-vite'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/create-vite'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khourageandreomnibarry/.npm/_logs/2023-08-12T00_50_33_538Z-debug-0.log
OmniBarrys-MacBook:react khourageandreomnibarry$ 
OmniBarrys-MacBook:react khourageandreomnibarry$

**Comment by bolshoytoster** [comment]
@AndreOmniBarry the solution is to run `npm install react` as root/admin:

```sh
sudo npm install react
```

**Comment by AndreOmniBarry** [comment]
It came up with same errors. 
it think its an npm problem, cos yarn worked just fine for me.

Thanks a million
