### ISSUE TITLE
help me I can't figure out what's the matter

### ISSUE THREAD

**Issue by Samuil-end** [HashLips/hashlips_art_engine#1597]
PS C:\NFT\hashlips_art_engine> npm install
npm warn old lockfile
npm warn old lockfile The package-lock.json file was created with an old version of npm,
npm warn old lockfile so supplemental metadata must be fetched from the registry.
npm warn old lockfile
npm warn old lockfile This is a one-time fix-up, please be patient...
npm warn old lockfile
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'C:\\NFT\\hashlips_art_engine\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\NFT\hashlips_art_engine\node_modules\readable-stream\lib'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\NFT\\hashlips_art_engine\\node_modules\\readable-stream\\lib'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path C:\NFT\hashlips_art_engine\node_modules\canvas
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm error Warning: Missing input files:
npm error C:\GTK\bin\zlib1.dll
npm error C:\GTK\bin\libpng14-14.dll
npm error C:\GTK\bin\libgmodule-2.0-0.dll
npm error C:\GTK\bin\libgthread-2.0-0.dll
npm error C:\GTK\bin\libintl-8.dll
npm error C:\GTK\bin\libpangoft2-1.0-0.dll
npm error C:\GTK\bin\libpangowin32-1.0-0.dll
npm error C:\GTK\bin\libfreetype-6.dll
npm error C:\GTK\bin\libfontconfig-1.dll
npm error C:\GTK\bin\libgobject-2.0-0.dll
npm error C:\GTK\bin\libexpat-1.dll
npm error C:\GTK\bin\libglib-2.0-0.dll
npm error C:\GTK\bin\libpangocairo-1.0-0.dll
npm error C:\GTK\bin\libpango-1.0-0.dll
npm error C:\GTK\bin\libcairo-2.dll
npm error
npm error   Backend.cc
npm error C:\NFT\hashlips_art_engine\node_modules\canvas\src\backend\Backend.h(3,10): error C1083: �� 㤠���� ������ 䠩� ����祭��: cairo.h: No such file or directory, [C:\NFT\hashlips_art_engine\node_modules\canvas\build\canvas.vcxproj]
npm error   (��������� ��室���� 䠩�� "../src/backend/Backend.cc")
npm error
npm error Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\21sam\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\NFT\hashlips_art_engine\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\NFT\hashlips_art_engine\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm error node-pre-gyp info it worked if it ends with ok
npm error node-pre-gyp info using node-pre-gyp@1.0.6
npm error node-pre-gyp info using node@20.13.1 | win32 | x64
npm error node-pre-gyp info check checked for "C:\NFT\hashlips_art_engine\node_modules\canvas\build\Release\canvas.node" (not found)
npm error node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-x64.tar.gz
npm error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-x64.tar.gz
npm error node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@20.13.1 (node-v115 ABI, unknown) (falling back to source compile with node-gyp)
npm error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-x64.tar.gz
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.13.1 | win32 | x64
npm error gyp info ok
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.13.1 | win32 | x64
npm error gyp info find Python using Python version 3.12.3 found at "C:\Python312\python.exe"
npm error gyp info find VS using VS2022 (17.9.34728.123) found at:
npm error gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
npm error gyp info find VS run with --verbose for detailed information
npm error gyp info spawn C:\Python312\python.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'C:\\Users\\21sam\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',        
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'msvs',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\NFT\\hashlips_art_engine\\node_modules\\canvas\\build\\config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\21sam\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\21sam\\AppData\\Local\\node-gyp\\Cache\\20.13.1\\include\\node\\common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=C:\\Users\\21sam\\AppData\\Local\\node-gyp\\Cache\\20.13.1',
npm error gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\21sam\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\21sam\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.13.1\\\\<(target_arch)\\\\node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=C:\\NFT\\hashlips_art_engine\\node_modules\\canvas',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'C:\\NFT\\hashlips_art_engine\\node_modules\\canvas\\build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info ok
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.13.1 | win32 | x64
npm error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'build\\binding.sln',
npm error gyp info spawn args '/clp:Verbosity=minimal',
npm error gyp info spawn args '/nologo',
npm error gyp info spawn args '/p:Configuration=Release;Platform=x64'
npm error gyp info spawn args ]
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\21sam\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
npm error gyp ERR! stack at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Windows_NT 10.0.26120
npm error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\21sam\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\NFT\\hashlips_art_engine\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\NFT\\hashlips_art_engine\\node_modules\\canvas\\build\\Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
npm error gyp ERR! cwd C:\NFT\hashlips_art_engine\node_modules\canvas
npm error gyp ERR! node -v v20.13.1
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
npm error node-pre-gyp ERR! build error
npm error node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\21sam\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\NFT\hashlips_art_engine\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\NFT\hashlips_art_engine\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\NFT\hashlips_art_engine\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm error node-pre-gyp ERR! System Windows_NT 10.0.26120
npm error node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\NFT\\hashlips_art_engine\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm error node-pre-gyp ERR! cwd C:\NFT\hashlips_art_engine\node_modules\canvas
npm error node-pre-gyp ERR! node -v v20.13.1
npm error node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm error node-pre-gyp ERR! not ok

npm error A complete log of this run can be found in: C:\Users\21sam\AppData\Local\npm-cache\_logs\2024-05-13T15_23_09_082Z-debug-0.log

**Comment by bolshoytoster** [comment]
@Samuil-end you need to either downgrade your node or upgrade the canvas dependency

**Comment by Samuil-end** [comment]
how can I raise it?

**Comment by bolshoytoster** [comment]
@Samuil-end have a look at [this thread](https://github.com/HashLips/hashlips_art_engine/issues/1586#issuecomment-1928544039).

**Comment by Samuil-end** [comment]
PS C:\NFT\hashlips_art_engine> npm install              
npm warn old lockfile
npm warn old lockfile The package-lock.json file was created with an old version of npm,
npm warn old lockfile so supplemental metadata must be fetched from the registry.
npm warn old lockfile
npm warn old lockfile This is a one-time fix-up, please be patient...
npm warn old lockfile
npm warn old lockfile Could not fetch metadata for canvas@2.11.2 Error: Integrity checksum failed when using sha512: wanted sha512-gLTi17X8WY9Cf5GZ2Yns8T5lfBOcGgFehDFb+JQwDqdOoBOcECS9ZWMEAqMSVcMYwXD659J8NyzjRY/2aE+C2Q== but got sha512-ItanGBMrmRV7Py2Z+Xhs7cT+FNt5K0vPL4p9EZ/UX/Mu7hFbkxSjKF2KVtPwX7UYWp7dRKnrTvReflgrItJbdw==.
npm warn old lockfile     at RegistryFetcher.manifest (C:\Users\21sam\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:164:35)
npm warn old lockfile     at async C:\Users\21sam\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:734:24 {
npm warn old lockfile   code: 'EINTEGRITY'
npm warn old lockfile }
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'C:\\NFT\\hashlips_art_engine\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\NFT\hashlips_art_engine\node_modules\@mapbox\node-pre-gyp'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\NFT\\hashlips_art_engine\\node_modules\\@mapbox\\node-pre-gyp'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path C:\NFT\hashlips_art_engine\node_modules\canvas
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm error Warning: Missing input files:
npm error C:\GTK\bin\libpangocairo-1.0-0.dll
npm error C:\GTK\bin\libpango-1.0-0.dll
npm error C:\GTK\bin\libglib-2.0-0.dll
npm error C:\GTK\bin\libexpat-1.dll
npm error C:\GTK\bin\libfontconfig-1.dll
npm error C:\GTK\bin\libgobject-2.0-0.dll
npm error C:\GTK\bin\libpng14-14.dll
npm error C:\GTK\bin\libintl-8.dll
npm error C:\GTK\bin\libfreetype-6.dll
npm error C:\GTK\bin\libgmodule-2.0-0.dll
npm error C:\GTK\bin\zlib1.dll
npm error C:\GTK\bin\libpangowin32-1.0-0.dll
npm error C:\GTK\bin\libgthread-2.0-0.dll
npm error C:\GTK\bin\libpangoft2-1.0-0.dll
npm error C:\GTK\bin\libcairo-2.dll
npm error
npm error   Backend.cc
npm error C:\NFT\hashlips_art_engine\node_modules\canvas\src\backend\Backend.h(3,10): error C1083: �� 㤠���� ������ 䠩� ����祭��: cairo.h: No such file or directory, [C:\NFT\hashlips_art_engine\node_modules\canvas\build\canvas.vcxproj]
npm error   (��������� ��室���� 䠩�� "../src/backend/Backend.cc")
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@22.1.0 | win32 | x64
npm error gyp info find Python using Python version 3.12.3 found at "C:\Python312\python.exe"
npm error gyp info find VS using VS2022 (17.9.34728.123) found at:
npm error gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
npm error gyp info find VS run with --verbose for detailed information
npm error gyp info spawn C:\Python312\python.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'C:\\Users\\21sam\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',        
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'msvs',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\NFT\\hashlips_art_engine\\node_modules\\canvas\\build\\config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\21sam\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\21sam\\AppData\\Local\\node-gyp\\Cache\\22.1.0\\include\\node\\common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=C:\\Users\\21sam\\AppData\\Local\\node-gyp\\Cache\\22.1.0',
npm error gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\21sam\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\21sam\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\22.1.0\\\\<(target_arch)\\\\node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=C:\\NFT\\hashlips_art_engine\\node_modules\\canvas',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'C:\\NFT\\hashlips_art_engine\\node_modules\\canvas\\build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'build\\binding.sln',
npm error gyp info spawn args '/clp:Verbosity=minimal',
npm error gyp info spawn args '/nologo',
npm error gyp info spawn args '/p:Configuration=Release;Platform=x64'
npm error gyp info spawn args ]
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\21sam\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
npm error gyp ERR! stack at ChildProcess.emit (node:events:520:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Windows_NT 10.0.26120
npm error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\21sam\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm error gyp ERR! cwd C:\NFT\hashlips_art_engine\node_modules\canvas
npm error gyp ERR! node -v v22.1.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok

npm error A complete log of this run can be found in: C:\Users\21sam\AppData\Local\npm-cache\_logs\2024-05-13T17_15_49_939Z-debug-0.log      
PS C:\NFT\hashlips_art_engine>

**Comment by Samuil-end** [comment]
Now it's written

**Comment by bolshoytoster** [comment]
@Samuil-end try deleting `node_modules/`.

**Comment by Samuil-end** [comment]
I reinstalled the project and registered the team
I've tried it now, like you said, but it's still the same mistake.

**Comment by Samuil-end** [comment]
I solved the problem by installing an old version of Nodes
