### ISSUE TITLE
yarn.ps1 cannot be loaded because running scripts is disabled on this system. 

### ISSUE THREAD

**Issue by bkhoward2001** [HashLips/hashlips_art_engine#19]
When I try to install yarn I get the following on windows:

PS E:\NTF\hashlips_art_engine-main> yarn install
yarn : File C:\Users\Brian\AppData\Roaming\npm\yarn.ps1 cannot be loaded because running scripts is disabled on this system. 
For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ yarn install

How do I fix? I am a newbie.

**Comment by mmintel** [comment]
you should be using WSL2

**Comment by trentmercer** [comment]
@bkhoward2001 Run this command in powershell with elevated privileges: ```Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted```
