### ISSUE TITLE
MODULE_NOT_FOUND 💣🤯🤯🤯

### ISSUE THREAD

**Issue by The-Last-Adam** [HashLips/hashlips_art_engine#2]
I have followed the new tutorial to a T and keep getting this error:

PS C:\Users\Morpheus360\hashlips_art_engine-1.0.0> node index.js
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'C:\Users\Morpheus360\hashlips_art_engine-1.0.0\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[config_js file.txt](https://github.com/HashLips/hashlips_art_engine/files/7158814/config_js.file.txt)

**Comment by HashLips** [comment]
Did you try install with Yarn or NPM?

**Comment by HashLips** [comment]
Please try to install using yarn, and then make sure you are in the root of the folder when calling node index.js you can alternatively Google the error because I see this is windows. Would be a great way for more windows users to see if you can find a fix.

**Comment by fonzi69** [comment]
> I have followed the new tutorial to a T and keep getting this error:
> 
> PS C:\Users\Morpheus360\hashlips_art_engine-1.0.0> node index.js internal/modules/cjs/loader.js:892 throw err; ^
> 
> Error: Cannot find module 'C:\Users\Morpheus360\hashlips_art_engine-1.0.0\index.js' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15) at Function.Module._load (internal/modules/cjs/loader.js:745:27) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) at internal/main/run_main_module.js:17:47 { code: 'MODULE_NOT_FOUND', requireStack: [] } [config_js file.txt](https://github.com/HashLips/hashlips_art_engine/files/7158814/config_js.file.txt)

Did you find the solution to this issue? Im having the same problem

**Comment by samgreenwashere** [comment]
The solution for this is to install js-sha1 so just do npm install js-sha1.

**Comment by samgreenwashere** [comment]
node_module/sha1 was missing.
