### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by sororitygirlsnft** [HashLips/hashlips_art_engine#201]
TypeError: Cannot read properties of undefined (reading 'path')
    
when i try to do the final step 'node index.js" i get this error message. can someone please help? been trying to fix this for days....

**Comment by Pukimaa** [comment]
```
(node:20452) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created gif at /home/jaron/Dokumente/coding/hashlips_art_engine/build/gifs/1.gif
Created edition: 1, with DNA: 4b0bbed152c26ee763a4a9333b45e3b34551657e
/home/jaron/Dokumente/coding/hashlips_art_engine/src/main.js:190
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at /home/jaron/Dokumente/coding/hashlips_art_engine/src/main.js:190:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/jaron/Dokumente/coding/hashlips_art_engine/src/main.js:189:10)
    at /home/jaron/Dokumente/coding/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/jaron/Dokumente/coding/hashlips_art_engine/src/main.js:367:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.0.1
```
That is the full error btw

**Comment by sororitygirlsnft** [comment]
yes thats exactly what im getting!

**Comment by dhyeythumar** [comment]
Hi,
Can you add `console.log(_layer);` before return at : https://github.com/HashLips/hashlips_art_engine/blob/32120789327a6996847c35d597a9ca93fea59431/src/main.js#L188-L193
& check what you are getting.

For example you should get something like:
```
{
  name: 'Top lid',
  blend: 'source-over',
  opacity: 1,
  selectedElement: {
    id: 1,
    name: 'Low',
    filename: 'Low#20.png',
    path: 'C:\\Users\\dhyey\\Desktop\\hashlips\\hashlips_art_engine\\layers/Top lid/Low#20.png',
    weight: 20
  }
}
```

**Comment by dhyeythumar** [comment]
Check out #188

**Comment by sororitygirlsnft** [comment]
I tried and now im receiving a new error code:

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /Users/sophie/Desktop/hashlips_art_engine-main/node_modules/canvas/lib/bindings.js
- /Users/sophie/Desktop/hashlips_art_engine-main/node_modules/canvas/lib/canvas.js
- /Users/sophie/Desktop/hashlips_art_engine-main/node_modules/canvas/index.js
- /Users/sophie/Desktop/hashlips_art_engine-main/src/main.js
- /Users/sophie/Desktop/hashlips_art_engine-main/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/sophiecunningham/Desktop/hashlips_art_engine-main/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/sophie/Desktop/hashlips_art_engine-main/node_modules/canvas/lib/bindings.js',
    '/Users/sophie/Desktop/hashlips_art_engine-main/node_modules/canvas/lib/canvas.js',
    '/Users/sophie/Desktop/hashlips_art_engine-main/node_modules/canvas/index.js',
    '/Users/sophie/Desktop/hashlips_art_engine-main/src/main.js',
    '/Users/sophie/Desktop/hashlips_art_engine-main/index.js'


do you know how to fix this?

**Comment by dhyeythumar** [comment]
I guess some modules are removed, did you deleted files ?
Do `npm install`

**Comment by dhyeythumar** [comment]
**And if you have '-' in image name or folder name then remove that & try it out, hopefully that path error should be resolved.**

**Comment by sororitygirlsnft** [comment]
when i run npm install this is what i get. i have deleted and restarted the project twice, i suppose it could be different if i tried again.

Node.js v17.0.1
sophie@Sophies-MacBook-Pro hashlips_art_engine-main % npm install

up to date, audited 67 packages in 5s

6 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

**Comment by dhyeythumar** [comment]
Installation looks good, now also you are getting that new error?

**Comment by sororitygirlsnft** [comment]
i finally got it to run! the issue was that i was using the latest version of node.js (v.17) which was giving me error codes. i uninstalled everything and reinstalled using node.js v.16 and didnt run into any issues. thanks for your help :)

**Comment by Pukimaa** [comment]
I still have the same issue

**Comment by Pukimaa** [comment]
also using node v16 and no dashes in the folder names

**Comment by Pukimaa** [comment]
canvas is also installed and build

**Comment by dhyeythumar** [comment]
@Pukimaa are you using Node v17 ? If yes then uninstall it & install v16 (LTS version)

**Comment by dhyeythumar** [comment]
> Hi, Can you add `console.log(_layer);` before return at :
> 
> https://github.com/HashLips/hashlips_art_engine/blob/32120789327a6996847c35d597a9ca93fea59431/src/main.js#L188-L193
> 
> 
> & check what you are getting.
> For example you should get something like:
> 
> ```
> {
>   name: 'Top lid',
>   blend: 'source-over',
>   opacity: 1,
>   selectedElement: {
>     id: 1,
>     name: 'Low',
>     filename: 'Low#20.png',
>     path: 'C:\\Users\\dhyey\\Desktop\\hashlips\\hashlips_art_engine\\layers/Top lid/Low#20.png',
>     weight: 20
>   }
> }
> ```

@Pukimaa did you check what you are getting ?

**Comment by Pukimaa** [comment]
I got:
```
{
  name: 'body',
  blend: 'source-over',
  opacity: 1,
  selectedElement: {
    id: 0,
    name: 'standard',
    filename: 'standard.png',
    path: '/home/jaron/Dokumente/coding/pixel-penguins/layers/body/standard.png',
    weight: 1
  }
}
{
  name: 'bodycolor',
  blend: 'source-over',
  opacity: 1,
  selectedElement: {
    id: 1,
    name: 'king-penguin',
    filename: 'king-penguin*80.png',
    path: '/home/jaron/Dokumente/coding/pixel-penguins/layers/bodycolor/king-penguin*80.png',
    weight: 80
  }
}
{
  name: 'eyes',
  blend: 'source-over',
  opacity: 1,
  selectedElement: undefined
}
{
  name: 'hat',
  blend: 'source-over',
  opacity: 1,
  selectedElement: undefined
}
{
  name: 'arms',
  blend: 'source-over',
  opacity: 1,
  selectedElement: {
    id: 0,
    name: 'kowalski',
    filename: 'kowalski*1.png',
    path: '/home/jaron/Dokumente/coding/pixel-penguins/layers/arms/kowalski*1.png',
    weight: 1
  }
}
```

**Comment by Pukimaa** [comment]
So for some reason *hat* and *eyes* paths are undefined even though the folders exist
