### ISSUE TITLE
Separate traits from image

### ISSUE THREAD

**Issue by mmintel** [HashLips/hashlips_art_engine#21]
Hi! Currently the traits are connected to the image. However though this connection might not always make sense: let's say your image is too complex so that you need to combine layers, e.g. lip color and mouth style. Depending on the shape of the mouth your color layer must be adapted. Now you want traits like `mouth: excited` and `lips: red`. Would probably be an idea to place a json file next to the PNG and grab that instead of the file name.

**Comment by HashLips** [comment]
Yea that is a good idea, it just makes it a bit more complex for users who don't really know that much about code. I the purpose of this is to make it as simple for the user. Let me think of a nice way we can include that.
