### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by loosebucks** [HashLips/hashlips_art_engine#214]
i've tried removing special characters from the layers, moving the files to my desktop, deleting and downloading the folder again almost 10 times now and still keep getting this error, i dont know what i am doing wrong.

**Comment by loosebucks** [comment]
So turns out some of the files in the layers folders were corrupted or something so i just had to replace them, easy fix if you know what it is lmaoo

**Comment by Jnksg** [comment]
How you find the corrupted files please help asap <3
