### ISSUE TITLE
Have problem on node index.js unexpected token '.'

### ISSUE THREAD

**Issue by ignatiusCG** [HashLips/hashlips_art_engine#222]
![gambar](https://user-images.githubusercontent.com/81274274/140630257-1219ad98-9019-4904-ad81-bedc6288aaf6.png)

**Comment by ignatiusCG** [comment]
![gambar](https://user-images.githubusercontent.com/81274274/140630593-e7e24cf9-31fa-4646-b4ff-00553a20e8b1.png)

So i re-install Node JS with new version but still get issue

**Comment by dhyeythumar** [comment]
**Use LTS version of Node.js (v16.13.0)**

**Comment by stricklandrbls** [comment]
You need to update your NodeJS version most likely. On Windows I'm not quite sure if it's as easy as just downloading the new installer and running it but on Linux you can download the tar, extract to /usr/local/lib/nodejs then in your ~/.profile you need to export the path to point to the 'node' binary in /usr/locla/lib/nodejs/bin/

**Comment by dhyeythumar** [comment]
Can easily install different Node.js version using [**nvm**](https://www.sitepoint.com/quick-tip-multiple-versions-node-nvm/).

**Comment by ignatiusCG** [comment]
The issue has been resolved, I don't know why some versions of Node JS don't support it.
So I tried another version and no problem with the script so far.
so it's just a version problem. thanks all for the response
