### ISSUE TITLE
Having issue running node index.js

### ISSUE THREAD

**Issue by asu10170** [HashLips/hashlips_art_engine#224]
I deleted all the old file names (Eyeball, Iris etc...) and replaced them with my own, but when I run node index.js it still searches for them
![Screenshot 2021-11-06 235546](https://user-images.githubusercontent.com/93851742/140631763-7033339d-fab6-4189-ac3d-0b894bace442.jpg)
@m.

How do I fix this?

**Comment by dhyeythumar** [comment]
**Possibly duplicate of #191 check it out**

**Comment by asu10170** [comment]
worked great thanks!
