### ISSUE TITLE
Rarity change not working properly

### ISSUE THREAD

**Issue by arrbrk1** [HashLips/hashlips_art_engine#225]
I have a layer of base images which should be rendered everytime it generates a new image and I'm changing the file names to "Base1#100.png, Base2#100.png and Base3#100.png" expecting to have it all the time, but it's not working...

**Comment by LKYSE7EN** [comment]
Hi arrbrk1,

As explained in the HashLips YouTube Video - How to create an NFT collection - Ultimate guide. (link below)

The rarity weight is not a scale of #1 (1% will include) #100 (100% will include).

The total weight for all values in a layer folder (for example /background/ ... background1#100 background2#50 background #10) is used to calculate a total rarity weight.

If you're able to provide a bit more information on what you're trying to achieve, there may be another way to reach the desired outcome.

From my understanding, using your example above Base1#100.png, Base2#100png and Base3#100.png if you want these three included every time, you could merge them into one image (Base#100.png) and then create a folder called /base/ to save only that file in and in the config.js have it above the /background/ layer so it always appears.

layersOrder: [
      { name: "Background" },
      { name: "Base" },
      { name: "Next Layer" },
      { name: "Another Layer" },
    ],

Please watch the YouTube tutorial - it has a significant amount of useful information and will give you a greater understanding of not only how you can use the tools but how they are actually working.

I hope this helps.

Cheers!

(Full Video) - https://youtu.be/fzH7Gjadmj0
(Start @ Rarities Explained) - https://youtu.be/fzH7Gjadmj0?t=1803

**Comment by arrbrk1** [comment]
Thanks, It solved my problem.
