### ISSUE TITLE
Random layer configurations

### ISSUE THREAD

**Issue by Grummie91** [HashLips/hashlips_art_engine#23]
Hey HashLips i rly like your projekt great work!
I just have a little problem working on a collection with multiple colorsets for my characters. I cant mix colors so i have more layer configurations set up but the problem is they are not random. 1-100 red 101-200 blue ....
i tried to mess around with your code to implement a random number witch chose the next layerconfiguration but i dont get it

`const layerConfigurationsblue = [
  { 
    layersOrder: [
      { name: "Background" },
      { name: "Eyeball" },
      { name: "Eye color" },
      { name: "Iris" },
      { name: "Shine" },
      { name: "Top lid" },
    ],
  },  
];
const layerConfigurationsred = [
  {    
    layersOrder: [
      { name: "Background" },
      { name: "Eyeball" },
      { name: "Eye color" },
      { name: "Iris" },
      { name: "Shine" },
      { name: "Bottom lid" },      
    ],
  },  
];` 
and in main 
`
const startCreating = async () => {
  let layerConfigIndex = 0;
  let editionCount = 1;
  let failedCount = 0;
  while (layerConfigIndex < 10) {
    
    let random = Math.floor(Math.random() * 2);
   
    console.log("++++++++random number++++++++ : ",random)
    console.log("++++++++layerconfigindex++++++++ : ",layerConfigIndex)
    
    if (random = 0) {
      
      const layers = layersSetup(
      layerConfigurationsred[layerConfigIndex].layersOrder
     );     
      let newDna = createDna(layers);
      if (isDnaUnique(dnaList, newDna)) {
        let results = constructLayerToDna(newDna, layers);
        let loadedElements = [];
        results.forEach((layer) => {
          loadedElements.push(loadLayerImg(layer));
        });
        await Promise.all(loadedElements).then((renderObjectArray) => {
          ctx.clearRect(0, 0, format.width, format.height);
          if (background.generate) {
            drawBackground();
          }
          renderObjectArray.forEach((renderObject) => {
            drawElement(renderObject);
          });
          saveImage(editionCount);
          addMetadata(newDna, editionCount);
          saveMetaDataSingleFile(editionCount);
          console.log(
            `Created edition: ${editionCount}, with DNA: ${sha1(
              newDna.join("")
            )}`
          );
        });
        dnaList.push(newDna);
        editionCount++;
      } else {
        console.log("DNA exists!");
        failedCount++;
        if (failedCount >= uniqueDnaTorrance) {
          console.log(
            `You need more layers or elements to grow your edition to ${layerConfigurationsred[layerConfigIndex].growEditionSizeTo} artworks!`
          );
          process.exit();
        }
      }     
    } else {
      const layers = layersSetup(
        layerConfigurationsblue[layerConfigIndex].layersOrder
       );       
        let newDna = createDna(layers);
        if (isDnaUnique(dnaList, newDna)) {
          let results = constructLayerToDna(newDna, layers);
          let loadedElements = [];  
          results.forEach((layer) => {
            loadedElements.push(loadLayerImg(layer));
          });  
          await Promise.all(loadedElements).then((renderObjectArray) => {
            ctx.clearRect(0, 0, format.width, format.height);
            if (background.generate) {
              drawBackground();
            }
            renderObjectArray.forEach((renderObject) => {
              drawElement(renderObject);
            });
            saveImage(editionCount);
            addMetadata(newDna, editionCount);
            saveMetaDataSingleFile(editionCount);
            console.log(
              `Created edition: ${editionCount}, with DNA: ${sha1(
                newDna.join("")
              )}`
            );
          });
          dnaList.push(newDna);
          editionCount++;
        } else {
          console.log("DNA exists!");
          failedCount++;
          if (failedCount >= uniqueDnaTorrance) {
            console.log(
              `You need more layers or elements to grow your edition to ${layerConfigurationsblue[layerConfigIndex].growEditionSizeTo} artworks!`
            );
            process.exit();
          }
        }            
    }
    layerConfigIndex++;    
 }   
};`

it creates only one img 
im am a total noob in programming but i`m trying xD

**Comment by OrionRuan** [comment]
I created something that will do exactly what you want!

**Comment by Grummie91** [comment]
thank you so much works great! GJ

**Comment by gewure** [comment]
> I created something that will do exactly what you want!
> 
> https://github.com/OrionRuan/orion_art_engine

I tried to run your fork but there are serious issues, you seem to have 2 mergeconflicts open in the latest deployment in

utils/createPreviewCollage.js
utils/regenerateMetata.js

...and accepting latest changes i then get something like this:

`Error: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/lib/librt.so.1)`

if you could help there @OrionDevStar that would be nice!
