### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error:Unsupported image type

### ISSUE THREAD

**Issue by fonzi69** [HashLips/hashlips_art_engine#236]
Hey guy, Can anyone help me figure out what the problem is. After I try to create 100 Images, It usually stops half way through or less and gives me this error " UnhandledPromiseRejectionWarning: Error:Unsupported image type" , Anyone have any suggestions? Im new to the scene so Im still learning. Thank
![hash](https://user-images.githubusercontent.com/94034293/141056022-545837b2-1a70-4e0e-9d15-867e37cc8271.png)
s!

**Comment by MaciekBaron** [comment]
Since the error message is mentioning unsupported image types: what images are you using?

**Comment by chrisninetyone** [comment]
Issue #231 has more info on this
