### ISSUE TITLE
Rarity weights: how to give a weight to "NO ATTRIBUTE? (e.g  "no t-shirt" 50%, black 25%, red 25%)

### ISSUE THREAD

**Issue by purpleglow** [HashLips/hashlips_art_engine#237]
I'm having a hard time understanding how to give weight to the absence of an attribute. Say I have 2 t-shirts: Black and Red, and I want to have approximately 
- 50% no shirt at all
- 25% black shirt
- 25% red shirt

I read that if the numbers add to 100, then weights will roughly represent percentages. My 2 files are Black#25.png, Red#25.png, but how do I specify the "no shirt" at 50%? If I leave it out the engine creates 50% black, 50% red. (argh!)

Thank you.

**Comment by fonzi69** [comment]
create a new photoshop file thats just blank, and just tittle it shirtless.png, thats what i do.

**Comment by dstuecken** [comment]
You would name your no shirt "#50.png", then the trait is not going to get a name at a 50% chance.

**Comment by edenheijer** [comment]
alternatively, you could add an additional layer configuration omitting the layer in config.js, such that you would grow editions to half of your desired amount without a shirt

**Comment by purpleglow** [comment]
Thank you so much for the detailed replies!
