### ISSUE TITLE
IPFS Upload Utility

### ISSUE THREAD

**Issue by SakuruNakamoto** [HashLips/hashlips_art_engine#25]
Would it be possible to develop an IPFS upload utility utilizing something like the following:

- nft.storage (https://nft.storage) OR
- pinata.cloud

I am working on building this but would be nice to have this in the main repository:

1. Install dotenv & nft.storage
`npm i dotenv`
`npm i nft.storage`

2. Update code in utility - "uploadNFT.js"
`require('dotenv').config()`
`const { NFTStorage, Blob, File } = require('nft.storage')`

3. Make sure to add .env in the .gitignore file and add NFTSTORAGE_API_KEY to file.

4. Create an upload utility function (Possibly modify the metadata upload to loop through the individual files and upload them one at a time).
```
const uploadNFT = async () => {
    const client = new NFTStorage({ token: process.env.NFTSTORAGE_API_KEY })
    const metadata = await client.store({
        name: 'NFT.Storage Test',
        description: "Testing of the initial upload of an NFT to NFT.Storage",
        image: new File([await fs.promises.readFile('<filename>.png')], '<filename>.png', { type: 'image/png',}),
        external_url: "https://<url to external site>",
        attributes: [
          {
            "trait_type": "Trait 1", 
            "value": "Value 1"
          }, 
          {
              "trait_type": "Trait 2", 
              "value": "Value 2"
          }
        ]
    })
    console.log(metadata.url)
}
```

5. Log each upload to a Log File to allow you to go back and have a list of all of the IPFS URLS for the metadata and images.

**Comment by jasan-s** [comment]
@SakuruNakamoto  open a PR

**Comment by jasan-s** [comment]
I already have function created that uploads to ipfs using pinanta cloud, I may need to spend some time to figure out where to insert it. I may look at it and submit PR this weekend
