### ISSUE TITLE
Only partial generation happening.

### ISSUE THREAD

**Issue by triiq** [HashLips/hashlips_art_engine#252]
Hello, I love your content and this program has changed the game for me. I've used it successfully multiple times but am running into an issue this time around. It will only generate a few images then fail.

PS C:\Users\zbart\Desktop\hashlips_art_engine> npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:7876) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 0, with DNA: 241cbbe260d076c8df14a3aa881a4637105d7b5e
Created edition: 1, with DNA: ff9d15163e0980c3ccc5fa4704e3decae4995fb1
C:\Users\zbart\Desktop\hashlips_art_engine\src\main.js:181
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\zbart\Desktop\hashlips_art_engine\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\zbart\Desktop\hashlips_art_engine\src\main.js:180:10)
    at C:\Users\zbart\Desktop\hashlips_art_engine\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\zbart\Desktop\hashlips_art_engine\src\main.js:360:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by lewayotte** [comment]
make sure you remove any dashes in your filenames...
