### ISSUE TITLE
Weighted rarity does not represent the actual output generated

### ISSUE THREAD

**Issue by barslz** [HashLips/hashlips_art_engine#253]
As what hashlips have already explained on his tutorial, which i recommend we all watched it..its full of usefull information. 
The trouble that im having is, with the weighted system, 
lets say: i have 4 attributes, with each attribute have 3 traits, and one of the color attribute consist of traits such us Blue#1, Green#1, Red#1. 
Maximum generated artwork would be 3x3x3x3 = 81. 
The problem start when im changing the weighted for the color for each traits. Blue#10, Green#40, Red#50. 
With the hope of the blue would generated only 10% x 81 = 8. 
But i know that if 81 is the maximum generated with the same weighted for all traits, when we start applying weighted for traits, the maximum generated should be less then 81.
First question is how to calculate the maximum generated artwork after we applying weighted. And i find the weighted that we put even if we put the total weighted would be 100%, if we check in rarity, the occurence will be different with the weighted. Which mean weighted that we put for rarity does not equal to the occurence with the artwork generated. 
Second question is how do we calculate a accurate weighted so that the occurence will also be the same after generated?

**Comment by cdric** [comment]
Yeah I don't have the answer for this and I'm following this as I'm interested to know more!

**Comment by edenheijer** [comment]
I authored a commit that merged into the dev branch today that more or less addresses your issue. Basically, it changes the output of the 'rarity' functionality by expressing it as "[amount of occurrences] in [total amount of editions] ([chance in percentage])". The readme has been updated to reflect this change.

Hope this helps

**Comment by barslz** [comment]
Thank you Edenheijer, after looking on your branch..i realized now that weight equal to chance, its not the same with the how percentage calculation works. I was on the impression that weight equal to percentage before. You've been a great help, thank you sir!
