### ISSUE TITLE
How to set art_engine to start pngs and jsons at 0 and grow from that?

### ISSUE THREAD

**Issue by bishop1701** [HashLips/hashlips_art_engine#285]
Same as title. Need to create a large amount of units.
Working alongside Metaplex, and therefore, need it all to start from zero and grow from there.

Instead it starts at
1.png
1.json

etc..

Also, the json file wont add 'creators' which causes a massive amount of problems.

Thanks for any helpers.

**Comment by cdric** [comment]
Set the network to sol! 

const network = NETWORK.sol;

**Comment by imkane** [comment]
@cdric but why? We want to start at 0 too, but we're using ethereum network.

**Comment by cdric** [comment]
Well then this need to be re-open so the Author can fix the behavior. I'm not familiar with ETH network when it come to the files format you need to upload you assets...

**Comment by imkane** [comment]
> Well then this need to be re-open so the Author can fix the behavior. I'm not familiar with ETH network when it come to the files format you need to upload you assets...

No worries, I opened a new issue :slightly_smiling_face:
