### ISSUE TITLE
You really need to add a rarity feature for layers!

### ISSUE THREAD

**Issue by kosy78** [HashLips/hashlips_art_engine#3]

**Comment by HashLips** [comment]
It is coming out tonight :)

**Comment by Kresoart** [comment]
Did you find out how to do it

**Comment by bolshoytoster** [comment]
@Kresoart https://github.com/HashLips/hashlips_art_engine#usage-%E2%84%B9%EF%B8%8F

**Comment by Kresoart** [comment]
@bolshoytoster 
Sorry but i cant seem to find how i can make Like the actual layer, not a specific asset, glasses only be used 20% of time do you know how to do that or is it maybe written in the link u sent me

**Comment by bolshoytoster** [comment]
@Kresoart you could try having a blank image with an 80% chance of I think [nftchef's repo](https://github.com/nftchef/art-engine) might help you.
