### ISSUE TITLE
Iam not able to npm run generate

### ISSUE THREAD

**Issue by paarthpathak** [HashLips/hashlips_art_engine#304]
Iam trying to generate with my own layers 

I first deleted the "eyes" layers that came with the  .zip file 

and then pasted my layers in the "Layers" folder 

also changed the { name: " " },
I saved the changes 

but still its giving these errors

const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\patha\Downloads\hashlips_art_engine-1.1.2_patch_v1\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\patha\Downloads\hashlips_art_engine-1.1.2_patch_v1\src\main.js:180:10)
    at C:\Users\patha\Downloads\hashlips_art_engine-1.1.2_patch_v1\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\patha\Downloads\hashlips_art_engine-1.1.2_patch_v1\src\main.js:360:17)
    at C:\Users\patha\Downloads\hashlips_art_engine-1.1.2_patch_v1\index.js:6:3
    at Object.<anonymous> (C:\Users\patha\Downloads\hashlips_art_engine-1.1.2_patch_v1\index.js:7:3)

**Comment by Reiyaku** [comment]
I tried removing most of my layers and just put 2 or 3 layers and the code is running well. Still looking for the problem too. Is yours fixed?

**Comment by paarthpathak** [comment]
Yes I had not renamed my layers properly

it should be name#somenumber

the # is important
