### ISSUE TITLE
generating count stops at 5

### ISSUE THREAD

**Issue by ericmr1234** [HashLips/hashlips_art_engine#309]
so i have been trying to generate my nft, and i setted the number of generated images to 20.

but at running it, it only generates 5. any idea how to fix it?

thanks

**Comment by taknii** [comment]
same problem

**Comment by FrankLio13213** [comment]
？How to fix it？

**Comment by FrankLio13213** [comment]
> so i have been trying to generate my nft, and i setted the number of generated images to 20.
> 
> but at running it, it only generates 5. any idea how to fix it?
> 
> thanks

Hi，How to fix it？
