### ISSUE TITLE
Glitch noise when i generate images

### ISSUE THREAD

**Issue by janunezconde** [HashLips/hashlips_art_engine#317]
I have high quality PNG images (2048 x 2048 png files with transparencies) occupying about 1mb each. But when I generate the images, they all appear with a kind of "glitch", with a noise like an old television. The composition seems to have been done well but the image quality is totally ruined, you can only hardly see the outlines. I have not seen it in the documentation but maybe the files need to have a specific quality and I do not know it

![2021-11-29_16h52_52](https://user-images.githubusercontent.com/94466741/143899864-9a28381d-34c7-4693-ae67-e8ec776919cb.png)

**Comment by lloydcarroll** [comment]
You closed? What was the fix? I have the same issue @janunezconde
