### ISSUE TITLE
Layers generating in the same size. Can someone help me with this?

### ISSUE THREAD

**Issue by eskik3** [HashLips/hashlips_art_engine#344]
![1](https://user-images.githubusercontent.com/1511630/144746097-c92a93b8-8200-4cf3-a2d2-e763dd830c38.png)

**Comment by itlackey** [comment]
Just making sure, are all of your layer images the same dimensions?

**Comment by klajdibiba** [comment]
> Just making sure, are all of your layer images the same dimensions?

No, images are on different width and height. 

EX: eyes are 969:64px 3 and mouth 761:448px .

**Comment by eskik3** [comment]
Figured it out, just uncheck "Trim Layers" option in photoshop when exporting layers as files.

**Comment by mroldchurch** [comment]
same issue here. the png files look ok. they have their own size. but when generating, this happens:
![image](https://user-images.githubusercontent.com/96824922/147660175-249e631c-90ce-45fc-8da7-a9fefffc51a5.png)
