### ISSUE TITLE
generator cant find the files path

### ISSUE THREAD

**Issue by sultan-710** [HashLips/hashlips_art_engine#348]
hi there, im almost 2days busy with this and tryin my best to fix this by my self but no luck :< . I hope u can fix it asap.

- Image downbelow

`PS C:\Users\Sultan Omari\Downloads\hashlips_art_engin> node index.js
(node:24664) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\Sultan Omari\Downloads\hashlips_art_engin\src\main.js:181
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\Sultan Omari\Downloads\hashlips_art_engin\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Sultan Omari\Downloads\hashlips_art_engin\src\main.js:180:10)
    at C:\Users\Sultan Omari\Downloads\hashlips_art_engin\src\main.js:360:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Sultan Omari\Downloads\hashlips_art_engin\src\main.js:359:17)
    at C:\Users\Sultan Omari\Downloads\hashlips_art_engin\index.js:6:3
    at Object.<anonymous> (C:\Users\Sultan Omari\Downloads\hashlips_art_engin\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)`
PS C:\Users\Sultan Omari\Downloads\hashlips_art_engin>

**Comment by Tahakh57** [comment]
download 1.03 its stable this new version is not

**Comment by Lenarp** [comment]
1.03 Visual Studio? I am also having this issue! When I ran it earlier with a simpler test (fewer layers), it ran fine. Now, I am getting this same path error. I tried it on the 1.03 Visual Studio but it still came up with the same error. Thank you!

**Comment by Lenarp** [comment]
figured it out from another thread!

remove any symbol from names of layers
for example bg-black becomes bgblack

**Comment by luisgarcia4511** [comment]
> figured it out from another thread!
> 
> remove any symbol from names of layers for example bg-black becomes bgblack

I don’t have any symbols on mine  …. It’s doing the same

**Comment by sultan-710** [comment]
Hi everyone, I found the solution. U have to rename all the layers without numbers before the #  eg: whiteBG#10.png     don't put any number before the #. Now the engine works fine for me. Thank you.

**Comment by Gromm21** [comment]
I've done that but i'm still getting the same error

**Comment by sultan-710** [comment]
> I've done that but i'm still getting the same error
