### ISSUE TITLE
NPM Install for installing dependencies failing at canvas

### ISSUE THREAD

**Issue by amingst** [HashLips/hashlips_art_engine#36]
Not sure what else to say about this. I'll just say that when running npm install in the project root, the following error message pops up.

$ npm install
npm ERR! code 1
npm ERR! path C:\Users\path_to_user\hashlips_art_engine-main\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! '"node"' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\path_to_user\AppData\Local\npm-cache\_logs\2021-09-20T00_13_02_796Z-debug.log

debug files:
[2021-09-20T00_13_02_796Z-debug.log](https://github.com/HashLips/hashlips_art_engine/files/7193170/2021-09-20T00_13_02_796Z-debug.log)

**Comment by bkhoward2001** [comment]
having same issue

**Comment by ImpliedThreat** [comment]
Having the same issue as above.

**Comment by Chante6412** [comment]
Same issue here. Not sure what I'm missing

**Comment by bengalsgrowl** [comment]
try following these steps maybe?
you might need to update Python
https://github.com/nodejs/node-gyp#installation

**Comment by gguelber** [comment]
Same issue here, i wasnt having these errors in the previous version, but now i cant install canvas anymore. Any clue?

**Comment by 0x8D85** [comment]
Make sure you have the right dependencies installed for compiling canvas package. 

https://www.npmjs.com/package/canvas#compiling

**Comment by OPPYnft** [comment]
I was having this same issue and found out that if I installed node.js LTS version with chocolatey (the option the installer gives you) it will install the dependencies. You still need to then `yarn add all` in the terminal. Hope this helps

**Comment by ImpliedThreat** [comment]
> I was having this same issue and found out that if I installed node.js LTS version with chocolatey (the option the installer gives you) it will install the dependencies. You still need to then `yarn add all` in the terminal. Hope this helps

I have node.js LTS installed with chocolatey, and still, the issue persists. I had no issues installing the dependencies in any other version of HashLips generative art projects, only the Art-Engine. I was able to run the code by copying my node_modules folder from a previously installed HashLips project and pasting it in the root directory of the Art-Engine project, but this is not a proper fix for the issue of being unable to install dependencies.

**Comment by bengalsgrowl** [comment]
Think you can email me that original hash lips data? Would save me as well.
bengalsgrowl@gmail.com

**Comment by moonriver860** [comment]
Having the same issue as above. How to use the above adding package-lock.json @mexitek

**Comment by mexitek** [comment]
This has been a weird issue. Some ppl on discord have fixed it by installing canvas manually: `npm install canvas` some ppl have had to downgrade their existing canvas `npm uninstall canvas && npm install canvas@2.7.0`. For others running `npm install -E` with this `package-lock.json` has been enough.

Not sure if that answers your question.

**Comment by bengalsgrowl** [comment]
Best option is to use the new repo they have posted and forget this one altogether
