### ISSUE TITLE
DNA exists! msg while running art engine

### ISSUE THREAD

**Issue by Poorvak33** [HashLips/hashlips_art_engine#376]
While generating art, what does 'DNA exists!' line means under some nfts?

**Comment by luisgarcia4511** [comment]
You don’t have enough layers to be able to create the amount of different nfts you choose to create

**Comment by psavva** [comment]
@Poorvak33   It's very possible that the exact same image was generated with the exact same layers.
This means the specific image it tried to generate happened to be exactly the same as another (randomness).
The output basically says, "I found another exact copy of this image.  Throw it away, and try again".

So this is nothing to worry about, and exepcted.

Suggest to close this issue.
