### ISSUE TITLE
ISSUE - libpixman-1.0.40.0.dylib

### ISSUE THREAD

**Issue by jpaezsa** [HashLips/hashlips_art_engine#39]
Hello Guys

I have an issue w/ image size output, if i change the starter 512px to any mayor number ej: 513px or 2500px have and error!…

Do you have an idea, how fix it?

In advanced, tks to all!

This are de error: libpixman-1.0.40.0.dylib (which was built for Mac OS X 10.15)

```
➜  hashlips_art_engine-1.0.0 node index.js
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/…/Desktop/hashlips_art_engine-1.0.0/node_modules/canvas/build/Release/libpixman-1.0.40.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/…/Desktop/hashlips_art_engine-1.0.0/node_modules/canvas/build/Release/libpixman-1.0.40.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

[1]    1906 abort      node index.js
```

![image](https://user-images.githubusercontent.com/1481416/134060156-240a3220-354c-4e9e-bae2-aa8ecc1384ca.png)

**Comment by jpaezsa** [comment]
Hello @HashLips Daniel!…

I fixed the problem with the size, upgrading the size of the images itself.

But if tray to apply filters, the problem back again and crash!

Any idea or hint? 
Note: I run macOS 10.13.6 - can't upgrade my OS  :( 

![image](https://user-images.githubusercontent.com/1481416/134094984-50bb1a85-75ae-4164-95b0-49307bcf1af6.png)

**Comment by adamnooh** [comment]
Hey can u please help me with all files to open them and to find them if I
provide u more info please let me know
