### ISSUE TITLE
solana - proper formatting of image attribute value in json file

### ISSUE THREAD

**Issue by Bobbytables134** [HashLips/hashlips_art_engine#402]
When generating the json files, for an image with a name of image0.png, what should the value of the image attribute be set to so that it displays properly when the images/json are uploaded to arweave?  

Currently,  each individual json file contains `"image": "image.png"` when i do `npm run build` which I believe could be causing my issue. 

When minting files created using this repo, the images are displaying as broken when i view them in my wallet or solscan. 

Thanks!

**Comment by summerplaybook** [comment]
Also checking in on this. It looks like it should no longer be 'image.png' but '0.png' for example

**Comment by summerplaybook** [comment]
see this pr - should fix it: https://github.com/HashLips/hashlips_art_engine/pull/401

**Comment by Bobbytables134** [comment]
Thanks!
