### ISSUE TITLE
Commands won't work: npm run and node index.js

### ISSUE THREAD

**Issue by gigiflower** [HashLips/hashlips_art_engine#408]
Hello! So I tried two command, which both won't work, why?
I have a M1 iMac, downloaded Node.js v16.13.1, and using editor VSC

**Command npm run build**

x new test % npm run build
npm ERR! Missing script: "build"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     x/.npm/_logs/2021-12-24T13_44_26_878Z-debug.log

**Command node index.js**

x new test % node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'x/Desktop/x/test dec 22/new test/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by orian3737** [comment]
have you installed all requisites node.js, yarn ect. try npm install

**Comment by gigiflower** [comment]
thanks! It works with node v14
