### ISSUE TITLE
HashLips stopped working.

### ISSUE THREAD

**Issue by KeefeOverby** [HashLips/hashlips_art_engine#423]
It was working fine, then it stopped working all of a sudden. Error code below. 

DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead.

https://github.com/HashLips/hashlips_art_engine/blob/304fcfc643c29e0943e4dcc38a751752607de1ad/src/main.js#L267

**Comment by Intelligencybar** [comment]
Same problem. Please help

**Comment by KeefeOverby** [comment]
> Same problem. Please help

I just saved my important layers and other personal files and info, deleted Hashlips engine, then started fresh with a new copy of hashlips, new node_models, new copy of node.js, new everything! You might not need to go that far, just try deleting node_modules and npm install again! Deprecation warnings are usually a dependency issue so for me right now it's nearly impossible to quickly find and fix these warnings by changing code, because that will for me at this moment in my learning journey likely just mess up more dependencies. Hopefully this helps if not I am sorry I am just a noob at this!  😊
