### ISSUE TITLE
Update Base Uri does not work

### ISSUE THREAD

**Issue by satok111** [HashLips/hashlips_art_engine#444]
When I get to the step of updating the baseuri, the code can be executed wonderfully and it is displayed that the base uri has been updated, but when I open the json files, the basuri was not updated.

I'm using the latest version, but it doesn't work with the others either...

**Comment by encryptedphysarum** [comment]
I have the same issue. Did you discover a soulution?

**Comment by satok111** [comment]
No not yet, until now I was just using an earlier version (1.1.0).
