### ISSUE TITLE
EEXIST: file already exists

### ISSUE THREAD

**Issue by b3at1** [HashLips/hashlips_art_engine#445]
this is the error I am getting

  errno: -4075,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: 'C:\\Users\\sambe\\hashlips_art_engine-main1\\hashlips_art_engine-main/build'

which occurs when I run "node index.js" in terminal "hashlips_art_engine-main"

I have no idea why this happens but I've try auditing and reinstalling npm, and nothing has worked. 
This only happens after the first build, which has worked fine (I have had to completely reinstall hashlips multiple times in the past and I'm sick of fixing the issue that way).

any help is appreciated

**Comment by bujitsu** [comment]
i have the same issue. have you found a solution?

**Comment by bujitsu** [comment]
As a workaround just delete the build folder from your project and run again index.js if you modified something into the config.js file

**Comment by ElDla** [comment]
Is there any way to fix this without deleting the build folder?

**Comment by bolshoytoster** [comment]
@ElDla I've fixed this on [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
