### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Intelligencybar** [HashLips/hashlips_art_engine#454]
<img width="952" alt="Снимок экрана 2022-01-04 221758" src="https://user-images.githubusercontent.com/75547234/148112197-d179718b-13e4-4f24-8451-a8be4f3a76db.png">

**Comment by laygir** [comment]
Do you have a forked repo to see your version of the source code?
It seems to be complaining about `DNA_DELIMITER` but hard to be 100% sure without seeing your source code just in case there wa any modification.

**Comment by Intelligencybar** [comment]
> Do you have a forked repo to see your version of the source code? It seems to be complaining about `DNA_DELIMITER` but hard to be 100% sure without seeing your source code just in case there wa any modification.

Thank you.  The problem has already been resolved
