### ISSUE TITLE
Include the desired trait name into the NFT name?

### ISSUE THREAD

**Issue by burmestr** [HashLips/hashlips_art_engine#47]
Let's say you generate some characters. Right now the naming is primitive, it's just number. How can you include the desired trait name into the NFT name? so it could be "NFT 450 Dog with umbrella"(where Dog and umbrella are trait filenames) and not just "NFT 450"?

**Comment by scco** [comment]
thought the same. maybe even in combination with #42
to give avatars random names .

**Comment by burmestr** [comment]
yes, the order number may remain, but really need an option to transfer the trait or multiple traits names into the final result name
