### ISSUE TITLE
Nothing happen when run index.js

### ISSUE THREAD

**Issue by amirmaleki33** [HashLips/hashlips_art_engine#494]
Hi,there.
I have a little issue:
Whenever I type and run the "node index.js" nothin happens and that box opens and says which program do you like to open with?
Even when I choose visual studio code, nothing happens.
Am I missing something in here?
(All yarn dependency installed!)
![Untitled](https://user-images.githubusercontent.com/97390614/148683191-a9148914-922b-4a6e-99ee-2a5894a90815.png)

**Comment by amirmaleki33** [comment]
Anybody?!

**Comment by psavva** [comment]
`npm run build`

**Comment by amirmaleki33** [comment]
Found the solution!
Thank you
