### ISSUE TITLE
* in filenames for PNGs breaks on PC

### ISSUE THREAD

**Issue by redmeadow** [HashLips/hashlips_art_engine#5]
Those are not allowed characters in a filename on a PC

**Comment by thelandofrandom** [comment]
I ran into this same issue as well

**Comment by Ramirotorrese** [comment]
Same

**Comment by bkhoward2001** [comment]
yes will not allow

**Comment by Ramirotorrese** [comment]
I found a way , Change line 33 and 42
replace the * for %. You will need to use % at the end of your file name 
From:  var nameWithoutWeight = nameWithoutExtension.split(/[* ]+/).shift();
To:      var nameWithoutWeight = nameWithoutExtension.split(/[% ]+/).shift();

**Comment by HashLips** [comment]
Fixed in v1.0.2
