### ISSUE TITLE
Randomize between "editions"?

### ISSUE THREAD

**Issue by peterbaker** [HashLips/hashlips_art_engine#50]
Is it possible to fully shuffle the `layerConfigurations` array, after creating a number of edition arrays?

For instance, if I have a set of 300, with layer configs for 100 at a time, can I generate them without doing the first 100 based solely on the first layerConfiguration[] array item?

Basically, I want to have some number of editions, and all the layer options that come with them, but make sure they're completely random on export, rather than in chunks.

**Comment by HashLips** [comment]
Yes, this will be an update in v1.0.6
