### ISSUE TITLE
file path error

### ISSUE THREAD

**Issue by bengalsgrowl** [HashLips/hashlips_art_engine#51]
When running npm run build i received a file path error.
It looks like it is trying to search for a file path to "layer/eyeball" and i am not using an eyeball layer.

![Capture](https://user-images.githubusercontent.com/91103242/134435356-5fdedf1d-e2be-49e8-bab8-bbb99697b8d0.PNG)

**Comment by bengalsgrowl** [comment]
ah just had to save the changes to the code i made to the layers in config.js 
ez fix
worked perfectly

**Comment by burmestr** [comment]
then close this f-n "issue"
