### ISSUE TITLE
Randomizing - How prevent repeat combinations?

### ISSUE THREAD

**Issue by jpaezsa** [HashLips/hashlips_art_engine#52]
Hello Guys!…

Anyone knows when combinations start to repeat?..
— I know this are a variable, depends on the numbers of layers and the combinations inside each layer.

How to prevent programmatically repeat combinations?

**Comment by HashLips** [comment]
It does not repeat, each one is unique even if it says DNA EXIST is creating a new one until it's unique.

**Comment by jpaezsa** [comment]
Many tks 4 all @HashLips Daniel!…
