### ISSUE TITLE
Make animated videos with soundtracks NFT collection

### ISSUE THREAD

**Issue by Ahmeddh** [HashLips/hashlips_art_engine#54]
Did anyone thought about how we could add the support into accepting different formats other than the png in this project? For example, I want to have videos in one layer and soundtracks on the other and I want to be able to make a different version of the videos generated by the code (the same way images work now) and mix those videos randomly with the soundtrack layer.

I understand this might be a futuristic milestone or even out of the scope of this repo, but if anyone can elaborate or give me some directors I'll be thankful

**Comment by MaciekBaron** [comment]
You can achieve this with `ffmpeg`:

    ffmpeg -i video.mkv -i audio.mp3 -map 0 -map 1:a -c:v copy -shortest output.mkv
    
 Where `video.mkv` is the video file and `audio.mp3` is the audio file. You can then prepare a simple bash script to combine random videos with random audio files.

However, if you want to combine different video layers, then obviously you need some sort of alpha channel information, or a chroma key, which requires a lot more preparation on the video file side (you'd have to use the correct chroma key in your video files and then provide it to the script).

You can then use the `colorkey` filter:

    ffmpeg -i video.mkv -i  overlay-video.mkv -filter_complex '[1:v]colorkey=0xYOUR_COLOR:YOUR_SIMILARITY_VALUE:YOUR_BLEND_VALUE[ckout];[0:v][ckout]overlay[out]' -map '[out]' output.mkv

So by combining the above you should be able to achieve what you want.

**Comment by tunjimesh** [comment]
Hello, @MaciekBaron @HashLips 

Is there a way to combine multiple animated GIF using the same script? The idea is to merge several animated GIF into one; resulting in an animated GIF with all the different looping sequences.

Any tip on how to get that done, please?

Thanks in advance.

TM.

**Comment by MaciekBaron** [comment]
If you mean merging GIFs sequentially there's [Gifsicle](http://www.lcdf.org/gifsicle/) that allows you to do it in the command line by simply doing:

    gifsicle 1.gif 2.gif 3.gif > merged.gif
    
 So all you need is a simple script that changes the order or the selection of the GIFs.

**Comment by tunjimesh** [comment]
Thanks, for the feedback @MaciekBaron. Appreciate it.

I meant using GIFs with alpha channels in the art engine and combining them in layers, not sequentially.

So in this case, layer 1 will be 1.gif, layer 2 will be 2.gif and so on.

So we have 1 GIF with all the different animated GIFs on different layers.

Once again, thanks for the feedback.

**Comment by MaciekBaron** [comment]
I wouldn't necessarily recommend this, as GIFs have limited colour palettes and differ in frame rates.

However, you can also use `ffmpeg` for that, you could look into the [`overlay`](https://ffmpeg.org/ffmpeg-filters.html#overlay-1) filter to overlay two source gifs on top of each other, similarly to what I did in the first example.

I think it could look something like this, although I haven't tried it:
    ffmpeg -t DURATION_HERE -i gifone.gif -i giftwo.gif -filter_complex "[1:v][ovrl];[0:v][ovrl]overlay=0:0" -vf "fps=10,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -loop 0 output.gif

It's best if you read the docs for this to get it right, but basically after `-vf` you want to use those options and set the appropriate framerate you want, and after `-filter_complex` you define your overlay.

**Comment by tunjimesh** [comment]
Sounds Great. Thanks

**Comment by PradhumnaPancholi** [comment]
I don't want videos but animated png or gifs as output. There's an issue about it https://github.com/HashLips/hashlips_art_engine/issues/461. Do you think this solution can help around it in some way?

**Comment by MaciekBaron** [comment]
@PradhumnaPancholi: `ffmpeg` supports both apng and gif output. See my comment above.
