### ISSUE TITLE
npm run generate issue

### ISSUE THREAD

**Issue by crosbypierce** [HashLips/hashlips_art_engine#557]
When I type npm run generate in the terminal it shows me some issues and I do not know why. For some reason it works before I add my files but not after. I am not a programmer and I need help. This is what it says...

<img width="694" alt="hashlips-art-engine-problem" src="https://user-images.githubusercontent.com/97996116/150040950-81c64028-89c2-4dea-8e2f-31d4def22026.png">

Please help. Thanks.

**Comment by MrRo-de** [comment]
I have exactly the same problem. But it generates 3 out of 100 and then this problem show up.

**Comment by benhalverson** [comment]
Some of your files have a `-` dash change it to an `_`  underscore  or remove it and try again.

**Comment by crosbypierce** [comment]
> Some of your files have a `-` dash change it to an `_` underscore or remove it and try again.

Thank you. It worked.
