### ISSUE TITLE
Question -  Possible create a collection based in gender?

### ISSUE THREAD

**Issue by jpaezsa** [HashLips/hashlips_art_engine#56]
Anyone knows if are possible create a collection based in gender?
- ex. 50 Male and 50 Female, sharing common attributes like bg or other presets in layers

Regards!

**Comment by jpaezsa** [comment]
I think, is creating in config 2 batches/sets, different attributes to tray to generate sharing rarities…


Possible Solution ->

**What you think?**

```
const layerConfigurations = [
  {
    // MALE VERSION
    growEditionSizeTo: 5,
    layersOrder: [
      { name: "Background" },
      { name: "Eyeball" },
      { name: "Eye color" },
      { name: "Iris" },
      { name: "Shine" },
      { name: "Bottom lid" },
      { name: "Top lid" },
      { name: "Male" },
    ],
  },
  {
    // FEMALE VERSION
    growEditionSizeTo: 10,
    layersOrder: [
      { name: "Background" },
      { name: "Eyeball" },
      { name: "Eye color" },
      { name: "Iris" },
      { name: "Shine" },
      { name: "Bottom lid" },
      { name: "Top lid" },
      { name: "Female" },
    ],
  },
];

```

This are the result: 

![image](https://user-images.githubusercontent.com/1481416/134760290-f51bcdeb-c75c-4f1b-be3f-14f5e50eed29.png)

**Comment by burmestr** [comment]
Layer groups exist as a function since previous versions, why do you post it here aa a bright new idea? ... Close it
