### ISSUE TITLE
Distorted Images

### ISSUE THREAD

**Issue by ThePresence** [HashLips/hashlips_art_engine#568]
Hi,

Thank you for this wonderful project.

I have 2 layers e.g. L1 and L2, so L1 has same pixel width and height but images in L2 has different pixel width and height which produces distorted images. How can I solve this issue?

Regards,

**Comment by Mirzatalha** [comment]
in config.js file in format object  
do this

smoothing: true, 


![image](https://user-images.githubusercontent.com/63523708/150349851-199ce07f-b245-4bfc-8943-bef404f001b9.png)

**Comment by ThePresence** [comment]
> in config.js file in format object  
> do this
> 
> smoothing: true, 
> 
> 
> ![image](https://user-images.githubusercontent.com/63523708/150349851-199ce07f-b245-4bfc-8943-bef404f001b9.png)
> 

Tried this but same result.

**Comment by ThePresence** [comment]
The workaround for me was to make all the layers have same width and height.
