### ISSUE TITLE
Please add this idea to the engine. This is due to the layers, I have attached a diagram

### ISSUE THREAD

**Issue by AlexeyPe** [HashLips/hashlips_art_engine#590]
Hi, please add the possibility that some layers are not random and depend on some previous layer (several previous ones?)

In my situation: there is hair, it should be behind the body, there is a part of the hair that will be in front of the body

What is the problem: the first layer randomly determines the hair, they can be light, there is a part of the hair that will be on the clothes, but they are randomly selected as green or those that do not fit the shape - this is my problem, I do not want random hair on this layer, I need pre-prepared hair there

If we assume that it works like this: if the image has an additional suffix, for example # "suffix" + "number" (a2).
This would mean that after 2 layers I need to add an image - where do I get the image from?
For example, after 2 layers there is a prepared folder in which the image is prepared - with the same name as from the 1st layer, perhaps with additional suffixes?

Actually, I have some programming skills, but God, please, I won't be able to do this, please add this to the engine ;)
**I do not know English and used a translator, I hope it was written normally
![problem-100](https://user-images.githubusercontent.com/70694988/150856558-3f84277b-d8b9-4e75-b245-efef58a73ac6.jpg)

**Comment by Azmuch** [comment]
I am not a programmer but i suggest:
Make all hair as 1 layer and place on top of hierarchy
Cut out face and clothes so that they show through the transparent PNG 
or SVG file. (similar to the attached)

**Comment by Qumico** [comment]
this will work, but my clothes are shaped differently, and my hair is shaped differently. Therefore it doesn't fit.
For example, there is knightly armor, there is also a T-shirt and they are of different shapes, and there are more than 6 clothes, as well as more than 8 hair, if you cut out each hair, you get 6 * 8 = 48 clothes and hair combined together, and they will have to be combined
