### ISSUE TITLE
Messed up images after generating

### ISSUE THREAD

**Issue by ilovesketchers** [HashLips/hashlips_art_engine#594]
At first the images would come out completely distorted but after exporting all of them at 1080 x 1080 they were a little more recognizable, but it seemed that the layers were not aligning in the correct places. For instance, the mouth would be on top of the eyes, clothes, and the accessory. Has anyone ran in to a similar issue and been able to fix it?

**Comment by RequiemDreams** [comment]
having same issue any fixes you would be a good send been tryna work this out for last 4 days it's as if each image has same proportion size and are covering one another
