### ISSUE TITLE
Rarity Question

### ISSUE THREAD

**Issue by SethCalkins** [HashLips/hashlips_art_engine#6]
Love you youtube channel by the way, and thanks so much for what you do for the community. 

Can you point me in the direction as to how I how would I calculate the total rarity of an image outputted? 
For example, your previous repo specified original, rare, super rare

**Comment by SethCalkins** [comment]
On your site you have Original, Rare, Super Rare for pricing structure. How would I identify the same with this repo?

**Comment by HashLips** [comment]
Add all the rarity weights for a given folder for example [20 + 40 + 15 + 50 + 20 + 10 + 90] = 245. Then you have the ratio of your elements rarity so the first element will have a ratio of 20/245 so do this (20 / 245) * 100 = 8.16% Rarity.
