### ISSUE TITLE
number of clones

### ISSUE THREAD

**Issue by Starla1979** [HashLips/hashlips_art_engine#613]
Hi having a bit of a frustrating issue I am trying to clone 100 nft but it will not clone more than 5. I am changing the growEditionSizeTo:100 but still it only clones 5 can anyone please help.

**Comment by AllieZZ** [comment]
Just click File-Save. Every time you make changes to the code, you first need to save, only after saving the changes will be accepted.

**Comment by Starla1979** [comment]
Thank you very much that worked.

**Comment by Starla1979** [comment]
Hi 

When I change the name in layers folder and the same name in the layers Order: I get an error message no idea why can you help?
      { name: "Background" },

**Comment by Starla1979** [comment]
This is the error message TypeError: Cannot read properties of undefined (reading 'replace')

**Comment by AllieZZ** [comment]
I first tried to run the start script with the files that were in the archive. And only then did he customize it for himself, comparing it with what was in the archive. Did you correctly name the names of the layers inside the folder? 
"Create your different layers as folders in the 'layers' directory, and add all the layer assets in these directories. You can name the assets anything as long as it has a rarity weight attached in the file name like so: example element#70.png. You can optionally change the delimiter # to anything you would like to use in the variable rarityDelimiter in the src/config.js file."
