### ISSUE TITLE
The generated JSON metadata files do not contain the creator of the collection

### ISSUE THREAD

**Issue by CineEncoder** [HashLips/hashlips_art_engine#631]
Hello!
Tell me please why the generated JSON metadata files do not contain the creator of the collection? 
despite the fact that in config.js the creator is specified in the solanaMetadata field.

**Comment by thepeanutgalleryandco** [comment]
@CineEncoder the solanaMetadata is only used when generating Solana Metadata files. If you are generating Ethereum / polygon metadata, then you need to scroll down in the config.js file to the "extraMetadata" object where you can add your creator, external_url, etc.

const extraMetadata = {
  //creator: "NFT_CREATOR_HERE", // Add the creator of the NFT collection here. Ex. The Peanut Gallery And Co
  //external_url: "YOUR_WEBSITE_URL_HERE"  // Add your website URL here. This will be added to each of your NFTs. Ex. https://thepeanutgalleryandco.co.za/
};
