### ISSUE TITLE
Npm not Install macbook air m1

### ISSUE THREAD

**Issue by hamzailyas434** [HashLips/hashlips_art_engine#643]
<img width="1440" alt="Screenshot 2022-01-31 at 6 10 56 PM" src="https://user-images.githubusercontent.com/63106388/151799521-0a4c4466-3b44-43db-8437-40a60ac5c73e.png">

**Comment by hamzailyas434** [comment]
Node Version: v16.13.0
NPM Version: 8.1.0

**Comment by MaciekBaron** [comment]
The message explains what's wrong: you need Python 3 (>=3.6.0 to be precise). Your installed version is 2.7.

**Comment by bolshoytoster** [comment]
@hamzailyas434 just so you know, one of the dependencies (canvas) can't run on M1 without rosetta.

**Comment by hamzailyas434** [comment]
> The message explains what's wrong: you need Python 3 (>=3.6.0 to be precise). Your installed version is 2.7.
<img width="1440" alt="Screenshot 2022-02-01 at 12 33 02 PM" src="https://user-images.githubusercontent.com/63106388/151929115-1d5d2de8-1f9e-492b-ac23-eba8db842af7.png">

**Comment by hamzailyas434** [comment]
> The message explains what's wrong: you need Python 3 (>=3.6.0 to be precise). Your installed version is 2.7.

Installed: softwareupdate --install-rosetta
But Still facing the same issue.

**Comment by hamzailyas434** [comment]
> The message explains what's wrong: you need Python 3 (>=3.6.0 to be precise). Your installed version is 2.7.
<img width="1440" alt="Scree
<img width="1440" alt="Screenshot 2022-02-01 at 12 36 35 PM" src="https://user-images.githubusercontent.com/63106388/151929460-164460d8-ce12-46f8-b402-57d2763bebdd.png">
nshot 2022-02-01 at 12 35 50 PM" src="https://user-images.githubusercontent.com/63106388/151929385-a0873595-8bfe-499e-9399-8d9edc0fa741.png">
This is my path

**Comment by bolshoytoster** [comment]
@hamzailyas434 it gives you '404 not found', because it's still trying to download the amd versions (that don't exist). You can target x64 by running `npm install --target_arch=x64`.

**Comment by hamzailyas434** [comment]
> npm install --target_arch=x64

Thank you so much it finally installed the node modules but now it's not running.
<img width="1440" alt="Screenshot 2022-02-01 at 12 57 36 PM" src="https://user-images.githubusercontent.com/63106388/151931833-6ea178a6-8da8-425e-9f98-d4acce24c9d5.png">

**Comment by bolshoytoster** [comment]
@hamzailyas434 you might have to install the x64 mode.js as well if you can figure out how.

**Comment by hamzailyas434** [comment]
> npm install --target_arch=x64

Can you please send me the link?

**Comment by hamzailyas434** [comment]
> @hamzailyas434 you might have to install the x64 node.js as well if you can figure out how.

of this

**Comment by hamzailyas434** [comment]
> @hamzailyas434 you might have to install the x64 node.js as well if you can figure out how.

Can you please text me: hamzailyas434@gmail.com or whatsapp/telegram: +923026282822. Please help me to resolve this issue.
