### ISSUE TITLE
NPM install not working not even the yarn command 

### ISSUE THREAD

**Issue by Tanmay0008** [HashLips/hashlips_art_engine#644]
![Screenshot (33)](https://user-images.githubusercontent.com/98755085/151809621-7647411c-7dbe-473f-8b57-57f704d4fb4f.png)

this is appearing dk what to do please help 
regards

**Comment by bolshoytoster** [comment]
@Tanmay0008 try `cd hashlips_art_engine-1.1.2_patch_v5`.

**Comment by Tanmay0008** [comment]
thank you so much dude it worked <3
