### ISSUE TITLE
ERROR WHILE USE NODE INDEX.JS CODE

### ISSUE THREAD

**Issue by BreachBoy** [HashLips/hashlips_art_engine#651]
Hello, i'm newbie in coding, specially in visual studio code
yesterday i had an error like this

PS D:\2022\NFT\ALAT & SOFTWARE\hashlips_art_engine-main> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'D:\2022\NFT\ALAT & SOFTWARE\hashlips_art_engine-main/node_modules/sha1'
Require stack:
- D:\2022\NFT\ALAT & SOFTWARE\hashlips_art_engine-main\src\main.js
- D:\2022\NFT\ALAT & SOFTWARE\hashlips_art_engine-main\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\2022\NFT\ALAT & SOFTWARE\hashlips_art_engine-main\src\main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\2022\\NFT\\ALAT & SOFTWARE\\hashlips_art_engine-main\\src\\main.js',
    'D:\\2022\\NFT\\ALAT & SOFTWARE\\hashlips_art_engine-main\\index.js'
  ]
}

anyone can help me? :(

**Comment by bolshoytoster** [comment]
@BreachBoy
> Error: Cannot find module 'D:\2022\NFT\ALAT & SOFTWARE\hashlips_art_engine-main/node_modules/sha1'

This says that it can’t find the `sha1` module. Try running `npm install`/`yarn install` again.

**Comment by BreachBoy** [comment]
@bolshoytoster Thaks for your respons!

i've try your suggestion, and this is the result :

PS D:\2022\NFT\ALAT & SOFTWARE\hashlips_art_engine-main> yarn install
yarn : The term 'yarn' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify    
that the path is correct and try again.
At line:1 char:1
+ yarn install
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (yarn:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
what should i do?

**Comment by bolshoytoster** [comment]
@BreachBoy
> yarn : The term 'yarn' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.

You need to install yarn.

**Comment by BreachBoy** [comment]
@bolshoytoster 

okay i have finished, what sholud i do? 😅

PS D:\2022\NFT\ALAT & SOFTWARE\hashlips_art_engine-main> npm install -g yarn

added 1 package, and audited 2 packages in 3s

found 0 vulnerabilities

**Comment by bolshoytoster** [comment]
@BreachBoy run `yarn install` then you should be good to go.

**Comment by BreachBoy** [comment]
@bolshoytoster 

PS D:\2022\NFT\ALAT & SOFTWARE\hashlips_art_engine-main> yarn install
yarn : File C:\Users\LENOVO\AppData\Roaming\npm\yarn.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies 
at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ yarn install
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

another error :(

**Comment by bolshoytoster** [comment]
@BreachBoy you could run `Set-ExecutionPolicy Unrestricted` in an admin powershell.

**Comment by BreachBoy** [comment]
fortunately that problem is done :}
but my last problem, why the layer exported is only the top one?

**Comment by bolshoytoster** [comment]
@BreachBoy is the top image transparent or does it cover the rest?

**Comment by BreachBoy** [comment]
@bolshoytoster transparent, all my layers is transparent except background layers

**Comment by cfpmonty** [comment]
Having the same troubles and applied all of the fixes above and have it down to these errors.
also ran the npm install npm-g
Also a newbie at this, Thanks Monty


PS C:\Users\monty\Desktop\hashlips_art_engine-1.1.2_patch_v5 (1)
node:internal/modules/cjs/loader:936
  throw err;
  ^
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by bolshoytoster** [comment]
@cfpmonty can you delete the `node_modules` folder then run `yarn install` and `npm install` again.

**Comment by cfpmonty** [comment]
is that command  npm uninstall node_modules 
to delete before running yarn and npm install again

**Comment by bolshoytoster** [comment]
@cfpmonty
> is that command npm uninstall node_modules

No, just delete it, i.e. `rm node_modules -r`.

**Comment by cfpmonty** [comment]
Removed node modules and ran yarn install and npm install and got this on running the node index.js command


PS C:\Users\monty\Desktop\hashlips_art_engine-1.1.2_patch_v5 (1)
node:internal/modules/cjs/loader:936
  throw err;
  ^
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by bolshoytoster** [comment]
@cfpmonty does `npm run build` return the same error?

**Comment by cfpmonty** [comment]
here is the new error , tried running npm run generate and came back with same err missing script "generate"

PS C:\Users\monty\Desktop\hashlips_art_engine-1.1.2_patch_v5 (1)> npm run build
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\monty\AppData\Local\npm-cache\_logs\2022-02-02T23_03_52_474Z-debug-0.log

**Comment by bolshoytoster** [comment]
@cfpmonty I think it's because there's a space in your path. Change the folder's name from `hashlips_art_engine-1.1.2_patch_v5 (1)` to `hashlips_art_engine-1.1.2_patch_v5-(1)` or whatever as long as it doesn't have a space in it. Then run `node index.js`.

**Comment by cfpmonty** [comment]
re-named folder and re-opened to run and still got the same kick back.   
PS C:\Users\monty\Desktop\hashlips_art_engine-1.1.2_patch_v5 (1)> node index.js
node:internal/modules/cjs/loader:936
  throw err;

**Comment by cfpmonty** [comment]
The space was the problem after re- opening I had to reload the -g yarn and npm install and was able to get a build file.
Thank you so much for the help!!
