### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by adcommodore** [HashLips/hashlips_art_engine#673]
Not sure why I keep getting unexpected token. tried to change it to a couple of other tokens to see if anything changes but it gets upset...I'm using version 10 of node...

initGifEncoder = () => {
                 ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/alexis/hashlips_art_engine/src/main.js:32:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

Here's where it's directing me to the editor

 initGifEncoder = () => {
    this.gifEncoder = new GifEncoder(this.canvas.width, this.canvas.height);
    this.gifEncoder.setQuality(this.quality);
    this.gifEncoder.setRepeat(this.repeat);
    this.gifEncoder.setDelay(this.delay);
  };

**Comment by bolshoytoster** [comment]
@adcommodore you could try changing the line to `initGifEncoder() {`. You'll probably also have to change the other similar lines accordingly.

**Comment by larryj52** [comment]
I am getting a similar errorcode.  Can someone advise

SyntaxError: Unexpected token '{'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:24:5)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)

**Comment by bolshoytoster** [comment]
@larryj52 your `src/config.js` has a syntax error, could you paste it here?

**Comment by bolshoytoster** [comment]
@larryj52 can you paste the `src/config.js` file please?

**Comment by larryj52** [comment]
The whole thing?

**Comment by bolshoytoster** [comment]
@larryj52 just the bits you've changed

**Comment by larryj52** [comment]
// If you have selected Solana then the collection starts from 0 automatically
const layerConfigurations = [
  {
    growEditionSizeTo: 10000,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Afro" },
      { name: "Face" },
      { name: "Dickie" },
      { name: "Dashikis" },
      { name: "Eye Brows" },
      { name: "Eyes" },
      { name: "Nose" },
      { name: "Mouths" },
      { name: "Pupils" },
      { name: "Shades" },
      { name: "Picks" },
      { name: "Hats" },
];



const extraMetadata = {external_url: "http://soulbrono1.xyz"
};


// General metadata for Ethereum
const namePrefix = "SoulBroNo1";
const description = "A mecca cool brother reflecting the times gone by";
const baseUri = "ipfs://NewUriToReplace";


const extraMetadata = {external_url: "http://soulbrono1.xyz"
};

**Comment by larryj52** [comment]
These are the problems that are being highlighted:

[{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 42,
	"startColumn": 2,
	"endLineNumber": 42,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 44,
	"startColumn": 7,
	"endLineNumber": 44,
	"endColumn": 33
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 44,
	"startColumn": 41,
	"endLineNumber": 44,
	"endColumn": 42
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 46,
	"startColumn": 7,
	"endLineNumber": 46,
	"endColumn": 16
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 46,
	"startColumn": 24,
	"endLineNumber": 46,
	"endColumn": 25
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 48,
	"startColumn": 7,
	"endLineNumber": 48,
	"endColumn": 13
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 52,
	"startColumn": 2,
	"endLineNumber": 52,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 54,
	"startColumn": 7,
	"endLineNumber": 54,
	"endColumn": 10
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 59,
	"startColumn": 2,
	"endLineNumber": 59,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 61,
	"startColumn": 7,
	"endLineNumber": 61,
	"endColumn": 11
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 72,
	"startColumn": 2,
	"endLineNumber": 72,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 74,
	"startColumn": 7,
	"endLineNumber": 74,
	"endColumn": 18
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 76,
	"startColumn": 2,
	"endLineNumber": 76,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 78,
	"startColumn": 7,
	"endLineNumber": 78,
	"endColumn": 17
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 83,
	"startColumn": 2,
	"endLineNumber": 83,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 85,
	"startColumn": 7,
	"endLineNumber": 85,
	"endColumn": 20
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 86,
	"startColumn": 2,
	"endLineNumber": 86,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 88,
	"startColumn": 7,
	"endLineNumber": 88,
	"endColumn": 22
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 88,
	"startColumn": 28,
	"endLineNumber": 88,
	"endColumn": 29
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 90,
	"startColumn": 7,
	"endLineNumber": 90,
	"endColumn": 24
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 90,
	"startColumn": 32,
	"endLineNumber": 90,
	"endColumn": 33
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 92,
	"startColumn": 7,
	"endLineNumber": 92,
	"endColumn": 14
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 97,
	"startColumn": 2,
	"endLineNumber": 97,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 99,
	"startColumn": 7,
	"endLineNumber": 99,
	"endColumn": 18
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 106,
	"startColumn": 2,
	"endLineNumber": 106,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 108,
	"startColumn": 7,
	"endLineNumber": 108,
	"endColumn": 8
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 127,
	"startColumn": 2,
	"endLineNumber": 127,
	"endColumn": 2,
	"relatedInformation": [
		{
			"startLineNumber": 108,
			"startColumn": 18,
			"endLineNumber": 108,
			"endColumn": 19,
			"message": "The parser expected to find a '}' to match the '{' token here.",
			"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js"
		},
		{
			"startLineNumber": 26,
			"startColumn": 3,
			"endLineNumber": 26,
			"endColumn": 4,
			"message": "The parser expected to find a '}' to match the '{' token here.",
			"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js"
		}
	]
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 42,
	"startColumn": 2,
	"endLineNumber": 42,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 44,
	"startColumn": 7,
	"endLineNumber": 44,
	"endColumn": 33
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 44,
	"startColumn": 41,
	"endLineNumber": 44,
	"endColumn": 42
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 46,
	"startColumn": 7,
	"endLineNumber": 46,
	"endColumn": 16
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 46,
	"startColumn": 24,
	"endLineNumber": 46,
	"endColumn": 25
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 48,
	"startColumn": 7,
	"endLineNumber": 48,
	"endColumn": 13
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 52,
	"startColumn": 2,
	"endLineNumber": 52,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 54,
	"startColumn": 7,
	"endLineNumber": 54,
	"endColumn": 10
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 59,
	"startColumn": 2,
	"endLineNumber": 59,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 61,
	"startColumn": 7,
	"endLineNumber": 61,
	"endColumn": 11
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 72,
	"startColumn": 2,
	"endLineNumber": 72,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 74,
	"startColumn": 7,
	"endLineNumber": 74,
	"endColumn": 18
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 76,
	"startColumn": 2,
	"endLineNumber": 76,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 78,
	"startColumn": 7,
	"endLineNumber": 78,
	"endColumn": 17
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 83,
	"startColumn": 2,
	"endLineNumber": 83,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 85,
	"startColumn": 7,
	"endLineNumber": 85,
	"endColumn": 20
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 86,
	"startColumn": 2,
	"endLineNumber": 86,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 88,
	"startColumn": 7,
	"endLineNumber": 88,
	"endColumn": 22
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 88,
	"startColumn": 28,
	"endLineNumber": 88,
	"endColumn": 29
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 90,
	"startColumn": 7,
	"endLineNumber": 90,
	"endColumn": 24
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 90,
	"startColumn": 32,
	"endLineNumber": 90,
	"endColumn": 33
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 92,
	"startColumn": 7,
	"endLineNumber": 92,
	"endColumn": 14
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 97,
	"startColumn": 2,
	"endLineNumber": 97,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 99,
	"startColumn": 7,
	"endLineNumber": 99,
	"endColumn": 18
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 106,
	"startColumn": 2,
	"endLineNumber": 106,
	"endColumn": 3
},{
	"resource": "/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 108,
	"startColumn": 7,
	"endLineNumber": 108,
	"endColumn": 8
}]

**Comment by bolshoytoster** [comment]
@larryj52 I think you're missing a `}]` around
```js
{ name: "Hats" },
];
 ^
```
Changing it to
```js
{ name: "Hats" },
]}];
```
Should fix it.

**Comment by larryj52** [comment]
I'll try it.

**Comment by larryj52** [comment]
It didn't work

**Comment by bolshoytoster** [comment]
@larryj52 What error is it giving you now?

**Comment by larryj52** [comment]
Same error

SyntaxError: Unexpected token '{'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:24:5)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)

**Comment by bolshoytoster** [comment]
@larryj52 what part is the error coming from?

**Comment by larryj52** [comment]
/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/config.js:38
      { name: "Pupils" },

i think

**Comment by larryj52** [comment]
This is what the code looks like now with yyour suggestion.

// If you have selected Solana then the collection starts from 0 automatically
const layerConfigurations = [
  {
    growEditionSizeTo: 10000,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Afro" },
      { name: "Face" },
      { name: "Dickie" },
      { name: "Dashikis" },
      { name: "Eye Brows" },
      { name: "Eyes" },
      { name: "Nose" },
      { name: "Mouths" },
      { name: "Pupils" },
      { name: "Shades" },
      { name: "Picks" },
      { name: "Hats" },
]}];

const shuffleLayerConfigurations = false;

**Comment by bolshoytoster** [comment]
@larryj52 there might be a missing comma on the line before, if not, can you send the line above this.

**Comment by adcommodore** [comment]
> @adcommodore you could try changing the line to `initGifEncoder() {`. You'll probably also have to change the other similar lines accordingly.

This totally worked. Thank you!

**Comment by larryj52** [comment]
Sent

**Comment by larryj52** [comment]
@adcommodore where did you put this line – initGifEncoder() { ?

**Comment by bolshoytoster** [comment]
@larryj52 that's about the original issue.

Can you send me the full error and the full `src/config.js` file please.

**Comment by larryj52** [comment]
const basePath = process.cwd();
const { MODE } = require(`${basePath}/constants/blend_mode.js`);
const { NETWORK } = require(`${basePath}/constants/network.js`);

const network = NETWORK.eth;

// General metadata for Ethereum
const namePrefix = "SoulBroNo1";
const description = "A mecca cool brother reflecting the times gone by";
const baseUri = "ipfs://NewUriToReplace";

const solanaMetadata = {
  symbol: "YC",
  seller_fee_basis_points: 1000, // Define how much % you want from secondary market sales 1000 = 10%
  external_url: "https://www.youtube.com/c/hashlipsnft",
  creators: [
    {
      address: "7fXNuer5sbZtaTEPhtJ5g5gNtuyRoKkvxdjEjEnPN4mC",
      share: 100,
    },
  ],
};

// If you have selected Solana then the collection starts from 0 automatically
const layerConfigurations = [
  {
    growEditionSizeTo: 10000,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Afro" },
      { name: "Face" },
      { name: "Dickie" },
      { name: "Dashikis" },
      { name: "Eye Brows" },
      { name: "Eyes" },
      { name: "Nose" },
      { name: "Mouths" },
      { name: "Pupils" },
      { name: "Shades" },
      { name: "Picks" },
      { name: "Hats" },
]}];

const shuffleLayerConfigurations = false;

const debugLogs = false;

const format = {
  width: 1500,
  height: 1500,
  smoothing: false,
};

const gif = {
  export: false,
  repeat: 0,
  quality: 100,
  delay: 500,
};

const text = {
  only: false,
  color: "#ffffff",
  size: 20,
  xGap: 40,
  yGap: 40,
  align: "left",
  baseline: "top",
  weight: "regular",
  family: "Courier",
  spacer: " => ",
};

const pixelFormat = {
  ratio: 2 / 128,
};

const background = {
  generate: true,
  brightness: "80%",
  static: false,
  default: "#000000",
};

const extraMetadata = {external_url: "http://soulbrono1.xyz"
};

const rarityDelimiter = "#";

const uniqueDnaTorrance = 10000;

const preview = {
  thumbPerRow: 5,
  thumbWidth: 50,
  imageRatio: format.height / format.width,
  imageName: "preview.png",
};

const preview_gif = {
  numberOfImages: 5,
  order: "ASC", // ASC, DESC, MIXED
  repeat: 0,
  quality: 100,
  delay: 500,
  imageName: "preview.gif",
};

module.exports = {
  format,
  baseUri,
  description,
  background,
  uniqueDnaTorrance,
  layerConfigurations,
  rarityDelimiter,
  preview,
  shuffleLayerConfigurations,
  debugLogs,
  extraMetadata,
  pixelFormat,
  text,
  namePrefix,
  network,
  solanaMetadata,
  gif,
  preview_gif,

**Comment by bolshoytoster** [comment]
@larryj52 I haven't run into any problems with that, I assume you have a `}` on the last line.

**Comment by larryj52** [comment]
I'll try

**Comment by larryj52** [comment]
Problem not resolved.  I re installed node.js and updated visual basic.  getting new error messages. WHat does this mean:


(node:43978) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:184
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at /Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:184:61
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:183:10)
    at /Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:364:31
    at Array.forEach (<anonymous>)
    at startCreating (/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:363:17)
    at /Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/index.js:6:3
    at Object.<anonymous> (/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)

Node.js v17.4.0

**Comment by bolshoytoster** [comment]
@larryj52 I think this can happen if you have DNA_DELIMITER (`-` by default) in the name of one of your images/layers.
