### ISSUE TITLE
Build rarity data and metadate from file contents in stead of config.js

### ISSUE THREAD

**Issue by klibansky** [HashLips/hashlips_art_engine#69]
At the moment, when you want to build the rarity data, the script looks at the config.js.

In my case, I first generated all the images and later decided to change a name of a trait.
So I ran a little terminal command to do a search and replace through all the separate files.

What I also did is I ran one instance to generate 500 images after that I changed some weights in the file names to generate another 1000 images with a different distribution.

When I re-ran the rebuildMetadata or the rarityData script, it did not work as intended because it did not reflect the current set, because the script is not looking at the file contents.

I think a great feature would be for the scripts to actually look at the contents of all the json files, index them and on the basis of that output the rarity data or generate the metadata file.

**Comment by enafta** [comment]
agree. 
it would make it easy
how can you do it?
