### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by larryj52** [HashLips/hashlips_art_engine#690]
I am getting this message and I don't know what it means. 
Cannot read properties of undefined (reading 'path')
I re-installed node.js and updated visual basic

**Comment by frasil1** [comment]
Bro, how u fix it.

**Comment by bolshoytoster** [comment]
@larryj52 can you post your full error here please.

**Comment by larryj52** [comment]
I started all over from the beginning after updating all of the software. Dump everything and reload from the start, Visual Basic hey the latest. Node.is and Hashlips 1.1.5

I am in a Mac so I had the change the “bash” path as well.


Larry Johnson
Reach Advertising and Design
***@***.***
(310) 654-0128
