### ISSUE TITLE
Hitting Duplicate DNA images multiple times - no error generated

### ISSUE THREAD

**Issue by ken-vat** [HashLips/hashlips_art_engine#691]
Found this with nftchef fork but could be an issue here 
All info here - https://github.com/nftchef/art-engine/issues/26

**Comment by bolshoytoster** [comment]
@ken-vat do you know if the issue occurs with this repo?

**Comment by ken-vat** [comment]
I havent tried the same config. I need the things that nftchef provides such as rarity weights in multiple layers, bypass dna, most importantly forcecombinations. Reason for posting here, is that this dna and dna check is a core function so I wouldnt be surprised if i hit the issue here.

**Comment by bolshoytoster** [comment]
@ken-vat looking at nftchef's code, it looks like they've changed the `isDnaUnique` function and probably a few other related ones. it might be just related to that repo.
