### ISSUE TITLE
Not all nft generate

### ISSUE THREAD

**Issue by heracross1412** [HashLips/hashlips_art_engine#696]
i have 3 layers
1. Background with 23 items
2. Body with 12 items
3. Clothes with 24 items
With this combination, i think i can generate 6624 NFT.

But after i do npm run generate, it stop at 6052 NFT.
Did i misscalculate ?
thanks for help

**Comment by bolshoytoster** [comment]
@heracross1412 did it give any output other than `Created edition: ..., with DNA: ...`?

**Comment by heracross1412** [comment]
> 

I done the running, but it say i dont have any layer and when i check the build folder, it only generate 6052 nft

**Comment by bolshoytoster** [comment]
@heracross1412 does it create 6052 if you run it again?

**Comment by heracross1412** [comment]
> @heracross1412 does it create 6052 if you run it again?

it doesnt, it decrease to 6031. did i miss something for running it ?

**Comment by bolshoytoster** [comment]
@heracross1412 did it say '`You need more layers or elements to grow your edition to ... artworks`'?

**Comment by heracross1412** [comment]
> 

yess you are right. it say that !
do i need to add more layer ? but from my calculation, i can generate 6624 nft
i also do this in order

    growEditionSizeTo: 6624,
    layersOrder: [
      { name: "Background" },
      { name: "Skin" },
      { name: "Body" },
      
      i have 23 background, 12 body and 24 clothes

**Comment by bolshoytoster** [comment]
@heracross1412 it's because it made too many duplicates, it's to stop it from going into an infinite loop. You can disable it by removing line 414 of `src/main.js`:  `editionCount++;`.

**Comment by heracross1412** [comment]
> 

allright im gonna try that, hope it gonna work. thanks for ur help

**Comment by heracross1412** [comment]
> @heracross1412 it's because it made too many duplicates, it's to stop it from going into an infinite loop. You can disable it by removing line 414 of `src/main.js`: `editionCount++;`.

after i running it again, it stop at 6074
i also remove already not include the line 414

![image](https://user-images.githubusercontent.com/22199218/153081217-754df58b-a533-46a2-a320-fd674851bf25.png)

**Comment by bolshoytoster** [comment]
@heracross1412 sorry it's line 418 in that version.

**Comment by heracross1412** [comment]
> @heracross1412 sorry it's line 418 in that version.

work like charms. thanks dude, u save my day sooo much !
