### ISSUE TITLE
Is there a way to do less than 1%?

### ISSUE THREAD

**Issue by xman86** [HashLips/hashlips_art_engine#700]
I am making a set of 10,000 total. I want there to be a very rare item of 5 different colors. I want there to be 20 of each, so I write "Nameofthing#.2" (with .png after the 2). Is this the right way to do this? The only image of the rare ones I get when running the node index.js after saving the percentages is the image of the rare item that is listed highest in its layer folder. All other images in the folder work fine with decimals (none of them have decimals first. So, 5.5, 6.5, etc work fine). It appears that the one that does show up is consistent with the #.2; but I do not get the other 4/5 rare pics. Help and advice would be greatly appreciated.

**Comment by bolshoytoster** [comment]
@xman86 you could change the total of the chances to 10,000. I'm going to add support for decimal chances soon though.

**Comment by xman86** [comment]
Thank You!

**Comment by jeff41101** [comment]
> total of the chance

Hi, may I ask which parameter is in charge of the total chances?

**Comment by bolshoytoster** [comment]
@jeff41101 it's just all of the chances added together.
