### ISSUE TITLE
start from certain number

### ISSUE THREAD

**Issue by heracross1412** [HashLips/hashlips_art_engine#711]
hello, is there any way to start the second generate but it start the count from the last generate ?

lets say i start first generate for 1000 collection, after that i want to start from 1001-2000

thanks for help

**Comment by bolshoytoster** [comment]
@heracross1412 [my repo](https://github.com/bolshoy/hashlips_art_engine) has this functionality, it will just continue from the previous run.

**Comment by heracross1412** [comment]
> @heracross1412 [my repo](https://github.com/bolshoy/hashlips_art_engine) has this functionality, it will just continue from the previous run.

cant open the repo sir, can u send it again..
also what configuration did i need to change. thanks sir

**Comment by bolshoytoster** [comment]
@heracross1412 bugger, it's https://github.com/bolshoytoster/hashlips_art_engine.

**Comment by bolshoytoster** [comment]
@heracross1412 you don't need to touch your configurations.

**Comment by heracross1412** [comment]
> @heracross1412 you don't need to touch your configurations.

ah i get it !
if i run second time but with same collection, does it gonna change DNA from the start, or just from newest run ?

**Comment by bolshoytoster** [comment]
@heracross1412 no, it loads the already created DNA to make sure there are no duplicates.

**Comment by heracross1412** [comment]
> @heracross1412 no, it loads the already created DNA to make sure there are no duplicates.

thanks alot frens, i already make it. really thanks for ur help
