### ISSUE TITLE
Layer not showing up

### ISSUE THREAD

**Issue by Mirandalynn7** [HashLips/hashlips_art_engine#724]
Everything is correct and running, but two layers are not showing up in generated photos . its just skipping the layer and moved to the next one,  any idea how to fix this ?

**Comment by nolimitf8t** [comment]
having the same issue or my layers are misplaced

**Comment by Mirandalynn7** [comment]
figured it out. one of the layers were solid and blocking. the other one

**Comment by BreachBoy** [comment]
hello, i've same problem, but my layers are not misplaced....

**Comment by bolshoytoster** [comment]
@BreachBoy make sure the layers have transparency.
