### ISSUE TITLE
Setting price and blockchain in metadata?

### ISSUE THREAD

**Issue by MaWads** [HashLips/hashlips_art_engine#748]
Hey Daniel/All,

I have run the Art Generator and it worked like a charm. 

However, in the metadata, the price is automatically set to 0.005 and the blockchain is Polygon. 

Is there any way to edit this prior to running the Art Generator? Say I wanted the price to be 0.1 and Blockchain to be ETH? I've looked high and low, watched the videos and am not sure. 

If there's no way to change this before running the generator, any idea how to bulk-change the values in the _metadata.json? 

I ask because I am bulk uploading to OpenSea with a program, and it is automatically selling them for the 0.005 price as that's what is in the metadata

Thanks!

**Comment by MaWads** [comment]
Disregard!

**Comment by rwsbrasil** [comment]
Hi, 

> Disregard!

Hi, did you succeed ?
