### ISSUE TITLE
modual not found error

### ISSUE THREAD

**Issue by pickles4812** [HashLips/hashlips_art_engine#754]
PS C:\Users\matt\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v5> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\matt\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v5\index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by bolshoytoster** [comment]
@pickles4812 You're in the wrong folder. Run `ls -Directory` to get the name and run `cd ` + tha name of the folder.

**Comment by ijaz13100** [comment]
> ls -Directory

Hi, Thanks for helping with this, I have the same issue.  I am using mac and the directory is on an external (not sure if that matters).  I run ls -Directory and get this:  

ls: illegal option -- -
usage: ls [-@ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1%] [file ...]

Can you please expand on your answer?  Much appreciated.

**Comment by pickles4812** [comment]
@bolshoytoster Thank you for the help its working now
