### ISSUE TITLE
Restart generating from where it stopped

### ISSUE THREAD

**Issue by faizanraj** [HashLips/hashlips_art_engine#76]
Can we restart generating art from the last time we stopped, instead of deleting all old files and start from zero?

For example: if I am generating 5000 artworks, it will take time to create 5000 so can I generate 5k in 5 different parts from the same layers, if I generate 1k on Monday and again give command node index.js on Tuesday it will delete all the build output files and start generating from the 0. Thank you.

**Comment by kristiangabriel** [comment]
In some of the older versions of Hashlips code, it had the "Start Number" but I don't see it in the newer Updates. I would also be interested to know this. An obvious question in addition to the original one, is if you are able to "continue" to process your NFT's from let say from #1000 to #2000--would the additional continued NFT creations still be unique to the ones that were created before? That's the trick. Continue isn't the problem but if there was a way for the program to recognize the previous NFTs via the existing JSON files and then continue the creation process uniquely.

**Comment by ElDla** [comment]
I think this would be useful for many of us. I'm still working on finding a way to do it.
