### ISSUE TITLE
script generating wierd images that are very blurry

### ISSUE THREAD

**Issue by leon2241** [HashLips/hashlips_art_engine#78]
![2](https://user-images.githubusercontent.com/86055143/135522648-bfe3477f-533f-4dcb-a974-c835b6329aee.png)
why is my image being generated so blurry? all my layers are clear and in png format and not so disorted...

**Comment by DanOlise** [comment]
I had this issue. Your images are most likely in 16/32 bit. Reduce them to 8 bit and they will look normal when generated.
