### ISSUE TITLE
same image for 500 nfts

### ISSUE THREAD

**Issue by ghost** [HashLips/hashlips_art_engine#783]
hello guys, how do I create 500 nft using just one picture? 1 picture - 500 NFT, thanks for help

**Comment by bolshoytoster** [comment]
@vts666 you want 500 images that look the exact same?

**Comment by bolshoytoster** [comment]
@vts666 hashlips doesn't support duplicates, you can disable the check by changing the line
https://github.com/HashLips/hashlips_art_engine/blob/7ea809424694e4f3348d0c2281eb8d9e8e483649/src/main.js#L363
to
```js
      if (true) {
```
around line 363 in `src/main.js`.

**Comment by vts666** [comment]
it works, спасибо)
