### ISSUE TITLE
Preview png amount of pictures

### ISSUE THREAD

**Issue by wyrw** [HashLips/hashlips_art_engine#789]
Hi everyone, can you help me with this task? I have collection with 10k pictures, dont want to create a preview with whole collection only with chosen ones, or the same colors ones, or simply just first 30 from 10k collection. Is it possible?

**Comment by bolshoytoster** [comment]
@wyrw hashlips doesn't support this; you could create a dummy `build/json/_metadata.json` file with only the images you want (make a backup of the original file).

**Comment by wyrw** [comment]
> @wyrw hashlips doesn't support this; you could create a dummy `build/json/_metadata.json` file with only the images you want (make a backup of the original file).

thanks man!
