### ISSUE TITLE
Syntax Error: unexpected token . line 94 in main.js

### ISSUE THREAD

**Issue by kkevin6000** [HashLips/hashlips_art_engine#792]
When I run the node index.js command, there is a syntax error: 

 node index.js
C:\Users\Kevin\Documents\Programming Demos\hashlips_art_engine\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token '.'
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1053:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1101:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\Users\Kevin\Documents\Programming Demos\hashlips_art_engine\index.js:2:39)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m

**Comment by bolshoytoster** [comment]
@kkevin6000 update your node.

**Comment by kkevin6000** [comment]
Thanks, that worked
