### ISSUE TITLE
Backgrounds do not change

### ISSUE THREAD

**Issue by GGSargsyan** [HashLips/hashlips_art_engine#802]
I'm seeing something odd where the backgrounds do not change. I have four different colored backgrounds: blue, navy, orange, and purple. They are 3470 by 5000 pixels in size and I set the width and height in my config.js to be 347 and 500 respectively. 

The program only uses the first background from the folder which is Blue because it is ordered alphabetically. I even tried running the program with only the backgrounds as the only layer. It will create a maximum of 7 photos, all of them the same background, with the console registering multiple "Duplicate creation"s. It will then terminate only having created the same background 7 times.

Also, I am experiencing the same issue as this user: https://github.com/HashLips/hashlips_art_engine/issues/581
I've made sure that all my png photos are transparent. Any other ideas of what I can do?

**Comment by GGSargsyan** [comment]
I have also tried assigning bypassDNA to options in layersOrder with no luck.

**Comment by GGSargsyan** [comment]
I realized my mistake, please ignore.

**Comment by bolshoytoster** [comment]
@GGSargsyan [in future, you should say what your mistake was so anyone that has the same issue can fix their mistake more easily.](https://xkcd.com/979/)
