### ISSUE TITLE
NFTs are not generating.

### ISSUE THREAD

**Issue by Priyarajsinh** [HashLips/hashlips_art_engine#804]
Everything I did correctly and build folder is also coming, but main problem is this that no images are generated, only folder is generate every single time . Please help me with this problem . I used v.1.0.6 version

**Comment by bolshoytoster** [comment]
@Priyarajsinh is the output when you're generating normal (`Created edition: x, with DNA: y`/`Edition exists!`)

**Comment by Priyarajsinh** [comment]
> @Priyarajsinh is the output when you're generating normal (`Created edition: x, with DNA: y`/`Edition exists!`]
I dont know what that means but, you tell me what to do next to generate nft collection easily . Please help me

**Comment by bolshoytoster** [comment]
@Priyarajsinh what does it say when you run `node index.js`.

**Comment by Priyarajsinh** [comment]
> @Priyarajsinh what does it say when you run `node index.js`.

C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update>node index.js
C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\config.js
C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\main.js:54
  var dna = Number(_str.split(":").shift());
                        ^

TypeError: Cannot read properties of undefined (reading 'split')
    at cleanDna (C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\main.js:54:25)
    at C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\main.js:151:22
    at Array.find (<anonymous>)
    at C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\main.js:150:42
    at Array.map (<anonymous>)
    at constructLayerToDna (C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\main.js:149:35)
    at startCreating (C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\main.js:248:23)
    at C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\index.js:13:3
    at Object.<anonymous> (C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\index.js:14:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)

C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update>C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update>node index.js
'C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update' is not recognized as an internal or external command,  
operable program or batch file.

C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update>C:\Users\priya\Downloads\hashlips_art_engine-1.0.6_update\hashlips_art_engine-1.0.6_update\src\config.js

**Comment by bolshoytoster** [comment]
@Priyarajsinh try using a more recent version.

**Comment by Priyarajsinh** [comment]
> @Priyarajsinh try using a more recent version.



> @Priyarajsinh try using a more recent version.

I tried in latest version , tell me  if i did something  wrong

C:\Users\priya\Downloads\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5>npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

added 65 packages, and audited 66 packages in 28s

6 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (3 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

C:\Users\priya\Downloads\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5>yarn install
yarn install v1.22.17
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 39.40s.

C:\Users\priya\Downloads\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5>node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\priya\Downloads\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5/modules/HashlipsGiffer.js'
Require stack:
- C:\Users\priya\Downloads\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5\src\main.js
- C:\Users\priya\Downloads\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\priya\Downloads\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5\src\main.js:32:24)        
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\priya\\Downloads\\hashlips_art_engine-1.1.2_patch_v5\\hashlips_art_engine-1.1.2_patch_v5\\src\\main.js',
    'C:\\Users\\priya\\Downloads\\hashlips_art_engine-1.1.2_patch_v5\\hashlips_art_engine-1.1.2_patch_v5\\index.js'
  ]
}

**Comment by bolshoytoster** [comment]
@Priyarajsinh there should be a `modules/` folder. Try downloading the full zip again. Also you only need to run `npm install` of `yarn install`, not both.

**Comment by Priyarajsinh** [comment]
> @Priyarajsinh there should be a `modules/` folder. Try downloading the full zip again. Also you only need to run `npm install` of `yarn install`, not both.

I tried in latest version , but i did not change anything and i run npm install and then node index.js and pics were generated . Then i increased number of images to 10 but , it generated only 5 pics\s . Then i decreased number of images to 2 , then also it genertaed 5 images . But every time images were of different combinations . So tell me how to increase number of images.

**Comment by bolshoytoster** [comment]
@Priyarajsinh can you paste your `src/config.js` please.

**Comment by Priyarajsinh** [comment]
> @Priyarajsinh can you paste your `src/config.js` please.

now it's generating perfectly , i saw your comment on another issue ans i saved it first and then , it works perfectly

**Comment by Priyarajsinh** [comment]
> @Priyarajsinh can you paste your `src/config.js` please.

now it's generating perfectly , i saw your comment on another issue ans i saved it first and then , it works perfectly. Thanks a lot :)

**Comment by nurekend** [comment]
> > @Priyarajsinh можете ли вы вставить свой `src/config.js`пожалуйста.
> 
> теперь он отлично генерируется , я видел ваш комментарий по другому вопросу , и я сначала сохранил его, а затем он отлично работает. Большое спасибо :)

а как сохранить?

**Comment by bolshoytoster** [comment]
@nurekend `ctrl` + `s`.
