### ISSUE TITLE
Missing layer

### ISSUE THREAD

**Issue by Kugesz** [HashLips/hashlips_art_engine#813]
So I have a really vierd issue. I want to genarete a collection size of 666 NFTs. And in the end results the skins of the character are missing sometimes, buit in the json files they have the proper value.

Can someone help me how can I fix that?

![2](https://user-images.githubusercontent.com/81580775/155844943-b667e732-a4fb-41fb-b100-0a253ad9e76b.png)
![Képkivágás](https://user-images.githubusercontent.com/81580775/155845001-17cb1b6d-bd3a-4ca2-ad43-507ad3fa1bc3.PNG)

![17](https://user-images.githubusercontent.com/81580775/155844949-2fc8550d-c504-40a8-9777-a4cb1458857a.png)
![Képkivágás1](https://user-images.githubusercontent.com/81580775/155845005-d34809f2-9c2e-4c4f-8a7f-81874123e3a5.PNG)
![Képkivágás2](https://user-images.githubusercontent.com/81580775/155845008-39cc9b86-e92e-4caf-89b4-fcddab76adfa.PNG)

**Comment by bolshoytoster** [comment]
@Kugesz you could try exporting the `White.png` again from whatever editor you used.

**Comment by Kugesz** [comment]
> @Kugesz you could try exporting the `White.png` again from whatever editor you used.

I tried to export again from Photoshop and it didnt worked

**Comment by bolshoytoster** [comment]
@Kugesz is it just the `White.png` that isn't showing/ does it show in other images?

**Comment by Kugesz** [comment]
> @Kugesz is it just the `White.png` that isn't showing/ does it show in other images?

Its showing on other images its happens all of the types of sking but only with the skin

**Comment by LegendLancer** [comment]
@Kugesz 
How did you fix the issue?

**Comment by ermiasabera** [comment]
I am experiencing this issue
