### ISSUE TITLE
How to match the traits? 

### ISSUE THREAD

**Issue by aibinary** [HashLips/hashlips_art_engine#82]
Lets say, we want to match eye color with face color, how can we do it using this program?

**Comment by zarifaziz** [comment]
can you be more specific? Are you trying to say you only want a specific face color for a particular eye color? So a sort of unique combination?

**Comment by aibinary** [comment]
How can I generate with matched combinations of layers? 

Of 10 layers, 3 are supposed to be with same color on image. Is there a parameter or a delimiter, we can't set? 

May be, we can have a function written for this feature? 

Many have been asking for the same across the discord.

**Comment by brantchoate** [comment]
we have a hands trait that needs to be separate from our body. But I want the colors to match. Is there a way to do that?
