### ISSUE TITLE
gif generating

### ISSUE THREAD

**Issue by genius665** [HashLips/hashlips_art_engine#830]
hello, i have problem with gif collection generating, assets is generating but not animating, just static pictures but in format .GIF, tried using layers and using GIF files! any idea how to fix?

> const gif = {
  export: true,
  repeat: 0,
  quality: 100,
  delay: 500,
};

**Comment by jalagar** [comment]
Hi @genius665 I was able to build a tool to do exactly this! it takes png layers and turns them into generative gifs.

Here's a medium article: https://jalagar-eth.medium.com/how-to-create-generative-animated-nft-art-in-under-an-hour-e7dab1785c56
And here's the repo: https://github.com/jalagar/Generative_Gif_Engine
Feel free to follow me on Twitter or DM me on Twitter with questions: https://twitter.com/jalagar_eth

You can see all 1k of them on https://opensea.io/collection/genesis-bouncing-ball. Let me know if you have any questions!
