### ISSUE TITLE
I need help! Do you know how to start hashlips_art_engine from the last image number I left off?

### ISSUE THREAD

**Issue by calvinvalerian** [HashLips/hashlips_art_engine#869]
My last image generated is #121 I need to start from 122

**Comment by bolshoytoster** [comment]
@calvinvalerian [my repo](https://github.com/bolshoytoster/hashlips_art_engine) supports this, you can just run it and it'll skip any images already generated.

**Comment by calvinvalerian** [comment]
Wow it did. But there is one problem. When I import the image collection from the original hashlips_art_engine to your repo, yours will overwrite the previously crafted images from the original haslips_art_engine.

Your repo solved my issue by the way if I start from scratch. Thanks :)

**Comment by bolshoytoster** [comment]
@calvinvalerian I think you need to copy over the `build/json` folder as well.

**Comment by calvinvalerian** [comment]
yes that's what I did it overwrite the original hashlips build folder

**Comment by bolshoytoster** [comment]
@calvinvalerian oh, it relies on the `build/json/_metadata.json` file, which isn't generated if you cancel it mid-generation.

**Comment by calvinvalerian** [comment]
oh yes it now makes sense I can see what _metadata.json do 
Greatly appreciate your work. Genius.
