### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Unsupported image type

### ISSUE THREAD

**Issue by Wentxz** [HashLips/hashlips_art_engine#87]
Can anyone please help me? I don't know what might be happening.
When I run the code, it usually generates the first few images and then returns the following error:

Created edition: 1, with DNA: 1,5,1,0,2,2,5
Created edition: 2, with DNA: 1,2,1,5,0,5,1
Created edition: 3, with DNA: 7,3,1,3,2,0,0
**(node:33120) UnhandledPromiseRejectionWarning: Error: Unsupported image type
    at setSource (C:\Users\--\hashlips_art_engine-1.0.0_update\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\--\hashlips_art_engine-1.0.0_update\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\--\hashlips_art_engine-1.0.0_update\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\--\hashlips_art_engine-1.0.0_update\node_modules\canvas\index.js:23:10)
    at C:\Users\--\hashlips_art_engine-1.0.0_update\src\main.js:101:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\--\hashlips_art_engine-1.0.0_update\src\main.js:100:10)
    at C:\--\hashlips_art_engine-1.0.0_update\src\main.js:158:29
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:33120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:33120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

Thanks!!

**Comment by fonzi69** [comment]
> I'm getting the same error. I think maybe some of my images are corrupted or have a format that the art engine doesn't recognize? It would be very helpful if the error message would contain the file name that it choked on.
> 
> EDIT: so, what I did to solve this issue is remove hidden Thumb.db files that are put there by Windows (thanks a lot), and run mogrify _._ which probably does nothing at all, but what the heck. It solved my problem though, so probably the Thumb file was the culprit.

Hey, How exactly do I remove the hidden Thumb.db files? Ans another thing, do I remove them from just the layer folders?

**Comment by bparticle** [comment]
@fonzi69 I'm running a linux terminal in the layers folder and use a command like `rm Thumb* `  to clean it up, along with several other commands to replace unsupported characters like hyphens. The engine is very picky and not precise with error handling, so it can be hard to figure out what's going wrong.
