### ISSUE TITLE
MODULE NOT FOUND. NODE INDEX.JS NOT WORKING

### ISSUE THREAD

**Issue by HakPerest** [HashLips/hashlips_art_engine#89]
PS C:\Users\pc\Downloads\hashlips_art_engine-1.0.5_update> node index.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\pc\Downloads\hashlips_art_engine-1.0.5_update\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
PS C:\Users\pc\Downloads\hashlips_art_engine-1.0.5_update>

**Comment by chrisninetyone** [comment]
Assuming index.js is in the project, have you tried deleting the `node_modules` folder and `package-lock.json` file and running `npm install` again?
