### ISSUE TITLE
Output images low quality

### ISSUE THREAD

**Issue by ecom-newb** [HashLips/hashlips_art_engine#896]
Original quality is clean - output is trash/pixelated 😬 

I can't figured out how to correct this??

Original:
<img width="400" alt="Screen Shot 2022-03-07 at 2 49 32 AM" src="https://user-images.githubusercontent.com/100897617/157017380-385913fb-198c-4117-b3a3-8049d3c12cbe.png">

Output:
<img width="400" alt="Screen Shot 2022-03-07 at 2 49 49 AM" src="https://user-images.githubusercontent.com/100897617/157017389-7eefb5e5-8a25-4460-86c8-67e82099eda6.png">

**Comment by bolshoytoster** [comment]
@ecom-newb you can turn up the output resolution in `src/config.js` ~line 45:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/config.js#L44-L48

change width and height to the resolution of your layer images.

**Comment by ecom-newb** [comment]
@bolshoytoster Resolution of layers are 300x300... I set it to that in config.js and it looks like this :(

<img width="239" alt="Screen Shot 2022-03-09 at 5 29 24 PM" src="https://user-images.githubusercontent.com/100897617/157569330-c90d716f-a17d-46ec-b1d3-4757a1f32d65.png">

<img width="248" alt="Screen Shot 2022-03-09 at 5 28 23 PM" src="https://user-images.githubusercontent.com/100897617/157569324-7c423495-764d-433d-878c-e7532dd382a5.png">

<img width="200" alt="Screen Shot 2022-03-09 at 5 28 55 PM" src="https://user-images.githubusercontent.com/100897617/157569327-eb85fbaa-88d7-494b-853e-a027f15a4917.png">

**Comment by bolshoytoster** [comment]
@ecom-newb [my repo](https://github.com/bolshoytoster/hashlips_art_engine) has support for this, but if you're lazy (like me) you can just follow [this](https://github.com/HashLips/hashlips_art_engine/issues/901#issuecomment-1061764884).

**Comment by ecom-newb** [comment]
@bolshoytoster thank you so much! I edited the canvas code and changed the smoothing from false to true and this seemed to do the trick!
