### ISSUE TITLE
How the code locate each layer in the NFT picture

### ISSUE THREAD

**Issue by omer2307** [HashLips/hashlips_art_engine#897]
Hi, I have a theoretical question.
how the code knows how to locate each layer? and how can I change that location?
Thank you!

**Comment by bolshoytoster** [comment]
@omer2307 it’s based on the position within the input image. I could add functionality to chose position/size of a layer but I can’t be arsed.

**Comment by omer2307** [comment]
I see... thanks for the response. 
Then how can I add functionality to adjust the position of a specific item (and in main or config)? I'm looking for providing location for some special items in a specific layer. If you have an idea I would love you share, even if it only part solved.
Thanks!

**Comment by bolshoytoster** [comment]
@omer2307 in `src/main.js` ~line 90:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L90-L108

you could add at the end:
```js
    posX:
      layerObj.options?.["posX"] != undefined 
       ? layerObj.options?.["posX"] 
       : 0,
    posY:
      layerObj.options?.["posY"] != undefined 
       ? layerObj.options?.["posY"] 
       : 0,
    sizeX:
      layerObj.options?.["sizeX"] != undefined 
       ? layerObj.options?.["sizeX"] 
       : format.width,
    sizeY:
      layerObj.options?.["sizeY"] != undefined 
       ? layerObj.options?.["sizeY"] 
       : format.height,
```
Then at ~line 211:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L211-L217

Change it to:
```js
    : ctx.drawImage( 
      _renderObject.loadedImage, 
      _renderObject.layer.posX, 
      _renderObject.layer.posY, 
      _renderObject.layer.sizeX, 
      _renderObject.layer.sizeY 
    );
```
Then in your `layersOrder` you can add e.g.:
```js
      { name: "Background", options: { posX: 128, posY: 128 } },
```
To give the layer an offset of 128 pixels from top-left.

**Comment by omer2307** [comment]
great! thanks, I'll try it.

**Comment by omer2307** [comment]
It actually outputted the images with the background all over the image.
When I listed the layers in config I inserted the posX and posY only, so why should I add to the layers setup size? the size gets its place and needed probably other place.
Do you have any idea what's the problem? Maybe its connected to the part I mentioned?

**Comment by bolshoytoster** [comment]
@omer2307 do you mean all of the other layers are covered up by the background?

**Comment by omer2307** [comment]
No, I'm using the hashlips_art_engine file as specifies in this repo, so there is only one black background so its not possible to come from the background.  I'm adding two examples below. The other images are kind of the same with random colors.
![1](https://user-images.githubusercontent.com/99732978/157287699-86ec6fe0-b343-44d2-b3f7-6244b1fff52a.png)
![2](https://user-images.githubusercontent.com/99732978/157287702-89dc53c2-c32f-4992-af1e-2075d69b4efe.png)

**Comment by bolshoytoster** [comment]
@omer2307 it looks like it's either drawing your layers off the canvas or not at all.Does it work without any of the `posX`/`posY` stuff in `src/config.js`?

**Comment by omer2307** [comment]
yes, before the changes the result of the build was the eyes images.
Did you tried it? maybe if it works for you, you can share here the whole changes of the code.
I didn't get it why to add this part if we don't inset the size in any part of the code (like in config we insert each pos the each layer).

```
sizeX:
        layerObj.options?.["sizeX"] != undefined 
         ? layerObj.options?.["sizeX"] 
         : format.width,
      sizeY:
        layerObj.options?.["sizeY"] != undefined 
         ? layerObj.options?.["sizeY"] 
         : format.height,

```

**Comment by bolshoytoster** [comment]
@omer2307
> Did you tried it? maybe if it works for you, you can share here the whole changes of the code.

No, I will do when I get home (~6 hours).

> I didn't get it why to add this part

That part is to allow compatability for it, it defaults to the whole page if you don't specify it.

**Comment by omer2307** [comment]
Great, thanks.

**Comment by bolshoytoster** [comment]
@omer2307 I've figured out the issue; you also need to add:
```js
      posX: layer.posX,
      posY: layer.posY,
      sizeX: layer.sizeX,
      sizeY: layer.sizeY,
```
at the end of this code, ~line 231:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L227-L231

**Comment by omer2307** [comment]
Great!! That works perfectly!
Are you the author or contributer of this repo? 
If negative, how do you understand that code package so good?
A lot of appreciation, keep it up.

**Comment by bolshoytoster** [comment]
@omer2307 I have a [fork](https://github.com/bolshoytoster/hashlips_art_engine) of this repo, it's more up to date because @HashLips has basically been inactive since janurary.

**Comment by omer2307** [comment]
I see...
what's the main difference between the original and your fork? 
Maybe I'll end up using yours edition.

**Comment by bolshoytoster** [comment]
@omer2307 they're mostly the same, just some performance/usability improvements.

If you want to be able to move/resize layers though I'm not sure if my fork will support it easily.

**Comment by chuanxd** [comment]
This issue page is very helpful to me.
