### ISSUE TITLE
NFT generate Error

### ISSUE THREAD

**Issue by WebDev-Learner** [HashLips/hashlips_art_engine#898]
I can't generate NFT. It has shown "missing script" how can i solve it?

**Comment by bolshoytoster** [comment]
@HtooKhant2001 can you paste the actual error please.

**Comment by WebDev-Learner** [comment]
@bolshoytoster i had already solved it and thank you.

**Comment by DesGenArt** [comment]
@HackyLeon how did you solve it? I'm experiencing the same error now.

**Comment by bolshoytoster** [comment]
@DesGenArt can you paste the error here please.

**Comment by dua1422** [comment]
> @DesGenArt can you paste the error here please.
I am getting this error, can u help me out please
npm ERR! Missing script: "generate"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kk\AppData\Local\npm-cache\_logs\2022-07-09T22_25_50_365Z-debug-0.log

**Comment by dua1422** [comment]
> @DesGenArt can you paste the error here please.

i'm getting this error can u help me out pls?

npm ERR! Missing script: "generate"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kk\AppData\Local\npm-cache\_logs\2022-07-09T22_25_50_365Z-debug-0.log

**Comment by bolshoytoster** [comment]
@dua1422 you're in the wrong folder. Run `Get-ChildItem -Directory` to get the name, then run `cd ` + the name to change into it.
