### ISSUE TITLE
Newbie needs help.

### ISSUE THREAD

**Issue by tryshka** [HashLips/hashlips_art_engine#919]
![157136972-571f6fed-0930-4d60-b770-2559d5aeb154](https://user-images.githubusercontent.com/101057184/157452791-aef2a6cf-14e2-49aa-a0db-0b1ac89d3b63.png)
What do I need to do? help please.

**Comment by bolshoytoster** [comment]
@tryshka I'm not completely sure about this error, but whenever I see it it's because there's russian in the path.

You could try moving the hashlips folder to somewhere that doesn't have russian in the name (e.g. `C:/Users/Public/`).

**Comment by tryshka** [comment]
> @tryshka Я не совсем уверен в этой ошибке, но всякий раз, когда я ее вижу, это потому, что в пути есть русский язык.
> 
> Вы можете попробовать переместить папку hashlips куда-нибудь, где нет русского языка в названии (например `C:/Users/Public/`).

Thank you very much

**Comment by vishal-raj15** [comment]
you don't have that ....pink#0.png image , maybe

**Comment by bolshoytoster** [comment]
@vishal-raj15 I think they do, otherwise it wouldn't try to open it.

**Comment by vishal-raj15** [comment]
you are using windows , windows have a little different path formatting : " c:\ project \ hashlips \ background \ pink#0. png " , not with  " / " format

**Comment by bolshoytoster** [comment]
@vishal-raj15 the forward slash is compatible with every modern OS (including windows). The backslash can actually cause more problems because [it's used as a marker character](https://softwareengineering.stackexchange.com/a/112733) basically telling an interpreter to skip the next character.

**Comment by bolshoytoster** [comment]
@tryshka did you fix this?

If so, how?

[relevant](https://xkcd.com/979/)
