### ISSUE TITLE
What is ERR_DLOPEN_FAILED?

### ISSUE THREAD

**Issue by oaoaoaoaoammm** [HashLips/hashlips_art_engine#937]
The module '/Users/mac/Downloads/GENERATOR/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1185:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mac/Downloads/GENERATOR/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by bolshoytoster** [comment]
@ddoo5 this is a notorious issue with M1 macs.

You could try looking at [other related issues](https://github.com/HashLips/hashlips_art_engine/issues?q=is%3Aissue+M1) for potential solutions.

**Comment by oaoaoaoaoammm** [comment]
> @ddoo5 this is a notorious issue with M1 macs.
> 
> 
> 
> You could try looking at [other related issues](https://github.com/HashLips/hashlips_art_engine/issues?q=is%3Aissue+M1) for potential solutions.

so i have mac os, but on intel.

**Comment by bolshoytoster** [comment]
@ddoo5 sorry, I saw mac and assumed that was the issue.

The error suggests running `npm rebuild`, you should try that.

**Comment by oaoaoaoaoammm** [comment]
> @ddoo5 sorry, I saw mac and assumed that was the issue.
> 
> 
> 
> The error suggests running `npm rebuild`, you should try that.

i've already tried, same result

**Comment by oaoaoaoaoammm** [comment]
> @ddoo5 sorry, I saw mac and assumed that was the issue.
> 
> 
> 
> The error suggests running `npm rebuild`, you should try that.

"npm run build" i tried too, same error

**Comment by bolshoytoster** [comment]
@ddoo5 not `npm run build`, run `npm rebuild`.

**Comment by oaoaoaoaoammm** [comment]
> @ddoo5 not `npm run build`, run `npm rebuild`.

did, nothing changed

**Comment by bolshoytoster** [comment]
@ddoo5 try deleting the `node_modules` folder then running `npm install` again.

**Comment by oaoaoaoaoammm** [comment]
> @ddoo5 try deleting the `node_modules` folder then running `npm install` again.

thx, best library i've ever used ^_^

**Comment by mpaata** [comment]
it has still failed to work on version 20

**Comment by bolshoytoster** [comment]
@mpaata can you paste your full error here?
