### ISSUE TITLE
(node:40060) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Dr-SIRM** [HashLips/hashlips_art_engine#94]
<img width="951" alt="Screen Shot 2021-10-08 at 6 21 25 pm" src="https://user-images.githubusercontent.com/91543656/136597598-d075ca22-0c21-4f2b-a8fc-675f26d1dd2e.png">
 
Can someone help me with this error? much appreciated !

**Comment by chrisninetyone** [comment]
If you don't want to include a rarity delimiter:
https://github.com/HashLips/hashlips_art_engine/pull/95
