### ISSUE TITLE
How to pixelate gifs?

### ISSUE THREAD

**Issue by Lypheal** [HashLips/hashlips_art_engine#947]
I am not able to pixelate gif files using _node utils/pixelate.js_

**Comment by bolshoytoster** [comment]
@Lypheal it wouldn't be possible because the library we use to make the gifs doesn't support loading them.

**Comment by Lypheal** [comment]
Is it possible if they were generated by something else?

**Comment by bolshoytoster** [comment]
@Lypheal probably, but it doesn’t look like anyone else wants this, so you’d have to implement it yourself.

**Comment by thepeanutgalleryandco** [comment]
@Lypheal what process wil lbe creating your gifs?
