### ISSUE TITLE
One layer create more than one attribute to fix an attribute hierarchy problem

### ISSUE THREAD

**Issue by bettyboomy** [HashLips/hashlips_art_engine#954]
Hello everybody,

Thanks in advance for your help and amazing work!

I need to know if it is possible: That one layer create different attributes in json file.

For example: 

A layer call "face" can generate two attributes in json file: "black" and "smile".

I'm asking this because I have this problem (maybe someone else comes up with another solution):  I would like my NFT collection to be well sorted, so that users can search for their NFT by selecting certain attributes. The problem is that some features belong to different layers, I mean the same feature is repeated in different layers. In addition, the structure is pyramidal, there are lower level characteristics that must belong to other higher level characteristics, I cannot just mix them, because then they would be incorrectly associated.

I give an example: A collection of NFT about maps of cities in the world. One layer has to be "city", another "country" and another "continent". What I would need would be that when I create the map of "Paris" its attributes should be "Paris", "France" and "Europe". It is clear that I cannot create a layer for each one, because when the whole collection is created it will not respect the hierarchy and will mix all the cities, with all the countries and all the continents.

Best regards!

Betty

**Comment by thepeanutgalleryandco** [comment]
Hi @bettyboomy 

Feel free to check out my repo's filtration options that allows for dependant traits ( which I think you are in need of ), maximum repeatability and incompatable traits.

Cheers,
Rohan

**Comment by bettyboomy** [comment]
> 

Hello @thepeanutgalleryandco,

Thanks Rohan for your answer, I think you're right :) (although since I'm not an expert at all and English is not my mother tongue, I'll see if I'm able to understand everything).

BR
Betty
