### ISSUE TITLE
Preview.js Bug

### ISSUE THREAD

**Issue by C0retek** [HashLips/hashlips_art_engine#963]
preview.js line 35 reads like:
`    await loadImage(`${buildDir}/images/${nft.custom_fields.edition}.png`).then((image) => {`

but actually I think it should be:

`    await loadImage(`${buildDir}/images/${nft.edition}.png`).then((image) => {`

**Comment by bolshoytoster** [comment]
@C0retek I think it should probably be
```js
await loadImage(`${buildDir}/images/${nft.edition ?? nft.custom_fields.edition}.png`).then((image) => {
```

**Comment by C0retek** [comment]
True ! 😉
