### ISSUE TITLE
build run problem 

### ISSUE THREAD

**Issue by ArmaBloody** [HashLips/hashlips_art_engine#965]
User@ArmaBloody MINGW64 ~/OneDrive/Рабочий стол/nft/hashlips_art_engine (main)
$ npm run build

> hashlips_art_engine@1.1.1 build
> node index.js

(node:13192) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\User\OneDrive\Рабочий стол\nft\hashlips_art_engine\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: ENOENT, No such file or directory 'C:\Users\User\OneDrive\Рабочий стол\nft\hashlips_art_engine/layers/Background/Black#1.png'
    at setSource (C:\Users\User\OneDrive\Рабочий стол\nft\hashlips_art_engine\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\User\OneDrive\Рабочий стол\nft\hashlips_art_engine\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\User\OneDrive\Рабочий стол\nft\hashlips_art_engine\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\User\OneDrive\Рабочий стол\nft\hashlips_art_engine\node_modules\canvas\index.js:23:10)
    at C:\Users\User\OneDrive\Рабочий стол\nft\hashlips_art_engine\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\User\OneDrive\Рабочий стол\nft\hashlips_art_engine\src\main.js:184:12)
    at C:\Users\User\OneDrive\Рабочий стол\nft\hashlips_art_engine\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\User\\OneDrive\\Рабочий стол\\nft\\hashlips_art_engine/layers/Background/Black#1.png',
  syscall: 'fopen'
}

**Comment by bolshoytoster** [comment]
@ArmaBloody can you move the project folder away from any path with russian characters please (e.g. `C:/Users/Public`).

**Comment by ArmaBloody** [comment]
Russia characters it's my desktop
can i change my windows language ??

**Comment by bolshoytoster** [comment]
@ArmaBloody you don't need to change the language, you can just move the project folder to somewhere like `C:/Users/Public`.

**Comment by ArmaBloody** [comment]
ok thanks :)

**Comment by ArmaBloody** [comment]
Thank you it worked:))
