### ISSUE TITLE
iMac:hashlips_art_engine-1.0.0_update jahromemissick$ yarn add all bash: yarn: command not found 

### ISSUE THREAD

**Issue by speakerheadzsociety** [HashLips/hashlips_art_engine#98]
When I get to the step of "yarn add all", this is the code it kicks back. It doesn't show any loading of canvas or anything. The code is below. 

Jahromes-iMac:hashlips_art_engine-1.0.0_update jahromemissick$ yarn add all
bash: yarn: command not found
Jahromes-iMac:hashlips_art_engine-1.0.0_update jahromemissick$

**Comment by chrisninetyone** [comment]
try `npm install -g yarn`
