### ISSUE TITLE
  at processTicksAndRejections (node:internal/process/task_queues:96:5)

### ISSUE THREAD

**Issue by CandyClanNFT** [HashLips/hashlips_art_engine#988]
Please help!

**Comment by CandyClanNFT** [comment]
This happens when i'm trying to run generate my images.

**Comment by bolshoytoster** [comment]
@CandyClanNFT can you paste the **full** error please.

**Comment by CandyClanNFT** [comment]
Bryces-MacBook-Air:hashlips_art_engine-1.1.2_patch_v6 3 Nicholson_approved$ npm run build

> hashlips_art_engine@1.1.1 build
> node index.js

(node:56478) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:314
  let metadata = metadataList.find((meta) => meta.custom_fields.edition == _editionCount);
                                                                ^

TypeError: Cannot read properties of undefined (reading 'edition')
    at /Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:314:65
    at Array.find (<anonymous>)
    at saveMetaDataSingleFile (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:314:31)
    at /Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:409:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startCreating (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:374:9)
Bryces-MacBook-Air:hashlips_art_engine-1.1.2_patch_v6 3 Nicholson_approved$

**Comment by bolshoytoster** [comment]
@CandyClanNFT can you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine) please.

**Comment by CandyClanNFT** [comment]
@bolshoytoster I would really love it if I didn't have to start this process from scratch. Can you help me otherwise?

**Comment by bolshoytoster** [comment]
@CandyClanNFT you can copy your config/images over.

**Comment by CandyClanNFT** [comment]
How do I fix my issue?

**Comment by bolshoytoster** [comment]
@CandyClanNFT my repo fixes  the bug.

**Comment by CandyClanNFT** [comment]
Why? what's the bug?

**Comment by bolshoytoster** [comment]
@CandyClanNFT
> /Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:314
let metadata = metadataList.find((meta) => meta.custom_fields.edition == _editionCount);
^
>
> TypeError: Cannot read properties of undefined (reading 'edition')
at /Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:314:65
at Array.find ()
at saveMetaDataSingleFile (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:314:31)
at /Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:409:11
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async startCreating (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:374:9)
