### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by HueLuna** [HashLips/hashlips_art_engine#995]
Hey, can someone help me with my issue please. I make sure there were no - characters in my names. I also used # for rarity value and ensured it equalled to 100 for each element names in each of my layers.However I still get this Error.

Microking-MBP:hashlips_art_engine-main microking$ node index.js
(node:19784) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/microking/Desktop/hashlips_art_engine-main/src/main.js:274
  return _dna.replace(query, "");
              ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at removeQueryStrings (/Users/microking/Desktop/hashlips_art_engine-main/src/main.js:274:15)
    at cleanDna (/Users/microking/Desktop/hashlips_art_engine-main/src/main.js:60:26)
    at /Users/microking/Desktop/hashlips_art_engine-main/src/main.js:225:22
    at Array.find (<anonymous>)
    at /Users/microking/Desktop/hashlips_art_engine-main/src/main.js:224:42
    at Array.map (<anonymous>)
    at constructLayerToDna (/Users/microking/Desktop/hashlips_art_engine-main/src/main.js:223:35)
    at startCreating (/Users/microking/Desktop/hashlips_art_engine-main/src/main.js:364:23)
    at /Users/microking/Desktop/hashlips_art_engine-main/index.js:6:3
    at Object.<anonymous> (/Users/microking/Desktop/hashlips_art_engine-main/index.js:7:3)
microking's-MBP:hashlips_art_engine-main microking$

**Comment by bolshoytoster** [comment]
@HueWaves can you use [my fork](https://github.com/bolshoytoster/hashlips_art_engine) please.

**Comment by HueLuna** [comment]
I figured it out. So basically I deleted the # in config.js and reentered it then saved config.js. sounds weird but that's what I did and it worked.

**Comment by HueWaves** [comment]
@bolshoytoster Hey, I still learning and I was having another issue and I'm hoping you could help me out. I'm using "hashlips_art_engine-1.1.2_patch_v6" So basically I generated 9000 images and uploaded the image folder on IPFS, when I click on inspect in IPFS it says that I have **256 links** but when I click on one of these links there are about 30 different links within each one of those 256 links. However, when I click on the folder uploaded on IPFS there are all 9000 pngs inside each with it's own link. Is that normal? 

My second issue is when I copy the CID for the folder on IPFS and try to pin it to Pinata, the status says "searching" I tried pinning the CID many times and for the pass 3 days piñata status has not changed or been able to pin the CID. Also I insured to have the IPFS Desktop running while I was doing all of this but still no changes in the piñata status. Could you tell me how I would fix this?
 Thank you.
