### ISSUE TITLE
[Question] Add new trait to existing collection to evolve and expand collection

### ISSUE THREAD

**Issue by C0retek** [HashLips/hashlips_art_engine#998]
I have a challenge and I hope that someone has an idea how to do this:

100 Images were generated in a first run. 

In a second run I want to add 1 trait to the collection:
--> Each image of the 100 will be available with 1 new trait that has 10 different expressions 
--> Generate / expand collection to  10 x 100 = 1000  (update images and meta)

Requirement: I can not reuse the old layers from the first run. 
The 2nd run can only take as input the build folder from the first run.

Let me know if you have any ideas...

**Comment by bolshoytoster** [comment]
@C0retek you could put the first collection as a background layer and put the new trait in a new layer:
```js
const layerConfigurations = [
  {
    growEditionSizeTo: 1000,
    layersOrder: [
      { name: "Original" },
      { name: "New" },
    ],
  },
];
```

**Comment by C0retek** [comment]
Thank you for your reply @bolshoytoster 

For generating the image that definitely works - my challenge is to update / expand the metadata. I want to keep all the previous metadata and traits information from the first run, but add a trait meaning expand also the metadata. All based only on the build folder from previous run.

Recreate / expand based on existing json files.

**Comment by bolshoytoster** [comment]
@C0retek you'll have to implement this yourself since it doesn't look like anyone else particularly wants this feature. You could probably use [my fork](https://github.com/bolshoytoster/hashlips_art_engine) to make it easier, since it already loads the metadata anyway.

**Comment by C0retek** [comment]
In case someone has the same challenge, here is how I did it:

Add the images from the first run as layer into the layers folder. For example  { name: "Original" }. Add a function to main.js to read the meta data from previous "generate" (replace BUILD_OLD with where you saved the build directory with the Json files from the initial run):

`const getattributes = (filenumber) => {
  let rawdata = fs.readFileSync(`${BASEDIR}/BUILD_OLD/json/` + filenumber + `.json`);
  let oldmeta = JSON.parse(rawdata);
  return oldmeta.attributes;
}`

Then add the old traits while building the new meta data by adding this code in the beginning of the function "addAttributes" in main.js:

` 
if (_element.layer.name == "Original") {
const oldtraits = getattributes(selectedElement.name);
oldtraits.forEach((element) => {
addToAttrbutesList(element.trait_type, element.value);
});}
`

Hope it's clear :)
